In [1]:
import numpy as np
import pandas as pd

In [2]:
colo = pd.read_csv('C:/Users/karan/Colorada_basic_Buffer.csv')

C:\Users\karan\AppData\Local\Temp\ipykernel_26268\752822360.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  colo = pd.read_csv('C:/Users/karan/Colorada_basic_Buffer.csv')


In [3]:
colo.isna().sum()

ROAD_CLASS        0
DATE              0
TIME              0
INTERSECTION      0
CONTOUR           0
SURFACE           0
LIGHTING          0
WEATHER           0
HUMAN_FACTOR      0
INTOXICATION      0
AGE               0
GENDER            0
COUNTY_FIPS       0
COUNTY            0
LATITUDE          0
LONGITUDE         0
YEAR              0
INJURY_COUNT      0
INJURY_OUTCOME    0
Crash_ID          0
BUFF_DIST         0
ORIG_FID          0
Shape_Length      0
Shape_Area        0
dtype: int64

In [4]:
colo.isnull().sum()

ROAD_CLASS        0
DATE              0
TIME              0
INTERSECTION      0
CONTOUR           0
SURFACE           0
LIGHTING          0
WEATHER           0
HUMAN_FACTOR      0
INTOXICATION      0
AGE               0
GENDER            0
COUNTY_FIPS       0
COUNTY            0
LATITUDE          0
LONGITUDE         0
YEAR              0
INJURY_COUNT      0
INJURY_OUTCOME    0
Crash_ID          0
BUFF_DIST         0
ORIG_FID          0
Shape_Length      0
Shape_Area        0
dtype: int64

In [5]:
colo.columns

Index(['ROAD_CLASS', 'DATE', 'TIME', 'INTERSECTION', 'CONTOUR', 'SURFACE',
       'LIGHTING', 'WEATHER', 'HUMAN_FACTOR', 'INTOXICATION', 'AGE', 'GENDER',
       'COUNTY_FIPS', 'COUNTY', 'LATITUDE', 'LONGITUDE', 'YEAR',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'Crash_ID', 'BUFF_DIST', 'ORIG_FID',
       'Shape_Length', 'Shape_Area'],
      dtype='object')

In [6]:
colo['YEAR'].unique()

array([2019, 2020, 2021], dtype=int64)

In [7]:
colo_2019 = colo[colo['YEAR']== 2019]
colo_2020 = colo[colo['YEAR']==2020]
colo_2021 = colo[colo['YEAR']==2021]

In [8]:
colo_2019.shape

(108647, 24)

In [9]:
colo_2020.shape

(74059, 24)

In [10]:
colo_2021.shape

(34584, 24)

In [11]:
colo_2019['WEATHER'].unique()

array([4, 8, 7, 2, 5], dtype=int64)

In [12]:
colo_2020['WEATHER'].unique()

array([8, 4, 7, 2, 5], dtype=int64)

In [13]:
colo_2021['WEATHER'].unique()

array([11,  2, 12,  4,  7,  6,  3,  5], dtype=int64)

In [14]:
weather_mapping = {
    11: 'CLEAR',
    12: 'CLOUDY',
    5: 'FOG',
    2: 'RAIN',
    3: 'SLEET/HAIL',
    8: 'OTHER_WEATHER',
    0: 'UNKNOWN_WEATHER',
    4: 'SNOW_WEATHER',
    6: 'BLOWING SAND/SNOW',
    7: 'SEVERE CROSSWINDS'
}


colo_2019['WEATHER_DESC'] = colo_2019['WEATHER'].map(weather_mapping)
colo_2020['WEATHER_DESC'] = colo_2020['WEATHER'].map(weather_mapping)
colo_2021['WEATHER_DESC'] = colo_2021['WEATHER'].map(weather_mapping)

def analyze_weather(df):
    grouped_weather = df.groupby(['COUNTY', 'WEATHER_DESC']).size().unstack(fill_value=0)
    total_counts_by_county_weather = grouped_weather.sum(axis=1)
    weather_percentages_df = (grouped_weather.div(total_counts_by_county_weather, axis=0) * 100).fillna(0)
    weather_percentages_df = weather_percentages_df.reset_index()
    return weather_percentages_df

weather_percentages_df_2019 = analyze_weather(colo_2019)
weather_percentages_df_2020 = analyze_weather(colo_2020)
weather_percentages_df_2021 = analyze_weather(colo_2021)

C:\Users\karan\AppData\Local\Temp\ipykernel_26268\4123123285.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colo_2019['WEATHER_DESC'] = colo_2019['WEATHER'].map(weather_mapping)
C:\Users\karan\AppData\Local\Temp\ipykernel_26268\4123123285.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colo_2020['WEATHER_DESC'] = colo_2020['WEATHER'].map(weather_mapping)
C:\Users\karan\AppData\Local\Temp\ipykernel_26268\4123123285.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice fr

In [15]:
weather_percentages_df_2019.columns

Index(['COUNTY', 'FOG', 'OTHER_WEATHER', 'RAIN', 'SEVERE CROSSWINDS',
       'SNOW_WEATHER'],
      dtype='object', name='WEATHER_DESC')

In [16]:
weather_percentages_df_2020.columns

Index(['COUNTY', 'FOG', 'OTHER_WEATHER', 'RAIN', 'SEVERE CROSSWINDS',
       'SNOW_WEATHER'],
      dtype='object', name='WEATHER_DESC')

In [17]:
weather_percentages_df_2021.columns

Index(['COUNTY', 'BLOWING SAND/SNOW', 'CLEAR', 'CLOUDY', 'FOG', 'RAIN',
       'SEVERE CROSSWINDS', 'SLEET/HAIL', 'SNOW_WEATHER'],
      dtype='object', name='WEATHER_DESC')

In [18]:
weather_percentages_df_2019.insert(1,'BLOWING SAND/SNOW',0)

In [19]:
weather_percentages_df_2019.insert(2,'CLEAR',0)

In [20]:
weather_percentages_df_2019.insert(3,'CLOUDY',0)

In [21]:
weather_percentages_df_2019.rename(columns={'OTHER': 'OTHER_WEATHER'}, inplace=True)

In [22]:
weather_percentages_df_2021.insert(5,'OTHER_WEATHER',0)

In [23]:
weather_percentages_df_2019.insert(8,'SLEET/HAIL',0)

In [24]:
weather_percentages_df_2020.rename(columns={'OTHER':'OTHER_WEATHER'},inplace=True)

In [25]:
weather_percentages_df_2020.insert(1,'BLOWING SAND/SNOW',0)

In [26]:
weather_percentages_df_2020.insert(2,'CLEAR',0)

In [27]:
weather_percentages_df_2020.insert(3,'CLOUDY',0)

In [28]:
weather_percentages_df_2020.insert(8,'SLEET/HAIL',0)

In [29]:
weather_percentages_df_2019.shape

(64, 10)

In [30]:
weather_percentages_df_2020.shape

(64, 10)

In [31]:
weather_percentages_df_2021.shape

(64, 10)

In [32]:
colo_2019 = pd.merge(colo_2019,weather_percentages_df_2019,on=['COUNTY'],how='left')

In [33]:
colo_2019.columns

Index(['ROAD_CLASS', 'DATE', 'TIME', 'INTERSECTION', 'CONTOUR', 'SURFACE',
       'LIGHTING', 'WEATHER', 'HUMAN_FACTOR', 'INTOXICATION', 'AGE', 'GENDER',
       'COUNTY_FIPS', 'COUNTY', 'LATITUDE', 'LONGITUDE', 'YEAR',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'Crash_ID', 'BUFF_DIST', 'ORIG_FID',
       'Shape_Length', 'Shape_Area', 'WEATHER_DESC', 'BLOWING SAND/SNOW',
       'CLEAR', 'CLOUDY', 'FOG', 'OTHER_WEATHER', 'RAIN', 'SEVERE CROSSWINDS',
       'SLEET/HAIL', 'SNOW_WEATHER'],
      dtype='object')

In [34]:
colo_2020 = pd.merge(colo_2020,weather_percentages_df_2020,on=['COUNTY'],how='left')

In [35]:
colo_2020.columns

Index(['ROAD_CLASS', 'DATE', 'TIME', 'INTERSECTION', 'CONTOUR', 'SURFACE',
       'LIGHTING', 'WEATHER', 'HUMAN_FACTOR', 'INTOXICATION', 'AGE', 'GENDER',
       'COUNTY_FIPS', 'COUNTY', 'LATITUDE', 'LONGITUDE', 'YEAR',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'Crash_ID', 'BUFF_DIST', 'ORIG_FID',
       'Shape_Length', 'Shape_Area', 'WEATHER_DESC', 'BLOWING SAND/SNOW',
       'CLEAR', 'CLOUDY', 'FOG', 'OTHER_WEATHER', 'RAIN', 'SEVERE CROSSWINDS',
       'SLEET/HAIL', 'SNOW_WEATHER'],
      dtype='object')

In [36]:
colo_2021 = pd.merge(colo_2021,weather_percentages_df_2021,on=['COUNTY'],how='left')

In [37]:
colo_2021.columns

Index(['ROAD_CLASS', 'DATE', 'TIME', 'INTERSECTION', 'CONTOUR', 'SURFACE',
       'LIGHTING', 'WEATHER', 'HUMAN_FACTOR', 'INTOXICATION', 'AGE', 'GENDER',
       'COUNTY_FIPS', 'COUNTY', 'LATITUDE', 'LONGITUDE', 'YEAR',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'Crash_ID', 'BUFF_DIST', 'ORIG_FID',
       'Shape_Length', 'Shape_Area', 'WEATHER_DESC', 'BLOWING SAND/SNOW',
       'CLEAR', 'CLOUDY', 'FOG', 'OTHER_WEATHER', 'RAIN', 'SEVERE CROSSWINDS',
       'SLEET/HAIL', 'SNOW_WEATHER'],
      dtype='object')

In [38]:
colo_2019['LIGHTING'].unique()

array([4, 3, 1, 5, 2], dtype=int64)

In [39]:
colo_2020['LIGHTING'].unique()

array([3, 1, 4, 2, 5], dtype=int64)

In [40]:
colo_2021['LIGHTING'].unique()

array([4, 1, 3, 5, 2], dtype=int64)

In [41]:
map = {
    0:'UNKNOWN_LIGHT',
    1:'DAYLIGHT',
    2:'DAWN',
    3:'DARK-NOT LIGHTED',
    4:'DARK-LIGHTED',
    5:'DUSK',
    6:'DARK-UNKNOWN LIGHTING',
    8:'OTHER_LIGHT'
}

def process_lighting_data(df, mapping):
    df['LIGHTING_DESC'] = df['LIGHTING'].map(mapping)
    grouped_lighting = df.groupby(['COUNTY', 'LIGHTING_DESC']).size().unstack(fill_value=0)
    grouped_lighting = df.groupby(['COUNTY', 'LIGHTING_DESC']).size().unstack(fill_value=0)
    total_counts_by_county_lighting = grouped_lighting.sum(axis=1)
    lighting_percentages_df = (grouped_lighting.div(total_counts_by_county_lighting, axis=0) * 100).fillna(0)
    lighting_percentages_df = lighting_percentages_df.reset_index()
    
    return lighting_percentages_df

lighting_percentages_df_2019 = process_lighting_data(colo_2019, map)
lighting_percentages_df_2020 = process_lighting_data(colo_2020, map)
lighting_percentages_df_2021 = process_lighting_data(colo_2021, map)

In [42]:
lighting_percentages_df_2019.columns

Index(['COUNTY', 'DARK-LIGHTED', 'DARK-NOT LIGHTED', 'DAWN', 'DAYLIGHT',
       'DUSK'],
      dtype='object', name='LIGHTING_DESC')

In [43]:
lighting_percentages_df_2020.columns

Index(['COUNTY', 'DARK-LIGHTED', 'DARK-NOT LIGHTED', 'DAWN', 'DAYLIGHT',
       'DUSK'],
      dtype='object', name='LIGHTING_DESC')

In [44]:
lighting_percentages_df_2021.columns

Index(['COUNTY', 'DARK-LIGHTED', 'DARK-NOT LIGHTED', 'DAWN', 'DAYLIGHT',
       'DUSK'],
      dtype='object', name='LIGHTING_DESC')

In [45]:
def merger(f1,f2):
    f1 = pd.merge(f1,f2,on=['COUNTY'],how='left')
    return f1

In [46]:
colo_2019.shape

(108647, 35)

In [47]:
colo_2019= merger(colo_2019,lighting_percentages_df_2019)
colo_2020= merger(colo_2020,lighting_percentages_df_2020)
colo_2021= merger(colo_2021,lighting_percentages_df_2021)

In [48]:
colo_2019.shape

(108647, 40)

In [49]:
colo_2020.shape

(74059, 40)

In [50]:
colo_2021.shape

(34584, 40)

In [51]:
colo_2019['SURFACE'].unique()

array([ 9,  6,  1,  2, 10,  5], dtype=int64)

In [52]:
colo_2020['SURFACE'].unique()

array([ 1,  6,  9,  5,  2, 10], dtype=int64)

In [53]:
colo_2021['SURFACE'].unique()

array([ 1,  2,  6,  9,  0, 10,  5], dtype=int64)

In [54]:
surface_mapping={
    0:'UNKNOWN_SURF',
    1:'DRY',
    2:'WET',
    3:'STANDING_WATER',
    5:'SLUSH',
    6:'ICE',
    8:'OTHER_SURF',
    9:'SNOW_SURF',
    10:'DIRT'
    
}

def surface(df, mapping):
    df['SURF_DESC'] = df['SURFACE'].map(mapping)
    grouped_lighting = df.groupby(['COUNTY', 'SURF_DESC']).size().unstack(fill_value=0)
    grouped_lighting = df.groupby(['COUNTY', 'SURF_DESC']).size().unstack(fill_value=0)
    total_counts_by_county_lighting = grouped_lighting.sum(axis=1)
    surf_percentages_df = (grouped_lighting.div(total_counts_by_county_lighting, axis=0) * 100).fillna(0)
    surf_percentages_df = surf_percentages_df.reset_index()
    
    return surf_percentages_df

surf_percentages_df_2019 = surface(colo_2019, surface_mapping)
surf_percentages_df_2020 = surface(colo_2020, surface_mapping)
surf_percentages_df_2021 = surface(colo_2021, surface_mapping)


In [55]:
surf_percentages_df_2019.shape

(64, 7)

In [56]:
surf_percentages_df_2019.columns

Index(['COUNTY', 'DIRT', 'DRY', 'ICE', 'SLUSH', 'SNOW_SURF', 'WET'], dtype='object', name='SURF_DESC')

In [57]:
surf_percentages_df_2020.columns

Index(['COUNTY', 'DIRT', 'DRY', 'ICE', 'SLUSH', 'SNOW_SURF', 'WET'], dtype='object', name='SURF_DESC')

In [58]:
surf_percentages_df_2021.columns

Index(['COUNTY', 'DIRT', 'DRY', 'ICE', 'SLUSH', 'SNOW_SURF', 'UNKNOWN_SURF',
       'WET'],
      dtype='object', name='SURF_DESC')

In [59]:
surf_percentages_df_2019.insert(6,'UNKNOWN_SURF',0)

In [60]:
surf_percentages_df_2020.insert(6,'UNKNOWN_SURF',0)

In [61]:
def merger(f1,f2):
    f1 = pd.merge(f1,f2,on=['COUNTY'],how='left')
    return f1

In [62]:
colo_2019.shape

(108647, 41)

In [63]:
colo_2019 = merger(colo_2019,surf_percentages_df_2019)
colo_2020 = merger(colo_2020,surf_percentages_df_2020)
colo_2021 = merger(colo_2021,surf_percentages_df_2021)

In [64]:
colo_2019.shape

(108647, 48)

In [65]:
colo_2020.shape

(74059, 48)

In [66]:
colo_2021.shape

(34584, 48)

In [67]:
colo_2019['INTOXICATION'].unique()

array([4, 5, 1, 2, 3], dtype=int64)

In [68]:
colo_2020['INTOXICATION'].unique()

array([4, 1, 3, 5], dtype=int64)

In [69]:
colo_2021['INTOXICATION'].unique()

array([4, 1, 6], dtype=int64)

In [70]:
intoxication_mapping = {
    1: 'ALCOHOL',
    2: 'DRUG',
    3: 'ALCOHOL, DRUG',
    4: 'NO INTOXICATION',
    5: 'MEDICINAL',
    6: 'MARIJUANA'
}

In [71]:
def process_intoxication_data(df, mapping):
    # Map the intoxication codes to descriptive names
    df['INTOXICATION_DESC'] = df['INTOXICATION'].map(mapping).astype(str)
    
    # Group by COUNTY and INTOXICATION_DESC, then count occurrences
    grouped = df.groupby(['COUNTY', 'INTOXICATION_DESC']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)
    
    # Calculate percentages
    intoxication_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    intoxication_percentages_df = intoxication_percentages_df.reset_index()
    
    return intoxication_percentages_df

# Process each year's data
intoxication_df_2019 = process_intoxication_data(colo_2019, intoxication_mapping)
intoxication_df_2020 = process_intoxication_data(colo_2020, intoxication_mapping)
intoxication_df_2021 = process_intoxication_data(colo_2021, intoxication_mapping)



In [72]:
intoxication_df_2019.columns

Index(['COUNTY', 'ALCOHOL', 'ALCOHOL, DRUG', 'DRUG', 'MEDICINAL',
       'NO INTOXICATION'],
      dtype='object', name='INTOXICATION_DESC')

In [73]:
intoxication_df_2020.columns

Index(['COUNTY', 'ALCOHOL', 'ALCOHOL, DRUG', 'MEDICINAL', 'NO INTOXICATION'], dtype='object', name='INTOXICATION_DESC')

In [74]:
intoxication_df_2021.columns

Index(['COUNTY', 'ALCOHOL', 'MARIJUANA', 'NO INTOXICATION'], dtype='object', name='INTOXICATION_DESC')

In [75]:
intoxication_df_2020.insert(3,'DRUG',0)

In [76]:
intoxication_df_2021.insert(2,'ALCOHOL, DRUG',0)

In [77]:
intoxication_df_2021.insert(3,'DRUG',0)

In [78]:
intoxication_df_2021.insert(4,'MEDICINAL',0)

In [79]:
intoxication_df_2019.insert(5,'MARIJUANA',0)

In [80]:
intoxication_df_2020.insert(5,'MARIJUANA',0)

In [81]:
def meger(f1,f2):
    f1 = pd.merge(f1,f2,on=['COUNTY'],how='left')
    return f1

In [82]:
colo_2019 = meger(colo_2019,intoxication_df_2019)
colo_2020 = meger(colo_2020,intoxication_df_2020)
colo_2021 = meger(colo_2021,intoxication_df_2021)

In [83]:
colo_2019.columns

Index(['ROAD_CLASS', 'DATE', 'TIME', 'INTERSECTION', 'CONTOUR', 'SURFACE',
       'LIGHTING', 'WEATHER', 'HUMAN_FACTOR', 'INTOXICATION', 'AGE', 'GENDER',
       'COUNTY_FIPS', 'COUNTY', 'LATITUDE', 'LONGITUDE', 'YEAR',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'Crash_ID', 'BUFF_DIST', 'ORIG_FID',
       'Shape_Length', 'Shape_Area', 'WEATHER_DESC', 'BLOWING SAND/SNOW',
       'CLEAR', 'CLOUDY', 'FOG', 'OTHER_WEATHER', 'RAIN', 'SEVERE CROSSWINDS',
       'SLEET/HAIL', 'SNOW_WEATHER', 'LIGHTING_DESC', 'DARK-LIGHTED',
       'DARK-NOT LIGHTED', 'DAWN', 'DAYLIGHT', 'DUSK', 'SURF_DESC', 'DIRT',
       'DRY', 'ICE', 'SLUSH', 'SNOW_SURF', 'UNKNOWN_SURF', 'WET',
       'INTOXICATION_DESC', 'ALCOHOL', 'ALCOHOL, DRUG', 'DRUG', 'MEDICINAL',
       'MARIJUANA', 'NO INTOXICATION'],
      dtype='object')

In [84]:
colo_2019.shape,colo_2020.shape,colo_2021.shape

((108647, 55), (74059, 55), (34584, 55))

In [85]:
colo_2019['INTERSECTION'].unique()

array([0, 1], dtype=int64)

In [86]:
colo_2020['INTERSECTION'].unique()

array([0, 1], dtype=int64)

In [87]:
colo_2021['INTERSECTION'].unique()

array([0, 1], dtype=int64)

In [88]:
intersection_mapping ={
    0:'NO_INTERSECTION',
    1:'YES_INTERSECTION'
}


def intersect(df, mapping):
    df['INTERSECTION_DESC'] = df['INTERSECTION'].map(mapping)
    grouped_lighting = df.groupby(['COUNTY', 'INTERSECTION_DESC']).size().unstack(fill_value=0)
    grouped_lighting = df.groupby(['COUNTY', 'INTERSECTION_DESC']).size().unstack(fill_value=0)
    total_counts_by_county_lighting = grouped_lighting.sum(axis=1)
    intersection_percentages_df = (grouped_lighting.div(total_counts_by_county_lighting, axis=0) * 100).fillna(0)
    intersection_percentages_df = intersection_percentages_df.reset_index()
    
    return intersection_percentages_df

intersection_percentages_df_2019 = intersect(colo_2019, intersection_mapping)
intersection_percentages_df_2020 = intersect(colo_2020, intersection_mapping)
intersection_percentages_df_2021 = intersect(colo_2021, intersection_mapping)

In [89]:
intersection_percentages_df_2019.shape,intersection_percentages_df_2020.shape,intersection_percentages_df_2021.shape

((64, 3), (64, 3), (64, 3))

In [90]:
def merg(f1,f2):
    f1 = pd.merge(f1,f2,on=['COUNTY'],how='left')
    return f1

In [91]:
colo_2019 = merg(colo_2019,intersection_percentages_df_2019)
colo_2020 = merg(colo_2020,intersection_percentages_df_2020)
colo_2021 = merg(colo_2021,intersection_percentages_df_2021)

In [92]:
colo_2019.shape,colo_2020.shape,colo_2021.shape

((108647, 58), (74059, 58), (34584, 58))

In [93]:
colo_2019.columns

Index(['ROAD_CLASS', 'DATE', 'TIME', 'INTERSECTION', 'CONTOUR', 'SURFACE',
       'LIGHTING', 'WEATHER', 'HUMAN_FACTOR', 'INTOXICATION', 'AGE', 'GENDER',
       'COUNTY_FIPS', 'COUNTY', 'LATITUDE', 'LONGITUDE', 'YEAR',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'Crash_ID', 'BUFF_DIST', 'ORIG_FID',
       'Shape_Length', 'Shape_Area', 'WEATHER_DESC', 'BLOWING SAND/SNOW',
       'CLEAR', 'CLOUDY', 'FOG', 'OTHER_WEATHER', 'RAIN', 'SEVERE CROSSWINDS',
       'SLEET/HAIL', 'SNOW_WEATHER', 'LIGHTING_DESC', 'DARK-LIGHTED',
       'DARK-NOT LIGHTED', 'DAWN', 'DAYLIGHT', 'DUSK', 'SURF_DESC', 'DIRT',
       'DRY', 'ICE', 'SLUSH', 'SNOW_SURF', 'UNKNOWN_SURF', 'WET',
       'INTOXICATION_DESC', 'ALCOHOL', 'ALCOHOL, DRUG', 'DRUG', 'MEDICINAL',
       'MARIJUANA', 'NO INTOXICATION', 'INTERSECTION_DESC', 'NO_INTERSECTION',
       'YES_INTERSECTION'],
      dtype='object')

In [94]:
colo_2019['ROAD_CLASS'].unique()

array([1, 5, 2, 4, 7], dtype=int64)

In [95]:
colo_2020['ROAD_CLASS'].unique()

array([2, 5, 1, 4, 7], dtype=int64)

In [96]:
colo_2021['ROAD_CLASS'].unique()

array([2, 5, 7, 1, 4], dtype=int64)

In [97]:
roadway_types = {
    1:'INTERSTATE',
    2:'US & STATE HIGHWAY',
    4:'COUNTY ROAD',
    5:'CITY STREET',
    7:'OTHER ROADS'
}



def process_road_type_data(df, mapping):
    # Map the road type codes to descriptive names
    df['ROAD_TYPE_DESC'] = df['ROAD_CLASS'].map(mapping).astype(str)
    
    # Group by COUNTY and ROAD_TYPE_DESC, then count occurrences
    grouped_road_type = df.groupby(['COUNTY', 'ROAD_TYPE_DESC']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_road_type = grouped_road_type.sum(axis=1)
    
    # Calculate percentages
    road_type_percentages_df = (grouped_road_type.div(total_counts_by_county_road_type, axis=0) * 100).fillna(0)
    road_type_percentages_df = road_type_percentages_df.reset_index()
    
    return road_type_percentages_df

# Apply the function to each yearly DataFrame
road_type_percentages_df_2019 = process_road_type_data(colo_2019, roadway_types)
road_type_percentages_df_2020 = process_road_type_data(colo_2020, roadway_types)
road_type_percentages_df_2021 = process_road_type_data(colo_2021, roadway_types)

In [98]:
road_type_percentages_df_2019.shape,road_type_percentages_df_2020.shape,road_type_percentages_df_2021.shape

((64, 6), (64, 6), (64, 6))

In [99]:
def merger(f1,f2):
    f1 = pd.merge(f1,f2,on=['COUNTY'],how='left')
    return f1

In [100]:
colo_2019 = merger(colo_2019,road_type_percentages_df_2019)
colo_2020 = merger(colo_2020,road_type_percentages_df_2020)
colo_2021 = merger(colo_2021,road_type_percentages_df_2021)

In [101]:
colo_2019.shape, colo_2020.shape, colo_2021.shape

((108647, 64), (74059, 64), (34584, 64))

In [102]:
colo_2019['CONTOUR'].unique()

array(['STRAIGHT ON-GRADE', 'STRAIGHT ON-LEVEL', 'CURVE ON-GRADE',
       'CURVE ON-LEVEL', 'HILLCREST'], dtype=object)

In [103]:
colo_2020['CONTOUR'].unique()

array(['STRAIGHT ON-LEVEL', 'CURVE ON-LEVEL', 'STRAIGHT ON-GRADE',
       'CURVE ON-GRADE', 'HILLCREST'], dtype=object)

In [104]:
colo_2021['CONTOUR'].unique()

array(['StraightLevel', 'StraightDownhill', 'StraightUphill',
       'Curve LeftLevel', 'Curve LeftUphill', 'Curve LeftDownhill',
       'Curve RightUphill', 'Curve RightLevel', 'Curve RightDownhill',
       'StraightUnknown', 'StraightHill Crest', 'UnknownLevel',
       'Curve RightUnknown', 'Curve RightSag/Bottom',
       'Curve LeftHill Crest', 'StraightSag/Bottom', 'UnknownUnknown',
       'UnknownDownhill', 'Curve LeftSag/Bottom', 'Curve RightHill Crest',
       'Curve LeftUnknown', 'UnknownUphill', 'UnknownHill Crest'],
      dtype=object)

In [105]:
colo_2019['HUMAN_FACTOR'].unique()

array([ 5., 11.,  7., 10.,  2.])

In [106]:
colo_2020['HUMAN_FACTOR'].unique()

array([10., 12.,  5.,  7.,  2., 11.])

In [107]:
colo_2021['HUMAN_FACTOR'].unique()

array([10.,  2.,  3.,  4.,  6.,  5.,  1., 11.,  8., 12.,  9.])

In [108]:
human_encoding = {
    1:'SPEEDING',
    2:'INATTENTION',
    3:'LANE_CHNG',
    4:'TAILGATING',
    5:'VIOLATION',
    6:'UNSAFE_BACKING',
    7:'IMPAIRMENT',
    8:'TURNING',
    9:'TECH_PARK',
    10:'NO_FAULT',
    11:'KNOWN_HUMAN_FACTOR',
    12:'UNKNOWN_HUMAN_FACTOR'
}


def human(df, mapping):
    # Map the road type codes to descriptive names
    df['HUMAN_FACTOR_DESC'] = df['HUMAN_FACTOR'].map(mapping).astype(str)
    
    # Group by COUNTY and ROAD_TYPE_DESC, then count occurrences
    grouped_road_type = df.groupby(['COUNTY', 'HUMAN_FACTOR_DESC']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_road_type = grouped_road_type.sum(axis=1)
    
    # Calculate percentages
    human_percentages_df = (grouped_road_type.div(total_counts_by_county_road_type, axis=0) * 100).fillna(0)
    human_percentages_df = human_percentages_df.reset_index()
    
    return human_percentages_df

# Apply the function to each yearly DataFrame
human_percentages_df_2019 = human(colo_2019, human_encoding)
human_percentages_df_2020 = human(colo_2020, human_encoding)
human_percentages_df_2021 = human(colo_2021, human_encoding)


In [109]:
human_percentages_df_2019.shape

(64, 6)

In [110]:
human_percentages_df_2020.shape

(64, 7)

In [111]:
human_percentages_df_2021.shape

(64, 12)

In [112]:
human_percentages_df_2019.columns

Index(['COUNTY', 'IMPAIRMENT', 'INATTENTION', 'KNOWN_HUMAN_FACTOR', 'NO_FAULT',
       'VIOLATION'],
      dtype='object', name='HUMAN_FACTOR_DESC')

In [113]:
human_percentages_df_2020.columns

Index(['COUNTY', 'IMPAIRMENT', 'INATTENTION', 'KNOWN_HUMAN_FACTOR', 'NO_FAULT',
       'UNKNOWN_HUMAN_FACTOR', 'VIOLATION'],
      dtype='object', name='HUMAN_FACTOR_DESC')

In [114]:
human_percentages_df_2021.columns

Index(['COUNTY', 'INATTENTION', 'KNOWN_HUMAN_FACTOR', 'LANE_CHNG', 'NO_FAULT',
       'SPEEDING', 'TAILGATING', 'TECH_PARK', 'TURNING',
       'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION'],
      dtype='object', name='HUMAN_FACTOR_DESC')

In [115]:
human_percentages_df_2021.insert(1,'IMPAIRMENT',0)

In [116]:
human_percentages_df_2019.insert(4,'LANE_CHNG',0)

In [117]:
human_percentages_df_2019.insert(6,'SPEEDING',0)

In [118]:
human_percentages_df_2019.insert(7,'TAILGATING',0)

In [119]:
human_percentages_df_2019.insert(8,'TECH_PARK',0)

In [120]:
human_percentages_df_2019.insert(9,'TURNING',0)

In [121]:
human_percentages_df_2019.insert(10,'UNKNOWN_HUMAN_FACTOR',0)

In [122]:
human_percentages_df_2019.insert(11,'UNSAFE_BACKING',0)

In [123]:
human_percentages_df_2020.insert(4,'LANE_CHNG',0)

In [124]:
human_percentages_df_2020.insert(6,'SPEEDING',0)

In [125]:
human_percentages_df_2020.insert(7,'TAILGATING',0)

In [126]:
human_percentages_df_2020.insert(8,'TECH_PARK',0)

In [127]:
human_percentages_df_2020.insert(9,'TURNING',0)

In [128]:
human_percentages_df_2020.insert(11,'UNSAFE_BACKING',0)

In [129]:
human_percentages_df_2019.shape, human_percentages_df_2020.shape, human_percentages_df_2020.shape

((64, 13), (64, 13), (64, 13))

In [130]:
def merger(f1,f2):
    f1 = pd.merge(f1,f2,on=['COUNTY'],how='left')
    return f1

In [131]:
colo_2019 = merger(colo_2019,human_percentages_df_2019)
colo_2020 = merger(colo_2020,human_percentages_df_2020)
colo_2021 = merger(colo_2021, human_percentages_df_2021)

In [132]:
colo_2019.shape, colo_2020.shape, colo_2021.shape

((108647, 77), (74059, 77), (34584, 77))

In [133]:
age_bands = ['AGE 1-21', 'AGE 22-30', 'AGE 31-65', 'AGE 66 and above', 'Unknown Age']

# Use pd.cut() to bin the ages into the age bands
colo_2019['AGE_BAND'] = pd.cut(colo_2019['AGE'], bins=[0, 21, 30, 65, 100, np.inf], labels=age_bands, right=False)

In [134]:
age_bands = ['AGE 1-21', 'AGE 22-30', 'AGE 31-65', 'AGE 66 and above', 'Unknown Age']

# Use pd.cut() to bin the ages into the age bands
colo_2020['AGE_BAND'] = pd.cut(colo_2020['AGE'], bins=[0, 21, 30, 65, 100, np.inf], labels=age_bands, right=False)

In [135]:
age_bands = ['AGE 1-21', 'AGE 22-30', 'AGE 31-65', 'AGE 66 and above', 'Unknown Age']

# Use pd.cut() to bin the ages into the age bands
colo_2021['AGE_BAND'] = pd.cut(colo_2021['AGE'], bins=[0, 21, 30, 65, 100, np.inf], labels=age_bands, right=False)

In [136]:
def age(df):
    
    # Group by COUNTY and ROAD_TYPE_DESC, then count occurrences
    grouped_road_type = df.groupby(['COUNTY', 'AGE_BAND']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_road_type = grouped_road_type.sum(axis=1)
    
    # Calculate percentages
    age_percentages_df = (grouped_road_type.div(total_counts_by_county_road_type, axis=0) * 100).fillna(0)
    age_percentages_df = age_percentages_df.reset_index()
    
    return age_percentages_df

# Apply the function to each yearly DataFrame
age_percentages_df_2019 = age(colo_2019)
age_percentages_df_2020 = age(colo_2020)
age_percentages_df_2021 = age(colo_2021)

In [137]:
age_percentages_df_2019

AGE_BAND      COUNTY   AGE 1-21  AGE 22-30  AGE 31-65  AGE 66 and above  \
0              ADAMS  26.738010  23.725723  43.265953          6.270313   
1            ALAMOSA  22.026432  19.383260  44.493392         14.096916   
2           ARAPAHOE  24.376989  23.049453  44.771369          7.802189   
3          ARCHULETA  12.994350  21.468927  51.977401         13.559322   
4               BACA  13.636364  18.181818  52.272727         15.909091   
..               ...        ...        ...        ...               ...   
59            SUMMIT  13.913043  30.326087  48.478261          7.282609   
60            TELLER  11.203320  15.352697  56.016598         17.427386   
61        WASHINGTON  12.500000  18.055556  48.611111         20.833333   
62              WELD  26.519514  23.704415  43.314139          6.461932   
63              YUMA  12.121212  27.272727  50.000000         10.606061   

AGE_BAND  Unknown Age  
0                 0.0  
1                 0.0  
2                 0.0  
3                 0.0  
4                 0.0  
..                ...  
59                0.0  
60                0.0  
61                0.0  
62                0.0  
63                0.0  

[64 rows x 6 columns]

In [138]:
age_percentages_df_2020

AGE_BAND      COUNTY   AGE 1-21  AGE 22-30  AGE 31-65  AGE 66 and above  \
0              ADAMS  30.111565  23.450790  41.157627          5.280018   
1            ALAMOSA  15.428571  17.142857  55.428571         12.000000   
2           ARAPAHOE  27.816144  23.446168  41.016642          7.721046   
3          ARCHULETA  13.736264  21.978022  47.252747         17.032967   
4               BACA   3.448276  27.586207  62.068966          6.896552   
..               ...        ...        ...        ...               ...   
59            SUMMIT  18.240000  27.360000  47.520000          6.880000   
60            TELLER   9.375000  18.750000  57.812500         14.062500   
61        WASHINGTON  20.000000  16.923077  58.461538          4.615385   
62              WELD  27.516030  24.003345  41.817675          6.662950   
63              YUMA  25.000000  20.833333  39.583333         14.583333   

AGE_BAND  Unknown Age  
0                 0.0  
1                 0.0  
2                 0.0  
3                 0.0  
4                 0.0  
..                ...  
59                0.0  
60                0.0  
61                0.0  
62                0.0  
63                0.0  

[64 rows x 6 columns]

In [139]:
age_percentages_df_2021

AGE_BAND      COUNTY   AGE 1-21  AGE 22-30  AGE 31-65  AGE 66 and above  \
0              ADAMS  33.296631  21.779344  39.903105          5.020921   
1            ALAMOSA  20.710059  21.893491  43.195266         14.201183   
2           ARAPAHOE  28.668639  23.431953  40.236686          7.662722   
3          ARCHULETA  22.748815  18.957346  44.549763         13.744076   
4               BACA  15.151515  24.242424  45.454545         15.151515   
..               ...        ...        ...        ...               ...   
59            SUMMIT  15.046296  24.305556  50.925926          9.722222   
60            TELLER  18.834081  18.834081  47.085202         15.246637   
61        WASHINGTON  13.207547  18.867925  58.490566          9.433962   
62              WELD  26.791569  23.981265  41.030445          8.196721   
63              YUMA  24.000000  10.000000  56.000000         10.000000   

AGE_BAND  Unknown Age  
0                 0.0  
1                 0.0  
2                 0.0  
3                 0.0  
4                 0.0  
..                ...  
59                0.0  
60                0.0  
61                0.0  
62                0.0  
63                0.0  

[64 rows x 6 columns]

In [140]:
def merger(f1,f2):
    f1 = pd.merge(f1,f2,on=['COUNTY'],how='left')
    return f1

In [141]:
colo_2019 = merger(colo_2019,age_percentages_df_2019)
colo_2020 = merger(colo_2020,age_percentages_df_2020)
colo_2021 = merger(colo_2021,age_percentages_df_2021)

In [142]:
colo_2019.shape, colo_2020.shape, colo_2021.shape

((108647, 83), (74059, 83), (34584, 83))

In [143]:
colo_2019['GENDER'].unique(), colo_2020['GENDER'].unique(), colo_2021['GENDER'].unique()

(array(['M', 'F', 'U'], dtype=object),
 array(['F', 'U', 'M'], dtype=object),
 array(['F', 'M', 'U'], dtype=object))

In [144]:
gender_mapping = {
    'M': 'MALE',
    'F': 'FEMALE',
    'U': 'UNKNOWN_GENDER'
}



def process_gender_data(df, mapping):
    # Map the gender codes to descriptive names
    df['GENDER_DESC'] = df['GENDER'].map(mapping).astype(str)
    
    # Group by COUNTY and GENDER_DESC, then count occurrences
    grouped = df.groupby(['COUNTY', 'GENDER_DESC']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)
    
    # Calculate percentages
    gender_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    gender_percentages_df = gender_percentages_df.reset_index()
    
    return gender_percentages_df

# Process each year's data
gender_df_2019 = process_gender_data(colo_2019, gender_mapping)
gender_df_2020 = process_gender_data(colo_2020, gender_mapping)
gender_df_2021 = process_gender_data(colo_2021, gender_mapping)


In [145]:
gender_df_2019

GENDER_DESC      COUNTY     FEMALE       MALE  UNKNOWN_GENDER
0                 ADAMS  32.493064  55.085216       12.421720
1               ALAMOSA  39.207048  54.625551        6.167401
2              ARAPAHOE  36.293766  53.148048       10.558186
3             ARCHULETA  39.548023  58.757062        1.694915
4                  BACA  22.727273  77.272727        0.000000
..                  ...        ...        ...             ...
59               SUMMIT  29.565217  65.217391        5.217391
60               TELLER  36.929461  59.751037        3.319502
61           WASHINGTON  30.555556  63.888889        5.555556
62                 WELD  32.613564  57.053743       10.332694
63                 YUMA  28.787879  66.666667        4.545455

[64 rows x 4 columns]

In [146]:
gender_df_2020

GENDER_DESC      COUNTY     FEMALE       MALE  UNKNOWN_GENDER
0                 ADAMS  29.901690  53.761184       16.337126
1               ALAMOSA  37.714286  57.142857        5.142857
2              ARAPAHOE  32.797464  53.583154       13.619382
3             ARCHULETA  37.912088  59.340659        2.747253
4                  BACA  27.586207  70.689655        1.724138
..                  ...        ...        ...             ...
59               SUMMIT  23.840000  68.960000        7.200000
60               TELLER  21.093750  75.000000        3.906250
61           WASHINGTON  35.384615  61.538462        3.076923
62                 WELD  30.303875  57.959297       11.736827
63                 YUMA  37.500000  58.333333        4.166667

[64 rows x 4 columns]

In [147]:
gender_df_2021

GENDER_DESC      COUNTY     FEMALE       MALE  UNKNOWN_GENDER
0                 ADAMS  34.485796  60.867650        4.646554
1               ALAMOSA  46.745562  52.071006        1.183432
2              ARAPAHOE  37.662722  59.733728        2.603550
3             ARCHULETA  35.071090  62.559242        2.369668
4                  BACA  15.151515  81.818182        3.030303
..                  ...        ...        ...             ...
59               SUMMIT  24.074074  74.305556        1.620370
60               TELLER  34.529148  63.228700        2.242152
61           WASHINGTON  33.962264  66.037736        0.000000
62                 WELD  34.051522  63.981265        1.967213
63                 YUMA  30.000000  64.000000        6.000000

[64 rows x 4 columns]

In [148]:
def merger(f1,f2):
    f1 = pd.merge(f1,f2,on=['COUNTY'],how='left')
    return f1

In [149]:
colo_2019 = merger(colo_2019,gender_df_2019)
colo_2020 = merger(colo_2020,gender_df_2020)
colo_2021 = merger(colo_2021,gender_df_2021)

In [150]:
colo_2019.shape, colo_2020.shape, colo_2021.shape

((108647, 87), (74059, 87), (34584, 87))

In [151]:
colo_2019['INJURY_COUNT_SUM'] = colo_2019.groupby(['COUNTY'])['INJURY_COUNT'].transform('sum')
colo_2020['INJURY_COUNT_SUM'] = colo_2020.groupby(['COUNTY'])['INJURY_COUNT'].transform('sum')
colo_2021['INJURY_COUNT_SUM'] = colo_2021.groupby(['COUNTY'])['INJURY_COUNT'].transform('sum')

In [152]:
colo_2019['INJURY_OUTCOME'].unique()

array([0, 1], dtype=int64)

In [153]:
colo_2020['INJURY_OUTCOME'].unique()

array([1, 0], dtype=int64)

In [154]:
colo_2021['INJURY_OUTCOME'].unique()

array([0, 1], dtype=int64)

In [155]:
map = {
    0:'NO INJURY_OUTCOME',
    1:'YES INJURY_OUTCOME'
}

def injury(df,map):
    df['INJURY_DESC'] = df['INJURY_OUTCOME'].map(map).astype('str')
    grouped = df.groupby(['COUNTY','INJURY_DESC']).size().unstack(fill_value=0)
    total_counts_by_county = grouped.sum(axis=1)
    injury_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    injury_percentages_df = injury_percentages_df.reset_index()
    return injury_percentages_df

injury_percentages_df_2019 = injury(colo_2019, map)
injury_percentages_df_2020 = injury(colo_2020, map)
injury_percentages_df_2021 = injury(colo_2021, map)

In [156]:
injury_percentages_df_2019.shape

(64, 3)

In [157]:
def merger(f1,f2):
    f1 = pd.merge(f1,f2, on=['COUNTY'],how='left')
    return f1

In [158]:
colo_2019 = merger(colo_2019,injury_percentages_df_2019)
colo_2020 = merger(colo_2020,injury_percentages_df_2020)
colo_2021 = merger(colo_2021,injury_percentages_df_2021)

In [159]:
colo_2019.shape, colo_2020.shape, colo_2021.shape

((108647, 91), (74059, 91), (34584, 91))

In [161]:
colo_2019.columns

Index(['ROAD_CLASS', 'DATE', 'TIME', 'INTERSECTION', 'CONTOUR', 'SURFACE',
       'LIGHTING', 'WEATHER', 'HUMAN_FACTOR', 'INTOXICATION', 'AGE', 'GENDER',
       'COUNTY_FIPS', 'COUNTY', 'LATITUDE', 'LONGITUDE', 'YEAR',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'Crash_ID', 'BUFF_DIST', 'ORIG_FID',
       'Shape_Length', 'Shape_Area', 'WEATHER_DESC', 'BLOWING SAND/SNOW',
       'CLEAR', 'CLOUDY', 'FOG', 'OTHER_WEATHER', 'RAIN', 'SEVERE CROSSWINDS',
       'SLEET/HAIL', 'SNOW_WEATHER', 'LIGHTING_DESC', 'DARK-LIGHTED',
       'DARK-NOT LIGHTED', 'DAWN', 'DAYLIGHT', 'DUSK', 'SURF_DESC', 'DIRT',
       'DRY', 'ICE', 'SLUSH', 'SNOW_SURF', 'UNKNOWN_SURF', 'WET',
       'INTOXICATION_DESC', 'ALCOHOL', 'ALCOHOL, DRUG', 'DRUG', 'MEDICINAL',
       'MARIJUANA', 'NO INTOXICATION', 'INTERSECTION_DESC', 'NO_INTERSECTION',
       'YES_INTERSECTION', 'ROAD_TYPE_DESC', 'CITY STREET', 'COUNTY ROAD',
       'INTERSTATE', 'OTHER ROADS', 'US & STATE HIGHWAY', 'HUMAN_FACTOR_DESC',
       'IMPAIRMENT', 'INATTE

In [162]:
p = pd.concat([colo_2019,colo_2020,colo_2021],axis=0)

In [163]:
p

ROAD_CLASS        DATE      TIME  INTERSECTION              CONTOUR  \
0               1    1/1/2019        10             0    STRAIGHT ON-GRADE   
1               5    1/1/2019        17             0    STRAIGHT ON-LEVEL   
2               5    1/1/2019        21             1    STRAIGHT ON-GRADE   
3               5    1/1/2019        24             1    STRAIGHT ON-LEVEL   
4               2    1/1/2019        41             0    STRAIGHT ON-GRADE   
...           ...         ...       ...           ...                  ...   
34579           2  12/31/2021  23:22:00             1        StraightLevel   
34580           4  12/31/2021  23:23:00             0      Curve LeftLevel   
34581           1  12/31/2021  23:39:00             0  Curve RightDownhill   
34582           2  12/31/2021  23:41:00             1        StraightLevel   
34583           2  12/31/2021  23:43:00             0       StraightUphill   

       SURFACE  LIGHTING  WEATHER  HUMAN_FACTOR  INTOXICATION  ...  \
0            9         4        4           5.0             4  ...   
1            6         4        4          11.0             5  ...   
2            9         4        8           7.0             1  ...   
3            6         4        4          10.0             4  ...   
4            9         4        4           2.0             4  ...   
...        ...       ...      ...           ...           ...  ...   
34579        6         4        4           2.0             4  ...   
34580        6         3        4           1.0             4  ...   
34581        0         3        4           1.0             4  ...   
34582        9         4        4          10.0             4  ...   
34583        6         4        4           1.0             4  ...   

       AGE 66 and above Unknown Age     GENDER_DESC     FEMALE       MALE  \
0              6.270313         0.0            MALE  32.493064  55.085216   
1             10.948403         0.0            MALE  36.039312  53.484029   
2              6.270313         0.0            MALE  32.493064  55.085216   
3              6.499569         0.0            MALE  32.008340  51.180710   
4              6.270313         0.0            MALE  32.493064  55.085216   
...                 ...         ...             ...        ...        ...   
34579         10.275545         0.0            MALE  38.633754  59.701493   
34580          9.722222         0.0            MALE  24.074074  74.305556   
34581         10.533553         0.0            MALE  38.778878  59.543454   
34582          8.196721         0.0  UNKNOWN_GENDER  34.051522  63.981265   
34583          5.020921         0.0            MALE  34.485796  60.867650   

       UNKNOWN_GENDER  INJURY_COUNT_SUM         INJURY_DESC  \
0           12.421720              4307   NO INJURY_OUTCOME   
1           10.476658              3213  YES INJURY_OUTCOME   
2           12.421720              4307  YES INJURY_OUTCOME   
3           16.810950              6233   NO INJURY_OUTCOME   
4           12.421720              4307   NO INJURY_OUTCOME   
...               ...               ...                 ...   
34579        1.664753               797   NO INJURY_OUTCOME   
34580        1.620370               155   NO INJURY_OUTCOME   
34581        1.677668              1356  YES INJURY_OUTCOME   
34582        1.967213               908   NO INJURY_OUTCOME   
34583        4.646554              1761   NO INJURY_OUTCOME   

       NO INJURY_OUTCOME  YES INJURY_OUTCOME  
0              75.219976           24.780024  
1              76.471744           23.528256  
2              75.219976           24.780024  
3              78.819743           21.180257  
4              75.219976           24.780024  
...                  ...                 ...  
34579          66.073479           33.926521  
34580          74.305556           25.694444  
34581          71.644664           28.355336  
34582          71.100703           28.899297  
34583          71.570139      

In [165]:
p['YEAR_CAT'] = np.where(p['YEAR']==2019,1,
                                         np.where(p['YEAR']==2020,2,
                                                 np.where(p['YEAR']==2021,3,np.nan)))

In [166]:
p

ROAD_CLASS        DATE      TIME  INTERSECTION              CONTOUR  \
0               1    1/1/2019        10             0    STRAIGHT ON-GRADE   
1               5    1/1/2019        17             0    STRAIGHT ON-LEVEL   
2               5    1/1/2019        21             1    STRAIGHT ON-GRADE   
3               5    1/1/2019        24             1    STRAIGHT ON-LEVEL   
4               2    1/1/2019        41             0    STRAIGHT ON-GRADE   
...           ...         ...       ...           ...                  ...   
34579           2  12/31/2021  23:22:00             1        StraightLevel   
34580           4  12/31/2021  23:23:00             0      Curve LeftLevel   
34581           1  12/31/2021  23:39:00             0  Curve RightDownhill   
34582           2  12/31/2021  23:41:00             1        StraightLevel   
34583           2  12/31/2021  23:43:00             0       StraightUphill   

       SURFACE  LIGHTING  WEATHER  HUMAN_FACTOR  INTOXICATION  ...  \
0            9         4        4           5.0             4  ...   
1            6         4        4          11.0             5  ...   
2            9         4        8           7.0             1  ...   
3            6         4        4          10.0             4  ...   
4            9         4        4           2.0             4  ...   
...        ...       ...      ...           ...           ...  ...   
34579        6         4        4           2.0             4  ...   
34580        6         3        4           1.0             4  ...   
34581        0         3        4           1.0             4  ...   
34582        9         4        4          10.0             4  ...   
34583        6         4        4           1.0             4  ...   

       Unknown Age     GENDER_DESC     FEMALE       MALE  UNKNOWN_GENDER  \
0              0.0            MALE  32.493064  55.085216       12.421720   
1              0.0            MALE  36.039312  53.484029       10.476658   
2              0.0            MALE  32.493064  55.085216       12.421720   
3              0.0            MALE  32.008340  51.180710       16.810950   
4              0.0            MALE  32.493064  55.085216       12.421720   
...            ...             ...        ...        ...             ...   
34579          0.0            MALE  38.633754  59.701493        1.664753   
34580          0.0            MALE  24.074074  74.305556        1.620370   
34581          0.0            MALE  38.778878  59.543454        1.677668   
34582          0.0  UNKNOWN_GENDER  34.051522  63.981265        1.967213   
34583          0.0            MALE  34.485796  60.867650        4.646554   

       INJURY_COUNT_SUM         INJURY_DESC  NO INJURY_OUTCOME  \
0                  4307   NO INJURY_OUTCOME          75.219976   
1                  3213  YES INJURY_OUTCOME          76.471744   
2                  4307  YES INJURY_OUTCOME          75.219976   
3                  6233   NO INJURY_OUTCOME          78.819743   
4                  4307   NO INJURY_OUTCOME          75.219976   
...                 ...                 ...                ...   
34579               797   NO INJURY_OUTCOME          66.073479   
34580               155   NO INJURY_OUTCOME          74.305556   
34581              1356  YES INJURY_OUTCOME          71.644664   
34582               908   NO INJURY_OUTCOME          71.100703   
34583              1761   NO INJURY_OUTCOME          71.570139   

       YES INJURY_OUTCOME  YEAR_CAT  
0               24.780024       1.0  
1               23.528256       1.0  
2               24.780024       1.0  
3               21.180257       1.0  
4               24.780024       1.0  
...                   ...       ...  
34579           33.926521       3.0  
34580           25.694444       3.0  
34581           28.355336       3.0  
34582           28.899297       3.0  
34583           28.429861       3.0  

[217290 rows x 92 columns]

In [167]:
colorado_19_20_21 = pd.get_dummies(p,columns=['YEAR'])

In [168]:
colorado_19_20_21

ROAD_CLASS        DATE      TIME  INTERSECTION              CONTOUR  \
0               1    1/1/2019        10             0    STRAIGHT ON-GRADE   
1               5    1/1/2019        17             0    STRAIGHT ON-LEVEL   
2               5    1/1/2019        21             1    STRAIGHT ON-GRADE   
3               5    1/1/2019        24             1    STRAIGHT ON-LEVEL   
4               2    1/1/2019        41             0    STRAIGHT ON-GRADE   
...           ...         ...       ...           ...                  ...   
34579           2  12/31/2021  23:22:00             1        StraightLevel   
34580           4  12/31/2021  23:23:00             0      Curve LeftLevel   
34581           1  12/31/2021  23:39:00             0  Curve RightDownhill   
34582           2  12/31/2021  23:41:00             1        StraightLevel   
34583           2  12/31/2021  23:43:00             0       StraightUphill   

       SURFACE  LIGHTING  WEATHER  HUMAN_FACTOR  INTOXICATION  ...       MALE  \
0            9         4        4           5.0             4  ...  55.085216   
1            6         4        4          11.0             5  ...  53.484029   
2            9         4        8           7.0             1  ...  55.085216   
3            6         4        4          10.0             4  ...  51.180710   
4            9         4        4           2.0             4  ...  55.085216   
...        ...       ...      ...           ...           ...  ...        ...   
34579        6         4        4           2.0             4  ...  59.701493   
34580        6         3        4           1.0             4  ...  74.305556   
34581        0         3        4           1.0             4  ...  59.543454   
34582        9         4        4          10.0             4  ...  63.981265   
34583        6         4        4           1.0             4  ...  60.867650   

      UNKNOWN_GENDER  INJURY_COUNT_SUM         INJURY_DESC  NO INJURY_OUTCOME  \
0          12.421720              4307   NO INJURY_OUTCOME          75.219976   
1          10.476658              3213  YES INJURY_OUTCOME          76.471744   
2          12.421720              4307  YES INJURY_OUTCOME          75.219976   
3          16.810950              6233   NO INJURY_OUTCOME          78.819743   
4          12.421720              4307   NO INJURY_OUTCOME          75.219976   
...              ...               ...                 ...                ...   
34579       1.664753               797   NO INJURY_OUTCOME          66.073479   
34580       1.620370               155   NO INJURY_OUTCOME          74.305556   
34581       1.677668              1356  YES INJURY_OUTCOME          71.644664   
34582       1.967213               908   NO INJURY_OUTCOME          71.100703   
34583       4.646554              1761   NO INJURY_OUTCOME          71.570139   

       YES INJURY_OUTCOME  YEAR_CAT  YEAR_2019  YEAR_2020  YEAR_2021  
0               24.780024       1.0          1          0          0  
1               23.528256       1.0          1          0          0  
2               24.780024       1.0          1          0          0  
3               21.180257       1.0          1          0          0  
4               24.780024       1.0          1          0          0  
...                   ...       ...        ...        ...        ...  
34579           33.926521       3.0          0          0          1  
34580           25.694444       3.0          0          0          1  
34581           28.355336       3.0          0          0          1  
34582           28.899297       3.0          0          0          1  
34583           28.429861       3.0          0          0          1  

[217290 rows x 94 columns]

In [169]:
colorado_19_20_21.to_csv('colorado_final_merged.csv',index= False)