In [1]:
import numpy as np
import pandas as pd

In [2]:
texas = pd.read_csv('C:/Users/karan/texas.csv')

In [3]:
texas.columns

Index(['GISJOIN', 'COUNT', 'ALCOHOL', 'DRUG', 'ALCOHOL, DRUG',
       'NO INTOXICATION', 'MEDICINAL', 'MARIJUANA', 'UNK', 'White', 'Hispanic',
       'Black', 'Asian', 'Other', 'American Native', 'NO_Damage', 'YES_Damage',
       'NO_Intersection', 'YES_Intersection', 'BLOWING SAND/SNOW', 'CLEAR',
       'CLOUDY', 'FOG', 'OTHER', 'RAIN', 'SEVERE CROSSWINDS', 'SLEET/HAIL',
       'SNOW_Weather', 'UNK_Weather', 'DAYLIGHT', 'DARK-LIGHTED',
       'DARK-NOT LIGHTED', 'DARK-UNKNOWN LIGHTING', 'DUSK', 'DAWN',
       'UNK_LIGHT', 'OTHER_LIGHT', 'CITY STREET', 'COUNTY ROAD',
       'FARM TO MARKET', 'INTERSTATE', 'OTHER ROADS', 'TOLL BRIDGES',
       'TOLLWAY', 'US & STATE HIGHWAY', 'DRY', 'ICE', 'OTHER_SURF',
       'SAND,MUD,DIRT', 'SLUSH', 'SNOW_SURF', 'STANDING WATER', 'UNKNOWN_SURF',
       'WET', 'SPEEDING', 'INATTENTION', 'LANE_CHANGE', 'TAILGATING',
       'VIOLATION', 'UNSAFE_BACKING', 'IMPAIRMENT', 'TURNING', 'TECH_PARK',
       'NO_FAULT', 'KNOWN_HUMAN_FACTOR', 'UNKNOWN_HUMAN_FACTOR

In [4]:
okla = pd.read_csv('C:/Users/karan/OKLA_27697 1.csv')

In [5]:
okla[okla['YEAR'] == 2020]['SPEEDING'].unique()

array([0], dtype=int64)

In [6]:
okla.drop(columns={'DATE'},inplace= True)

In [7]:
okla.columns

Index(['Crash_ID', 'County_FIP', 'COUNTY', 'CITY', 'TIME', 'LIGHTING_CAT',
       'WEATHER_CAT', 'YEAR', 'ROAD_CLASS', 'INTOXICATION', 'LATITUDE',
       'LONGITUDE', 'INATTENTION', 'SPEEDING', 'TEEN_DRIVE', 'OLDER_DRIV',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'BUFF_DIST', 'GISJOIN', 'COUNTYFP',
       'Shape_Leng', 'GISJOIN.1', 'COUNTY.1', 'POP_AMPVE001'],
      dtype='object')

In [8]:
okla.rename(columns={'POP_AMPVE001':'POPN'},inplace= True)

In [9]:
o_19 = okla[okla['YEAR']==2019]
o_20 = okla[okla['YEAR']==2020]
o_21= okla[okla['YEAR']==2021]

In [10]:
o_21

Crash_ID  County_FIP     COUNTY           CITY  TIME  LIGHTING_CAT  \
12873  211202855       40027  Cleveland          NOBLE   0.0             1   
12874  211202858       40037      Creek        BRISTOW   0.0             1   
12875  211202863       40017   Canadian        MUSTANG   0.0             1   
12876  211230295       40143      Tulsa   BROKEN ARROW   0.0             1   
12877  211230321       40143      Tulsa   BROKEN ARROW   0.0             1   
...          ...         ...        ...            ...   ...           ...   
27692  300532018       40109   Oklahoma  OKLAHOMA CITY   0.0             1   
27693  300534146       40109   Oklahoma  OKLAHOMA CITY   0.0             1   
27694  300528197       40109   Oklahoma  OKLAHOMA CITY   0.0             1   
27695  300539748       40109   Oklahoma  OKLAHOMA CITY   0.0             1   
27696  300536486       40109   Oklahoma  OKLAHOMA CITY   0.0             3   

       WEATHER_CAT  YEAR  ROAD_CLASS  INTOXICATION  ...  OLDER_DRIV  \
12873           11  2021           7             4  ...           1   
12874            2  2021           7             4  ...           0   
12875           12  2021           7             4  ...           1   
12876           11  2021           7             4  ...           0   
12877           12  2021           7             4  ...           0   
...            ...   ...         ...           ...  ...         ...   
27692           11  2021           7             4  ...           0   
27693           11  2021           7             4  ...           0   
27694           11  2021           7             4  ...           1   
27695           11  2021           7             4  ...           1   
27696           11  2021           7             4  ...           1   

       INJURY_COUNT  INJURY_OUTCOME  BUFF_DIST          GISJOIN  COUNTYFP  \
12873             1               1       0.25  G40004906819002        49   
12874             1               1       0.25  G40002903882001        29   
12875             1               1       0.25  G40013700009021       137   
12876             2               1       0.25  G40012104868001       121   
12877             1               1       0.25  G40012104868001       121   
...             ...             ...        ...              ...       ...   
27692             1               1       0.25  G40004906819002        49   
27693             1               1       0.25  G40004906819002        49   
27694             1               1       0.25  G40004906819002        49   
27695             0               0       0.25  G40004906819002        49   
27696             1               1       0.25  G40004906819002        49   

         Shape_Leng        GISJOIN.1          COUNTY.1  POPN  
12873   98862.92586  G40004906819002     Garvin County  1122  
12874  104926.65410  G40002903882001       Coal County  1059  
12875   97242.43652  G40013700009021   Stephens County  1355  
12876   83370.68390  G40012104868001  Pittsburg County   664  
12877   83370.68390  G40012104868001  Pittsburg County   664  
...             ...              ...               ...   ...  
27692   98862.92586  G40004906819002     Garvin County  1122  
27693   98862.92586  G40004906819002     Garvin County  1122  
27694   98862.92586  G40004906819002     Garvin County  1122  
27695   98862.92586  G40004906819002     Garvin County  1122  
27696   98862.92586  G40004906819002     Garvin County  1122  

[9309 rows x 25 columns]

In [11]:
group_19 = o_19.groupby(['GISJOIN'])

In [12]:
group_19 = group_19.size()

In [13]:
group_19 = group_19.reset_index()

In [14]:
group_19

GISJOIN  0
0     G40000103766001  2
1     G40000103767001  2
2     G40000103767002  3
3     G40000103767003  1
4     G40000103767004  2
...               ... ..
2592  G40015309532003  9
2593  G40015309533002  3
2594  G40015309534002  1
2595  G40015309534004  1
2596  G40015309535005  1

[2597 rows x 2 columns]

In [15]:
group_20 = o_20.groupby(['GISJOIN'])

In [16]:
group_20 = group_20.size()

In [17]:
group_20 = group_20.reset_index()

In [18]:
group_20

GISJOIN     0
0    G40000103767003     1
1    G40000103769003     1
2    G40000103770001     1
3    G40000103770004     1
4    G40000505876001  1254
..               ...   ...
309  G40014700006013     1
310  G40014700007002     1
311  G40014700010001    73
312  G40015309531001     1
313  G40015309532003     2

[314 rows x 2 columns]

In [19]:
group_21 = o_21.groupby(['GISJOIN'])
group_21

In [20]:
group_21 = group_21.size()
group_21

GISJOIN
G40000505876001    1477
G40001703007023       1
G40002903881001     203
G40002903882001     242
G40003100020031      61
                   ... 
G40014300076562       2
G40015109542012       1
G40015109542013       7
G40015109543003       1
G40015309531001       1
Length: 120, dtype: int64

In [21]:
group_21= group_21.reset_index()
group_21

GISJOIN     0
0    G40000505876001  1477
1    G40001703007023     1
2    G40002903881001   203
3    G40002903882001   242
4    G40003100020031    61
..               ...   ...
115  G40014300076562     2
116  G40015109542012     1
117  G40015109542013     7
118  G40015109543003     1
119  G40015309531001     1

[120 rows x 2 columns]

In [22]:
group_21

GISJOIN     0
0    G40000505876001  1477
1    G40001703007023     1
2    G40002903881001   203
3    G40002903882001   242
4    G40003100020031    61
..               ...   ...
115  G40014300076562     2
116  G40015109542012     1
117  G40015109542013     7
118  G40015109543003     1
119  G40015309531001     1

[120 rows x 2 columns]

In [23]:
okla.columns

Index(['Crash_ID', 'County_FIP', 'COUNTY', 'CITY', 'TIME', 'LIGHTING_CAT',
       'WEATHER_CAT', 'YEAR', 'ROAD_CLASS', 'INTOXICATION', 'LATITUDE',
       'LONGITUDE', 'INATTENTION', 'SPEEDING', 'TEEN_DRIVE', 'OLDER_DRIV',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'BUFF_DIST', 'GISJOIN', 'COUNTYFP',
       'Shape_Leng', 'GISJOIN.1', 'COUNTY.1', 'POPN'],
      dtype='object')

In [24]:
okla['LIGHTING_CAT'].unique()

array([1, 4, 3, 6, 2, 5, 8, 0], dtype=int64)

In [25]:
lighting_conditions = {
    1: 'DAYLIGHT',
    4: 'DARK-LIGHTED',
    3: 'DARK-NOT LIGHTED',
    6: 'DARK-UNKNOWN LIGHTING',
    5: 'DUSK',
    2: 'DAWN',
    0: 'UNK_LIGHT',
    8: 'OTHER_LIGHT'
}
def process_intoxication_data(df, mapping):
    # Map the intoxication codes to descriptive names
    df['light_desc'] = df['LIGHTING_CAT'].map(mapping).astype(str)

    # Create a list of all possible intoxication categories
    all_categories = list(mapping.values())

    # Group by COUNTY and INTOXICATION_DESC, then count occurrences
    grouped = df.groupby(['GISJOIN', 'light_desc']).size().unstack(fill_value=0)

    # Reindex the DataFrame to include all possible intoxication categories
    grouped = grouped.reindex(columns=all_categories, fill_value=0)

    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)

    # Calculate percentages
    light_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    light_percentages_df = light_percentages_df.reset_index(drop=False)

    return light_percentages_df

# Process each year's data
l_df_2019 = process_intoxication_data(o_19, lighting_conditions)
l_df_2020 = process_intoxication_data(o_20, lighting_conditions)
l_df_2021 = process_intoxication_data(o_21, lighting_conditions)



C:\Users\karan\AppData\Local\Temp\ipykernel_21608\3384557865.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['light_desc'] = df['LIGHTING_CAT'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_21608\3384557865.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['light_desc'] = df['LIGHTING_CAT'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_21608\3384557865.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

In [26]:
o1 = pd.merge(group_19,l_df_2019,on=['GISJOIN'],how='left')
o2 = pd.merge(group_20,l_df_2020,on=['GISJOIN'],how='left')
o3 = pd.merge(group_21,l_df_2021,on=['GISJOIN'],how='left')

In [27]:
o1.shape, o2.shape, o3.shape

((2597, 10), (314, 10), (120, 10))

In [28]:
o3

GISJOIN     0    DAYLIGHT  DARK-LIGHTED  DARK-NOT LIGHTED  \
0    G40000505876001  1477   68.449560     15.978334         12.389980   
1    G40001703007023     1  100.000000      0.000000          0.000000   
2    G40002903881001   203   67.487685      6.896552         20.689655   
3    G40002903882001   242   58.677686      2.479339         33.884298   
4    G40003100020031    61   59.016393      0.000000         36.065574   
..               ...   ...         ...           ...               ...   
115  G40014300076562     2  100.000000      0.000000          0.000000   
116  G40015109542012     1  100.000000      0.000000          0.000000   
117  G40015109542013     7   57.142857      0.000000          0.000000   
118  G40015109543003     1  100.000000      0.000000          0.000000   
119  G40015309531001     1  100.000000      0.000000          0.000000   

     DARK-UNKNOWN LIGHTING       DUSK       DAWN  UNK_LIGHT  OTHER_LIGHT  
0                 0.203114   1.624915   1.083277   0.135410      0.13541  
1                 0.000000   0.000000   0.000000   0.000000      0.00000  
2                 0.492611   3.940887   0.492611   0.000000      0.00000  
3                 0.000000   1.652893   2.479339   0.826446      0.00000  
4                 0.000000   1.639344   3.278689   0.000000      0.00000  
..                     ...        ...        ...        ...          ...  
115               0.000000   0.000000   0.000000   0.000000      0.00000  
116               0.000000   0.000000   0.000000   0.000000      0.00000  
117               0.000000  14.285714  28.571429   0.000000      0.00000  
118               0.000000   0.000000   0.000000   0.000000      0.00000  
119               0.000000   0.000000   0.000000   0.000000      0.00000  

[120 rows x 10 columns]

In [29]:
pop1 = o_19.groupby(['GISJOIN','POPN'])
pop1 = pop1.size()
pop1 = pop1.reset_index()
pop1

GISJOIN  POPN  0
0     G40000103766001   817  2
1     G40000103767001   589  2
2     G40000103767002  1364  3
3     G40000103767003   734  1
4     G40000103767004   803  2
...               ...   ... ..
2592  G40015309532003  1123  9
2593  G40015309533002  1726  3
2594  G40015309534002   716  1
2595  G40015309534004  1016  1
2596  G40015309535005  1082  1

[2597 rows x 3 columns]

In [30]:
pop2 = o_20.groupby(['GISJOIN','POPN'])
pop2 = pop2.size()
pop2 = pop2.reset_index()
pop2

GISJOIN  POPN     0
0    G40000103767003   734     1
1    G40000103769003  1411     1
2    G40000103770001  1597     1
3    G40000103770004  1173     1
4    G40000505876001  1146  1254
..               ...   ...   ...
309  G40014700006013  1331     1
310  G40014700007002  1349     1
311  G40014700010001  1214    73
312  G40015309531001   703     1
313  G40015309532003  1123     2

[314 rows x 3 columns]

In [31]:
pop3 = o_21.groupby(['GISJOIN','POPN'])
pop3 = pop3.size()
pop3 = pop3.reset_index()
pop3

GISJOIN  POPN     0
0    G40000505876001  1146  1477
1    G40001703007023  1155     1
2    G40002903881001   630   203
3    G40002903882001  1059   242
4    G40003100020031  2410    61
..               ...   ...   ...
115  G40014300076562  1092     2
116  G40015109542012   686     1
117  G40015109542013   621     7
118  G40015109543003  1343     1
119  G40015309531001   703     1

[120 rows x 3 columns]

In [32]:
o1 = pd.merge(o1,pop1,on=['GISJOIN'],how='left')
o2 = pd.merge(o2,pop2,on=['GISJOIN'],how='left')
o3 = pd.merge(o3,pop3,on=['GISJOIN'],how='left')

In [33]:
o1.columns

Index(['GISJOIN', '0_x', 'DAYLIGHT', 'DARK-LIGHTED', 'DARK-NOT LIGHTED',
       'DARK-UNKNOWN LIGHTING', 'DUSK', 'DAWN', 'UNK_LIGHT', 'OTHER_LIGHT',
       'POPN', '0_y'],
      dtype='object')

In [34]:
def drop(data):
    data.drop(columns=['0_x','0_y'],inplace=True)
    return data
    

In [35]:
o1 = drop(o1)

In [36]:
o2 = drop(o2)
o3 = drop(o3)

In [37]:
o1.shape, o2.shape, o3.shape

((2597, 10), (314, 10), (120, 10))

In [38]:
o2.columns

Index(['GISJOIN', 'DAYLIGHT', 'DARK-LIGHTED', 'DARK-NOT LIGHTED',
       'DARK-UNKNOWN LIGHTING', 'DUSK', 'DAWN', 'UNK_LIGHT', 'OTHER_LIGHT',
       'POPN'],
      dtype='object')

In [39]:
o3

GISJOIN    DAYLIGHT  DARK-LIGHTED  DARK-NOT LIGHTED  \
0    G40000505876001   68.449560     15.978334         12.389980   
1    G40001703007023  100.000000      0.000000          0.000000   
2    G40002903881001   67.487685      6.896552         20.689655   
3    G40002903882001   58.677686      2.479339         33.884298   
4    G40003100020031   59.016393      0.000000         36.065574   
..               ...         ...           ...               ...   
115  G40014300076562  100.000000      0.000000          0.000000   
116  G40015109542012  100.000000      0.000000          0.000000   
117  G40015109542013   57.142857      0.000000          0.000000   
118  G40015109543003  100.000000      0.000000          0.000000   
119  G40015309531001  100.000000      0.000000          0.000000   

     DARK-UNKNOWN LIGHTING       DUSK       DAWN  UNK_LIGHT  OTHER_LIGHT  POPN  
0                 0.203114   1.624915   1.083277   0.135410      0.13541  1146  
1                 0.000000   0.000000   0.000000   0.000000      0.00000  1155  
2                 0.492611   3.940887   0.492611   0.000000      0.00000   630  
3                 0.000000   1.652893   2.479339   0.826446      0.00000  1059  
4                 0.000000   1.639344   3.278689   0.000000      0.00000  2410  
..                     ...        ...        ...        ...          ...   ...  
115               0.000000   0.000000   0.000000   0.000000      0.00000  1092  
116               0.000000   0.000000   0.000000   0.000000      0.00000   686  
117               0.000000  14.285714  28.571429   0.000000      0.00000   621  
118               0.000000   0.000000   0.000000   0.000000      0.00000  1343  
119               0.000000   0.000000   0.000000   0.000000      0.00000   703  

[120 rows x 10 columns]

In [40]:
okla.columns

Index(['Crash_ID', 'County_FIP', 'COUNTY', 'CITY', 'TIME', 'LIGHTING_CAT',
       'WEATHER_CAT', 'YEAR', 'ROAD_CLASS', 'INTOXICATION', 'LATITUDE',
       'LONGITUDE', 'INATTENTION', 'SPEEDING', 'TEEN_DRIVE', 'OLDER_DRIV',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'BUFF_DIST', 'GISJOIN', 'COUNTYFP',
       'Shape_Leng', 'GISJOIN.1', 'COUNTY.1', 'POPN'],
      dtype='object')

In [41]:
okla['WEATHER_CAT'].unique()

array([11,  2,  3, 12,  0,  5,  4,  7,  6,  8], dtype=int64)

In [42]:
weather_mapping = {
    11: 'CLEAR',
    12: 'CLOUDY',
    5: 'FOG',
    2: 'RAIN',
    3: 'SLEET/HAIL',
    8: 'OTHER_WEATHER',
    0: 'UNK_Weather',
    4: 'SNOW_Weather',
    6: 'BLOWING SAND/SNOW',
    7: 'SEVERE CROSSWINDS'
}

def process_road_type_data(df, mapping):
    # Map the road type codes to descriptive names
    df['weather_DESC'] = df['WEATHER_CAT'].map(mapping).astype(str)
    
    all_categories = list(mapping.values())
    
    # Group by COUNTY and ROAD_TYPE_DESC, then count occurrences
    grouped = df.groupby(['GISJOIN', 'weather_DESC']).size().unstack(fill_value=0)
    
    grouped = grouped.reindex(columns=all_categories, fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_road_type = grouped.sum(axis=1)
    
    # Calculate percentages
    road_type_percentages_df = (grouped.div(total_counts_by_county_road_type, axis=0) * 100).fillna(0)
    road_type_percentages_df = road_type_percentages_df.reset_index()
    
    return road_type_percentages_df

# Apply the function to each yearly DataFrame
w_type_percentages_df_2019 = process_road_type_data(o_19, weather_mapping)
w_type_percentages_df_2020 = process_road_type_data(o_20, weather_mapping)
w_type_percentages_df_2021 = process_road_type_data(o_21, weather_mapping)


C:\Users\karan\AppData\Local\Temp\ipykernel_21608\433814867.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weather_DESC'] = df['WEATHER_CAT'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_21608\433814867.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weather_DESC'] = df['WEATHER_CAT'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_21608\433814867.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.

In [43]:
w_type_percentages_df_2019

weather_DESC          GISJOIN       CLEAR      CLOUDY  FOG  RAIN  SLEET/HAIL  \
0             G40000103766001  100.000000    0.000000  0.0   0.0         0.0   
1             G40000103767001   50.000000    0.000000  0.0  50.0         0.0   
2             G40000103767002   66.666667   33.333333  0.0   0.0         0.0   
3             G40000103767003    0.000000  100.000000  0.0   0.0         0.0   
4             G40000103767004  100.000000    0.000000  0.0   0.0         0.0   
...                       ...         ...         ...  ...   ...         ...   
2592          G40015309532003   66.666667    0.000000  0.0   0.0         0.0   
2593          G40015309533002  100.000000    0.000000  0.0   0.0         0.0   
2594          G40015309534002  100.000000    0.000000  0.0   0.0         0.0   
2595          G40015309534004  100.000000    0.000000  0.0   0.0         0.0   
2596          G40015309535005  100.000000    0.000000  0.0   0.0         0.0   

weather_DESC  OTHER_WEATHER  UNK_Weather  SNOW_Weather  BLOWING SAND/SNOW  \
0                       0.0          0.0      0.000000                0.0   
1                       0.0          0.0      0.000000                0.0   
2                       0.0          0.0      0.000000                0.0   
3                       0.0          0.0      0.000000                0.0   
4                       0.0          0.0      0.000000                0.0   
...                     ...          ...           ...                ...   
2592                    0.0          0.0     33.333333                0.0   
2593                    0.0          0.0      0.000000                0.0   
2594                    0.0          0.0      0.000000                0.0   
2595                    0.0          0.0      0.000000                0.0   
2596                    0.0          0.0      0.000000                0.0   

weather_DESC  SEVERE CROSSWINDS  
0                           0.0  
1                           0.0  
2                           0.0  
3                           0.0  
4                           0.0  
...                         ...  
2592                        0.0  
2593                        0.0  
2594                        0.0  
2595                        0.0  
2596                        0.0  

[2597 rows x 11 columns]

In [44]:
o1 = pd.merge(o1,w_type_percentages_df_2019,on=['GISJOIN'],how='left')
o2 = pd.merge(o2,w_type_percentages_df_2020,on=['GISJOIN'],how='left')
o3 = pd.merge(o3,w_type_percentages_df_2021,on=['GISJOIN'],how='left')

In [45]:
o1.shape, o2.shape, o3.shape

((2597, 20), (314, 20), (120, 20))

In [46]:
okla.columns

Index(['Crash_ID', 'County_FIP', 'COUNTY', 'CITY', 'TIME', 'LIGHTING_CAT',
       'WEATHER_CAT', 'YEAR', 'ROAD_CLASS', 'INTOXICATION', 'LATITUDE',
       'LONGITUDE', 'INATTENTION', 'SPEEDING', 'TEEN_DRIVE', 'OLDER_DRIV',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'BUFF_DIST', 'GISJOIN', 'COUNTYFP',
       'Shape_Leng', 'GISJOIN.1', 'COUNTY.1', 'POPN'],
      dtype='object')

In [47]:
okla['ROAD_CLASS'].unique()

array([2, 5, 1, 4, 7], dtype=int64)

In [48]:
roadway_types = {
    1: 'INTERSTATE',
    2: 'US & STATE HIGHWAY',
    3: 'FARM TO MARKET',
    4: 'COUNTY ROAD',
    5: 'CITY STREET',
    6: 'TOLLWAY',
    7: 'OTHER ROADS',
    8: 'TOLL BRIDGES'
}


def process_road_type_data(df, mapping):
    # Map the road type codes to descriptive names
    df['ROAD_TYPE_DESC'] = df['ROAD_CLASS'].map(mapping).astype(str)
    
    all_categories = list(mapping.values())
    
    # Group by COUNTY and ROAD_TYPE_DESC, then count occurrences
    grouped = df.groupby(['GISJOIN', 'ROAD_TYPE_DESC']).size().unstack(fill_value=0)
    
    grouped = grouped.reindex(columns=all_categories, fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_road_type = grouped.sum(axis=1)
    
    # Calculate percentages
    road_type_percentages_df = (grouped.div(total_counts_by_county_road_type, axis=0) * 100).fillna(0)
    road_type_percentages_df = road_type_percentages_df.reset_index()
    
    return road_type_percentages_df

# Apply the function to each yearly DataFrame
road_type_percentages_df_2019 = process_road_type_data(o_19, roadway_types)
road_type_percentages_df_2020 = process_road_type_data(o_20, roadway_types)
road_type_percentages_df_2021 = process_road_type_data(o_21, roadway_types)


C:\Users\karan\AppData\Local\Temp\ipykernel_21608\1972534223.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ROAD_TYPE_DESC'] = df['ROAD_CLASS'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_21608\1972534223.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ROAD_TYPE_DESC'] = df['ROAD_CLASS'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_21608\1972534223.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataF

In [49]:
road_type_percentages_df_2019

ROAD_TYPE_DESC          GISJOIN  INTERSTATE  US & STATE HIGHWAY  \
0               G40000103766001         0.0           50.000000   
1               G40000103767001         0.0           50.000000   
2               G40000103767002         0.0           33.333333   
3               G40000103767003         0.0          100.000000   
4               G40000103767004         0.0           50.000000   
...                         ...         ...                 ...   
2592            G40015309532003         0.0           77.777778   
2593            G40015309533002         0.0          100.000000   
2594            G40015309534002         0.0            0.000000   
2595            G40015309534004         0.0          100.000000   
2596            G40015309535005         0.0            0.000000   

ROAD_TYPE_DESC  FARM TO MARKET  COUNTY ROAD  CITY STREET  TOLLWAY  \
0                          0.0    50.000000          0.0      0.0   
1                          0.0    50.000000          0.0      0.0   
2                          0.0    66.666667          0.0      0.0   
3                          0.0     0.000000          0.0      0.0   
4                          0.0    50.000000          0.0      0.0   
...                        ...          ...          ...      ...   
2592                       0.0    22.222222          0.0      0.0   
2593                       0.0     0.000000          0.0      0.0   
2594                       0.0     0.000000        100.0      0.0   
2595                       0.0     0.000000          0.0      0.0   
2596                       0.0   100.000000          0.0      0.0   

ROAD_TYPE_DESC  OTHER ROADS  TOLL BRIDGES  
0                       0.0           0.0  
1                       0.0           0.0  
2                       0.0           0.0  
3                       0.0           0.0  
4                       0.0           0.0  
...                     ...           ...  
2592                    0.0           0.0  
2593                    0.0           0.0  
2594                    0.0           0.0  
2595                    0.0           0.0  
2596                    0.0           0.0  

[2597 rows x 9 columns]

In [50]:
o1 = pd.merge(o1,road_type_percentages_df_2019,on=['GISJOIN'],how='left')
o2 = pd.merge(o2,road_type_percentages_df_2020,on=['GISJOIN'],how='left')
o3 = pd.merge(o3,road_type_percentages_df_2021,on=['GISJOIN'],how='left')

In [51]:
o1.shape, o2.shape, o3.shape

((2597, 28), (314, 28), (120, 28))

In [52]:
okla['INTOXICATION'].unique()

array([4, 1, 3, 2], dtype=int64)

In [53]:
okla.columns

Index(['Crash_ID', 'County_FIP', 'COUNTY', 'CITY', 'TIME', 'LIGHTING_CAT',
       'WEATHER_CAT', 'YEAR', 'ROAD_CLASS', 'INTOXICATION', 'LATITUDE',
       'LONGITUDE', 'INATTENTION', 'SPEEDING', 'TEEN_DRIVE', 'OLDER_DRIV',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'BUFF_DIST', 'GISJOIN', 'COUNTYFP',
       'Shape_Leng', 'GISJOIN.1', 'COUNTY.1', 'POPN'],
      dtype='object')

In [54]:
okla['INTOXICATION'].unique()

array([4, 1, 3, 2], dtype=int64)

In [55]:
intoxication_mapping = {
    1: 'ALCOHOL',
    2: 'DRUG',
    3: 'ALCOHOL, DRUG',
    4: 'NO INTOXICATION',
    5: 'MEDICINAL',
    6: 'MARIJUANA'
}
def process_intoxication_data(df, mapping):
    # Map the intoxication codes to descriptive names
    df['INT_DESC'] = df['INTOXICATION'].map(mapping).astype(str)

    # Create a list of all possible intoxication categories
    all_categories = list(mapping.values())

    # Group by COUNTY and INTOXICATION_DESC, then count occurrences
    grouped = df.groupby(['GISJOIN', 'INT_DESC']).size().unstack(fill_value=0)

    # Reindex the DataFrame to include all possible intoxication categories
    grouped = grouped.reindex(columns=all_categories, fill_value=0)

    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)

    # Calculate percentages
    test_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    test_percentages_df = test_percentages_df.reset_index(drop=False)

    return test_percentages_df

# Process each year's data
int_df_2019 = process_intoxication_data(o_19, intoxication_mapping)
int_df_2020 = process_intoxication_data(o_20, intoxication_mapping)
int_df_2021 = process_intoxication_data(o_21, intoxication_mapping)


C:\Users\karan\AppData\Local\Temp\ipykernel_21608\2935850862.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['INT_DESC'] = df['INTOXICATION'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_21608\2935850862.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['INT_DESC'] = df['INTOXICATION'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_21608\2935850862.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Tr

In [56]:
int_df_2019.shape, int_df_2020.shape, int_df_2021.shape

((2597, 7), (314, 7), (120, 7))

In [57]:
int_df_2019.columns

Index(['GISJOIN', 'ALCOHOL', 'DRUG', 'ALCOHOL, DRUG', 'NO INTOXICATION',
       'MEDICINAL', 'MARIJUANA'],
      dtype='object', name='INT_DESC')

In [58]:
o1 = pd.merge(o1,int_df_2019,on=['GISJOIN'],how='left')
o2 = pd.merge(o2,int_df_2020,on=['GISJOIN'],how='left')
o3 = pd.merge(o3,int_df_2021,on=['GISJOIN'],how='left')

In [59]:
o1.shape, o2.shape,o3.shape

((2597, 34), (314, 34), (120, 34))

In [60]:
okla.columns

Index(['Crash_ID', 'County_FIP', 'COUNTY', 'CITY', 'TIME', 'LIGHTING_CAT',
       'WEATHER_CAT', 'YEAR', 'ROAD_CLASS', 'INTOXICATION', 'LATITUDE',
       'LONGITUDE', 'INATTENTION', 'SPEEDING', 'TEEN_DRIVE', 'OLDER_DRIV',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'BUFF_DIST', 'GISJOIN', 'COUNTYFP',
       'Shape_Leng', 'GISJOIN.1', 'COUNTY.1', 'POPN'],
      dtype='object')

In [61]:
okla['INATTENTION']

0        0
1        1
2        0
3        0
4        0
        ..
27692    0
27693    1
27694    0
27695    0
27696    0
Name: INATTENTION, Length: 27697, dtype: int64

In [62]:
grouped_intersection = okla.groupby(['GISJOIN', 'INATTENTION']).size().unstack(fill_value=0)
grouped_intersection

INATTENTION       0  1
GISJOIN               
G40000103766001   1  1
G40000103767001   2  0
G40000103767002   3  0
G40000103767003   1  1
G40000103767004   1  1
...              .. ..
G40015309532003  11  0
G40015309533002   3  0
G40015309534002   1  0
G40015309534004   0  1
G40015309535005   0  1

[2657 rows x 2 columns]

In [63]:
def calculate_intersection_percentages(df):
    grouped_intersection = df.groupby(['GISJOIN', 'INATTENTION']).size().unstack(fill_value=0)
    grouped_intersection.columns = ['NO_INATTENTION', 'YES_INATTENTION']
    total_counts_by_county = grouped_intersection.sum(axis=1)
    no_intersection_percentage = (grouped_intersection['NO_INATTENTION'] / total_counts_by_county) * 100
    yes_intersection_percentage = (grouped_intersection['YES_INATTENTION'] / total_counts_by_county) * 100

    intersection_percentages_df = pd.concat([
        no_intersection_percentage,
        yes_intersection_percentage
    ], axis=1)
    intersection_percentages_df.columns = ['NO_INATTENTION', 'YES_INATTENTION']
    intersection_percentages_df = intersection_percentages_df.reset_index().rename(columns={'index': 'GISJOIN'})
    intersection_percentages_df.fillna(0, inplace=True)

    return intersection_percentages_df

In [64]:
int1 = calculate_intersection_percentages(o_19)
int2 = calculate_intersection_percentages(o_20)
int3 = calculate_intersection_percentages(o_21)

In [65]:
o1 = pd.merge(o1,int1,on=['GISJOIN'],how='left')
o2 = pd.merge(o2,int2,on=['GISJOIN'],how='left')
o3 = pd.merge(o3,int3,on=['GISJOIN'],how='left')

In [66]:
o1.shape, o2.shape,o3.shape

((2597, 36), (314, 36), (120, 36))

In [67]:
okla['SPEEDING'].unique()

array([0, 1], dtype=int64)

In [68]:
sp1 = calculate_intersection_percentages(o_19)

In [69]:
o_19['SPEEDING'].unique()

array([0, 1], dtype=int64)

In [70]:
o_21['SPEEDING'].unique()

array([0], dtype=int64)

In [71]:
o_20['SPEEDING'].unique()

array([0], dtype=int64)

In [72]:
calculate_intersection_percentages(o_19)

GISJOIN  NO_INATTENTION  YES_INATTENTION
0     G40000103766001            50.0             50.0
1     G40000103767001           100.0              0.0
2     G40000103767002           100.0              0.0
3     G40000103767003             0.0            100.0
4     G40000103767004            50.0             50.0
...               ...             ...              ...
2592  G40015309532003           100.0              0.0
2593  G40015309533002           100.0              0.0
2594  G40015309534002           100.0              0.0
2595  G40015309534004             0.0            100.0
2596  G40015309535005             0.0            100.0

[2597 rows x 3 columns]

In [73]:
def calculate_intersection_percentages(df):
    grouped_intersection = df.groupby(['GISJOIN', 'SPEEDING']).size().unstack(fill_value=0)
    
    # Ensure both columns 'NO_SPD' and 'YES_SPD' are always present
    if 0 in grouped_intersection.columns and 1 in grouped_intersection.columns:
        grouped_intersection.columns = ['NO_SPD', 'YES_SPD']
    elif 0 in grouped_intersection.columns:
        grouped_intersection.columns = ['NO_SPD']
        grouped_intersection['YES_SPD'] = 0
    else:
        grouped_intersection.columns = ['YES_SPD']
        grouped_intersection['NO_SPD'] = 0
    
    total_counts_by_county = grouped_intersection.sum(axis=1)

    no_intersection_percentage = (grouped_intersection['NO_SPD'] / total_counts_by_county) * 100
    yes_intersection_percentage = (grouped_intersection['YES_SPD'] / total_counts_by_county) * 100

    # Replace NaN values with 0
    no_intersection_percentage.fillna(0, inplace=True)
    yes_intersection_percentage.fillna(0, inplace=True)

    # Ensure that both no_intersection_percentage and yes_intersection_percentage have the same index
    no_intersection_percentage = no_intersection_percentage.reindex(grouped_intersection.index, fill_value=0)
    yes_intersection_percentage = yes_intersection_percentage.reindex(grouped_intersection.index, fill_value=0)

    intersection_percentages_df = pd.concat([
        no_intersection_percentage,
        yes_intersection_percentage
    ], axis=1)
    
    intersection_percentages_df.columns = ['NO_SPD', 'YES_SPD']
    intersection_percentages_df = intersection_percentages_df.reset_index().rename(columns={'index': 'GISJOIN'})

    return intersection_percentages_df

In [74]:
sp1 = calculate_intersection_percentages(o_19)
sp1

GISJOIN      NO_SPD    YES_SPD
0     G40000103766001   50.000000  50.000000
1     G40000103767001  100.000000   0.000000
2     G40000103767002   33.333333  66.666667
3     G40000103767003  100.000000   0.000000
4     G40000103767004  100.000000   0.000000
...               ...         ...        ...
2592  G40015309532003   44.444444  55.555556
2593  G40015309533002   66.666667  33.333333
2594  G40015309534002  100.000000   0.000000
2595  G40015309534004  100.000000   0.000000
2596  G40015309535005  100.000000   0.000000

[2597 rows x 3 columns]

In [75]:
sp2 = calculate_intersection_percentages(o_20)

In [76]:
sp3 = calculate_intersection_percentages(o_21)

In [77]:
o1 = pd.merge(o1,sp1,on=['GISJOIN'],how='left')
o2 = pd.merge(o2,sp2,on=['GISJOIN'],how='left')
o3 = pd.merge(o3,sp3,on=['GISJOIN'],how='left')

In [78]:
o1.shape, o2.shape, o3.shape

((2597, 38), (314, 38), (120, 38))

In [79]:
okla.columns

Index(['Crash_ID', 'County_FIP', 'COUNTY', 'CITY', 'TIME', 'LIGHTING_CAT',
       'WEATHER_CAT', 'YEAR', 'ROAD_CLASS', 'INTOXICATION', 'LATITUDE',
       'LONGITUDE', 'INATTENTION', 'SPEEDING', 'TEEN_DRIVE', 'OLDER_DRIV',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'BUFF_DIST', 'GISJOIN', 'COUNTYFP',
       'Shape_Leng', 'GISJOIN.1', 'COUNTY.1', 'POPN'],
      dtype='object')

In [80]:
o_21['INJURY_OUTCOME'].unique()

array([1, 0], dtype=int64)

In [81]:
def calculate_intersection_percentages(df):
    grouped_intersection = df.groupby(['GISJOIN', 'INJURY_OUTCOME']).size().unstack(fill_value=0)
    grouped_intersection.columns = ['NO_INJ', 'YES_INJ']
    total_counts_by_county = grouped_intersection.sum(axis=1)
    no_intersection_percentage = (grouped_intersection['NO_INJ'] / total_counts_by_county) * 100
    yes_intersection_percentage = (grouped_intersection['YES_INJ'] / total_counts_by_county) * 100

    intersection_percentages_df = pd.concat([
        no_intersection_percentage,
        yes_intersection_percentage
    ], axis=1)
    intersection_percentages_df.columns = ['NO_INJ', 'YES_INJ']
    intersection_percentages_df = intersection_percentages_df.reset_index().rename(columns={'index': 'GISJOIN'})
    intersection_percentages_df.fillna(0, inplace=True)

    return intersection_percentages_df

In [82]:
in1 = calculate_intersection_percentages(o_19)
in2 = calculate_intersection_percentages(o_20)
in3 = calculate_intersection_percentages(o_21)

In [83]:
o1 = pd.merge(o1,in1,on=['GISJOIN'],how='left')
o2 = pd.merge(o2,in2,on=['GISJOIN'],how='left')
o3 = pd.merge(o3,in3,on=['GISJOIN'],how='left')

In [84]:
o1.shape, o2.shape,  o3.shape

((2597, 40), (314, 40), (120, 40))

In [85]:
def process_median_width_data(df):
    # Group by COUNTY and MEDIANWIDTH, then aggregate to calculate the sum and median
    aggregated_data = df.groupby('GISJOIN')['INJURY_COUNT'].agg(['sum']).reset_index()
 
    # Rename columns for clarity
    aggregated_data.columns = ['GISJOIN', 'INJ_COUNT_SUM']
 
   
 
    return aggregated_data
 
# Assuming df_2019, df_2020, df_2021 are your dataframes for each respective year
inj_width_summary_df_2019 = process_median_width_data(o_19)
inj_width_summary_df_2020 = process_median_width_data(o_20)
inj_width_summary_df_2021 = process_median_width_data(o_21)
 


In [86]:
o1 = pd.merge(o1,inj_width_summary_df_2019,on=['GISJOIN'],how='left')
o2 = pd.merge(o2,inj_width_summary_df_2020,on=['GISJOIN'],how='left')
o3 = pd.merge(o3,inj_width_summary_df_2021,on=['GISJOIN'],how='left')

In [87]:
o1.shape, o2.shape, o3.shape

((2597, 41), (314, 41), (120, 41))

In [88]:
okla.columns

Index(['Crash_ID', 'County_FIP', 'COUNTY', 'CITY', 'TIME', 'LIGHTING_CAT',
       'WEATHER_CAT', 'YEAR', 'ROAD_CLASS', 'INTOXICATION', 'LATITUDE',
       'LONGITUDE', 'INATTENTION', 'SPEEDING', 'TEEN_DRIVE', 'OLDER_DRIV',
       'INJURY_COUNT', 'INJURY_OUTCOME', 'BUFF_DIST', 'GISJOIN', 'COUNTYFP',
       'Shape_Leng', 'GISJOIN.1', 'COUNTY.1', 'POPN'],
      dtype='object')

In [89]:
o1['YEAR'] = 2019
o2['YEAR'] = 2020
o3['YEAR'] = 2021

In [95]:
o1['STATE'] = 'Oklahoma'
o2['STATE'] = 'Oklahoma'
o3['STATE'] = 'Oklahoma'

In [98]:
o1.to_csv('okla_2019.csv',index= False)
#o2.to_csv('okla_2020.csv',index= False)
#o3.to_csv('okla_2021.csv',index= False)

In [90]:
okla = pd.concat([o1,o2,o3],axis=0)

In [91]:
okla.isna().sum().sum()

0

In [92]:
okla['STATE'] = 'Oklahoma'

In [93]:
okla.to_csv('okla.csv',index= False)