In [1]:
import numpy as np
import pandas as pd

In [2]:
t1 = pd.read_csv('C:/Users/karan/Texas_2019_LSAD.csv')
t2 = pd.read_csv('C:/Users/karan/Texas_2020_LSAD.csv')
t3 = pd.read_csv('C:/Users/karan/Texas_2021_LSAD.csv')

In [3]:
t1.shape, t2.shape,t3.shape

((16032, 82), (16032, 79), (16032, 78))

In [4]:
t1.columns

Index(['GISJOIN', 'TEXAS_CopyFeatures1_STATEFP',
       'TEXAS_CopyFeatures1_COUNTYFP', 'TEXAS_CopyFeatures1_Shape_Leng',
       'COUNT', 'ALCOHOL', 'DRUG', 'ALCOHOL__DRUG', 'NO_INTOXICATION',
       'MEDICINAL', 'MARIJUANA', 'Race_UNK', 'White', 'Hispanic', 'Black',
       'Asian', 'Other', 'American_Native', 'BLOWING_SAND_SNOW', 'CLEAR',
       'CLOUDY', 'FOG', 'Other_Weather', 'RAIN', 'SEVERE_CROSSWINDS',
       'SLEET_HAIL', 'SNOW_Weather', 'UNK_Weather', 'DAYLIGHT', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN',
       'UNK_LIGHT', 'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD',
       'FARM_TO_MARKET', 'INTERSTATE', 'OTHER_ROADS', 'TOLL_BRIDGES',
       'TOLLWAY', 'US_STATE_HIGHWAY', 'DRY', 'ICE', 'OTHER_SURF',
       'SAND_MUD_DIRT', 'SLUSH', 'SNOW_SURF', 'STANDING_WATER', 'UNKNOWN_SURF',
       'WET', 'SPEEDING', 'INATTENTION', 'LANE_CHANGE', 'TAILGATING',
       'VIOLATION', 'UNSAFE_BACKING', 'IMPAIRMENT', 'TURNING', 'TECH_PARK',
       'NO_FA

In [5]:
cols= ['GISJOIN', 'STATEFP', 'Shape_Leng', 'COUNT', 'ALCOHOL', 'DRUG',
       'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
        'BLOWING_SAND_SNOW', 'CLEAR', 'CLOUDY', 'FOG',
       'Other_Weather', 'RAIN', 'SEVERE_CROSSWINDS', 'SLEET_HAIL',
       'SNOW_Weather', 'UNK_Weather', 'DAYLIGHT', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN',
       'UNK_LIGHT', 'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD',
       'FARM_TO_MARKET', 'INTERSTATE', 'OTHER_ROADS', 'TOLL_BRIDGES',
       'TOLLWAY', 'US_STATE_HIGHWAY', 'DRY', 'ICE', 'OTHER_SURF',
       'SAND_MUD_DIRT', 'SLUSH', 'SNOW_SURF', 'STANDING_WATER', 'UNKNOWN_SURF',
       'WET', 'SPEEDING', 'INATTENTION', 'LANE_CHANGE', 'TAILGATING',
       'VIOLATION', 'UNSAFE_BACKING', 'IMPAIRMENT', 'TURNING', 'TECH_PARK',
       'NO_FAULT', 'KNOWN_HUMAN_FACTOR', 'UNKNOWN_HUMAN_FACTOR', 'FATAL',
       'MIN_INJURY', 'NO_INJURY', 'POSBL_INJURY','UNK_SEVERITY', 'NO_INJ', 'YES_INJ', 'INJ_COUNT_SUM', 'POPN', 'YEAR','Shape_Area','NAME']

In [6]:
t1.rename(columns={'TEXAS_CopyFeatures1_Shape_Leng':'Shape_Leng'},inplace= True)

In [7]:
t1.drop(columns=['TEXAS_CopyFeatures1_COUNTYFP'],inplace= True)

In [8]:
t2.drop(columns=['TEXAS_CopyFeatures_1_BLKGRPCE'],inplace= True)

In [9]:
t1.columns

Index(['GISJOIN', 'TEXAS_CopyFeatures1_STATEFP', 'Shape_Leng', 'COUNT',
       'ALCOHOL', 'DRUG', 'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL',
       'MARIJUANA', 'Race_UNK', 'White', 'Hispanic', 'Black', 'Asian', 'Other',
       'American_Native', 'BLOWING_SAND_SNOW', 'CLEAR', 'CLOUDY', 'FOG',
       'Other_Weather', 'RAIN', 'SEVERE_CROSSWINDS', 'SLEET_HAIL',
       'SNOW_Weather', 'UNK_Weather', 'DAYLIGHT', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN',
       'UNK_LIGHT', 'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD',
       'FARM_TO_MARKET', 'INTERSTATE', 'OTHER_ROADS', 'TOLL_BRIDGES',
       'TOLLWAY', 'US_STATE_HIGHWAY', 'DRY', 'ICE', 'OTHER_SURF',
       'SAND_MUD_DIRT', 'SLUSH', 'SNOW_SURF', 'STANDING_WATER', 'UNKNOWN_SURF',
       'WET', 'SPEEDING', 'INATTENTION', 'LANE_CHANGE', 'TAILGATING',
       'VIOLATION', 'UNSAFE_BACKING', 'IMPAIRMENT', 'TURNING', 'TECH_PARK',
       'NO_FAULT', 'KNOWN_HUMAN_FACTOR', 'UNKNOWN_HUMAN_FACTOR', 'FATAL'

In [10]:
t2.rename(columns={'TEXAS_CopyFeatures_1_STATEFP':'STATEFP'},inplace= True)

In [11]:
t1.rename(columns={'TEXAS_CopyFeatures1_STATEFP':'STATEFP'},inplace= True)

In [12]:
t2.columns

Index(['GISJOIN', 'STATEFP', 'TEXAS_CopyFeatures_1_COUNTYFP', 'Shape_Leng',
       'COUNT', 'ALCOHOL', 'DRUG', 'ALCOHOL__DRUG', 'No_INTOXICATION',
       'MEDICINAL', 'MARIJUANA', 'Race_UNK', 'White', 'Hispanic', 'Black',
       'Asian', 'Other_Race', 'American_Native', 'BLOWING_SAND_SNOW', 'CLEAR',
       'CLOUDY', 'FOG', 'Other_Weather ', 'RAIN', 'SEVERE_CROSSWINDS',
       'SLEET_HAIL', 'SNOW_Weather', 'UNK_Weather', 'DAYLIGHT', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN',
       'UNK_LIGHT', 'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD',
       'FARM_TO_MARKET', 'INTERSTATE', 'OTHER_ROADS', 'TOLL_BRIDGES',
       'TOLLWAY', 'US_STATE_HIGHWAY', 'DRY', 'ICE', 'OTHER_SURF',
       'SAND_MUD_DIRT', 'SLUSH', 'SNOW_SURF', 'STANDING_WATER', 'UNKNOWN_SURF',
       'WET', 'SPEEDING', 'INATTENTION', 'LANE_CHANGE', 'TAILGATING',
       'texas_2020_csv_VIOLATION', 'UNSAFE_BACKING', 'IMPAIRMENT', 'TURNING',
       'TECH_PARK', 'NO_FAULT', 'KNOWN_HUMAN_FACTOR

In [13]:
t = t1.columns.intersection(t2.columns)
len(t)

72

In [14]:
t2.rename(columns={'No_INTOXICATION':'NO_INTOXICATION','texas_2020_csv_VIOLATION':'VIOLATION'},inplace= True)

In [15]:
w1 = set(t1.columns)
w2= set(t2.columns)
w1-w2

{'FID_LSAD_Metropolitan',
 'GISJOIN.1',
 'LSAD',
 'NAMELSAD',
 'Other',
 'Other_Weather',
 'Sus_serious_Inj'}

In [16]:
t1.columns.tolist().index('Other')

15

In [17]:
t1['YEAR'].unique()

array([2019,    0], dtype=int64)

In [18]:
t2['YEAR'].unique()

array([2020,    0], dtype=int64)

In [19]:
t1.columns

Index(['GISJOIN', 'STATEFP', 'Shape_Leng', 'COUNT', 'ALCOHOL', 'DRUG',
       'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
       'Race_UNK', 'White', 'Hispanic', 'Black', 'Asian', 'Other',
       'American_Native', 'BLOWING_SAND_SNOW', 'CLEAR', 'CLOUDY', 'FOG',
       'Other_Weather', 'RAIN', 'SEVERE_CROSSWINDS', 'SLEET_HAIL',
       'SNOW_Weather', 'UNK_Weather', 'DAYLIGHT', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN',
       'UNK_LIGHT', 'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD',
       'FARM_TO_MARKET', 'INTERSTATE', 'OTHER_ROADS', 'TOLL_BRIDGES',
       'TOLLWAY', 'US_STATE_HIGHWAY', 'DRY', 'ICE', 'OTHER_SURF',
       'SAND_MUD_DIRT', 'SLUSH', 'SNOW_SURF', 'STANDING_WATER', 'UNKNOWN_SURF',
       'WET', 'SPEEDING', 'INATTENTION', 'LANE_CHANGE', 'TAILGATING',
       'VIOLATION', 'UNSAFE_BACKING', 'IMPAIRMENT', 'TURNING', 'TECH_PARK',
       'NO_FAULT', 'KNOWN_HUMAN_FACTOR', 'UNKNOWN_HUMAN_FACTOR', 'FATAL',
       'MIN_INJURY

In [20]:
t2.rename(columns={'Other_Weather ':'Other_Weather'},inplace= True)

In [21]:
t11 = t1[cols]

In [22]:
t22 = t2[cols]

In [23]:
t22.columns

Index(['GISJOIN', 'STATEFP', 'Shape_Leng', 'COUNT', 'ALCOHOL', 'DRUG',
       'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
       'BLOWING_SAND_SNOW', 'CLEAR', 'CLOUDY', 'FOG', 'Other_Weather', 'RAIN',
       'SEVERE_CROSSWINDS', 'SLEET_HAIL', 'SNOW_Weather', 'UNK_Weather',
       'DAYLIGHT', 'DARK_LIGHTED', 'DARK_NOT_LIGHTED', 'DARK_UNKNOWN_LIGHTING',
       'DUSK', 'DAWN', 'UNK_LIGHT', 'OTHER_LIGHT', 'CITY_STREET',
       'COUNTY_ROAD', 'FARM_TO_MARKET', 'INTERSTATE', 'OTHER_ROADS',
       'TOLL_BRIDGES', 'TOLLWAY', 'US_STATE_HIGHWAY', 'DRY', 'ICE',
       'OTHER_SURF', 'SAND_MUD_DIRT', 'SLUSH', 'SNOW_SURF', 'STANDING_WATER',
       'UNKNOWN_SURF', 'WET', 'SPEEDING', 'INATTENTION', 'LANE_CHANGE',
       'TAILGATING', 'VIOLATION', 'UNSAFE_BACKING', 'IMPAIRMENT', 'TURNING',
       'TECH_PARK', 'NO_FAULT', 'KNOWN_HUMAN_FACTOR', 'UNKNOWN_HUMAN_FACTOR',
       'FATAL', 'MIN_INJURY', 'NO_INJURY', 'POSBL_INJURY', 'UNK_SEVERITY',
       'NO_INJ', 'YES_INJ', 'INJ_COUNT_SUM', 

In [24]:
t3.columns = t3.columns.str.replace('TEXAS_CopyFeatures_','')

In [25]:
t33 = t3[cols]

In [26]:
t11['YEAR'].unique()

array([2019,    0], dtype=int64)

In [27]:
t11['YEAR'] = np.where(t11['YEAR']==0,2019,t11['YEAR'])

C:\Users\karan\AppData\Local\Temp\ipykernel_25652\115541228.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t11['YEAR'] = np.where(t11['YEAR']==0,2019,t11['YEAR'])


In [28]:
t22['YEAR'] = np.where(t22['YEAR']==0,2020,t22['YEAR'])

C:\Users\karan\AppData\Local\Temp\ipykernel_25652\329786148.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t22['YEAR'] = np.where(t22['YEAR']==0,2020,t22['YEAR'])


In [29]:
t33['YEAR'] = np.where(t33['YEAR']==0,2021,t33['YEAR'])

C:\Users\karan\AppData\Local\Temp\ipykernel_25652\4024975471.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t33['YEAR'] = np.where(t33['YEAR']==0,2021,t33['YEAR'])


In [30]:
t11['YEAR_CAT'] = 1
t22['YEAR_CAT'] =2
t33['YEAR_CAT'] =3

C:\Users\karan\AppData\Local\Temp\ipykernel_25652\658547526.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t11['YEAR_CAT'] = 1
C:\Users\karan\AppData\Local\Temp\ipykernel_25652\658547526.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t22['YEAR_CAT'] =2
C:\Users\karan\AppData\Local\Temp\ipykernel_25652\658547526.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentati

In [31]:
t11['STATE_CAT'] = 1
t22['STATE_CAT'] =1
t33['STATE_CAT'] =1

C:\Users\karan\AppData\Local\Temp\ipykernel_25652\668016725.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t11['STATE_CAT'] = 1
C:\Users\karan\AppData\Local\Temp\ipykernel_25652\668016725.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t22['STATE_CAT'] =1
C:\Users\karan\AppData\Local\Temp\ipykernel_25652\668016725.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documenta

In [32]:
texas = pd.concat([t11,t22,t33],axis=0)
texas['STATE'] = 'Texas'

In [33]:
texas.shape

(48096, 72)

In [34]:
texas.to_csv('texas_metro.csv',index= False)

In [35]:
texas.shape

(48096, 72)

In [36]:
texas['YEAR'].value_counts()

2019    16032
2020    16032
2021    16032
Name: YEAR, dtype: int64

In [37]:
texas.to_csv('texas_metro.csv',index= False)

In [38]:
o1 = pd.read_csv('C:/Users/karan/Oklahoma_2019_LSAD.csv')
o2 = pd.read_csv('C:/Users/karan/Oklahoma_2020_LSAD.csv')
o3 = pd.read_csv('C:/Users/karan/Oklahoma_2021_LSAD.csv')

In [39]:
o1.shape, o2.shape, o3.shape

((2196, 48), (2196, 48), (2196, 75))

In [40]:
del o1['Shape_Leng']

In [41]:
o3.columns

Index(['GISJOIN', 'STATEFP', 'COUNTYFP', 'DAYLIGHT', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN',
       'UNK_LIGHT', 'OTHER_LIGHT', 'POPN', 'CLEAR', 'CLOUDY', 'FOG', 'RAIN',
       'SLEET_HAIL', 'OTHER_WEATHER', 'UNK_Weather', 'SNOW_Weather',
       'BLOWING_SAND_SNOW', 'SEVERE_CROSSWINDS', 'INTERSTATE',
       'US_STATE_HIGHWAY', 'FARM_TO_MARKET', 'COUNTY_ROAD', 'CITY_STREET',
       'TOLLWAY', 'OTHER_ROADS', 'TOLL_BRIDGES', 'ALCOHOL', 'DRUG',
       'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
       'NO_INATTENTION', 'YES_INATTENTION', 'NO_SPD', 'YES_SPD', 'NO_INJ',
       'YES_INJ', 'INJ_COUNT_SUM', 'YEAR', 'STATE', 'NAME', 'Shape_Area', '0',
       '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8', '0.9', '0.10',
       '0.11', '0.12', '0.13', '0.14', '0.15', '0.16', '0.17', '0.18', '0.19',
       '0.20', '0.21', '0.22', '0.23', '0.24', '0.25', '0.26', '0.27'],
      dtype='object')

In [42]:
o1['YEAR'].unique()

array([2019,    0], dtype=int64)

In [43]:
o1['YEAR'] = np.where(o1['YEAR']==0,2019,o1['YEAR'])

In [44]:
o3['YEAR'] =np.where(o3['YEAR']==0,2021,o3['YEAR'])

In [45]:
o33 = o3[o1.columns]

In [46]:
o1.shape, o33.shape

((2196, 47), (2196, 47))

In [47]:
o2.columns= o2.columns.str.replace('Oklahoma_CopyFeatures_1_','')

In [48]:
o2.rename(columns={'_COUNTY_ROAD':'COUNTY_ROAD'},inplace= True)

In [49]:
o33.columns

Index(['GISJOIN', 'STATEFP', 'COUNTYFP', 'DAYLIGHT', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN',
       'UNK_LIGHT', 'OTHER_LIGHT', 'POPN', 'CLEAR', 'CLOUDY', 'FOG', 'RAIN',
       'SLEET_HAIL', 'OTHER_WEATHER', 'UNK_Weather', 'SNOW_Weather',
       'BLOWING_SAND_SNOW', 'SEVERE_CROSSWINDS', 'INTERSTATE',
       'US_STATE_HIGHWAY', 'FARM_TO_MARKET', 'COUNTY_ROAD', 'CITY_STREET',
       'TOLLWAY', 'OTHER_ROADS', 'TOLL_BRIDGES', 'ALCOHOL', 'DRUG',
       'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
       'NO_INATTENTION', 'YES_INATTENTION', 'NO_SPD', 'YES_SPD', 'NO_INJ',
       'YES_INJ', 'INJ_COUNT_SUM', 'YEAR', 'STATE', 'NAME', 'Shape_Area'],
      dtype='object')

In [50]:
o22 = o2[o33.columns]

In [51]:
o22['YEAR'].unique()

array([2020,    0], dtype=int64)

In [52]:
o22['YEAR'] = np.where(o22['YEAR']==0,2020,o22['YEAR'])

C:\Users\karan\AppData\Local\Temp\ipykernel_25652\1525507479.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o22['YEAR'] = np.where(o22['YEAR']==0,2020,o22['YEAR'])


In [53]:
o1.shape, o22.shape,o33.shape

((2196, 47), (2196, 47), (2196, 47))

In [54]:
o1['STATE_CAT'] = 2
o22['STATE_CAT'] = 2
o33['STATE_CAT'] =2

o1['YEAR_CAT'] =1
o22['YEAR_CAT'] = 2
o33['YEAR_CAT'] = 3

C:\Users\karan\AppData\Local\Temp\ipykernel_25652\1681792907.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o33['STATE_CAT'] =2
C:\Users\karan\AppData\Local\Temp\ipykernel_25652\1681792907.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  o33['YEAR_CAT'] = 3


In [55]:
o1.shape,o22.shape,o33.shape

((2196, 49), (2196, 49), (2196, 49))

In [56]:
okla = pd.concat([o1,o22,o33],axis=0)
okla['STATE'] = okla['STATE'].replace('0', 'Oklahoma')

In [57]:
okla['STATE'].unique()

array(['Oklahoma'], dtype=object)

In [58]:
okla.to_csv('okla_metro.csv',index= False)

In [59]:
okla.shape, texas.shape

((6588, 49), (48096, 72))

In [60]:
texas.columns

Index(['GISJOIN', 'STATEFP', 'Shape_Leng', 'COUNT', 'ALCOHOL', 'DRUG',
       'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
       'BLOWING_SAND_SNOW', 'CLEAR', 'CLOUDY', 'FOG', 'Other_Weather', 'RAIN',
       'SEVERE_CROSSWINDS', 'SLEET_HAIL', 'SNOW_Weather', 'UNK_Weather',
       'DAYLIGHT', 'DARK_LIGHTED', 'DARK_NOT_LIGHTED', 'DARK_UNKNOWN_LIGHTING',
       'DUSK', 'DAWN', 'UNK_LIGHT', 'OTHER_LIGHT', 'CITY_STREET',
       'COUNTY_ROAD', 'FARM_TO_MARKET', 'INTERSTATE', 'OTHER_ROADS',
       'TOLL_BRIDGES', 'TOLLWAY', 'US_STATE_HIGHWAY', 'DRY', 'ICE',
       'OTHER_SURF', 'SAND_MUD_DIRT', 'SLUSH', 'SNOW_SURF', 'STANDING_WATER',
       'UNKNOWN_SURF', 'WET', 'SPEEDING', 'INATTENTION', 'LANE_CHANGE',
       'TAILGATING', 'VIOLATION', 'UNSAFE_BACKING', 'IMPAIRMENT', 'TURNING',
       'TECH_PARK', 'NO_FAULT', 'KNOWN_HUMAN_FACTOR', 'UNKNOWN_HUMAN_FACTOR',
       'FATAL', 'MIN_INJURY', 'NO_INJURY', 'POSBL_INJURY', 'UNK_SEVERITY',
       'NO_INJ', 'YES_INJ', 'INJ_COUNT_SUM', 

In [61]:
del okla['COUNTYFP']

In [62]:
texas.columns

Index(['GISJOIN', 'STATEFP', 'Shape_Leng', 'COUNT', 'ALCOHOL', 'DRUG',
       'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
       'BLOWING_SAND_SNOW', 'CLEAR', 'CLOUDY', 'FOG', 'Other_Weather', 'RAIN',
       'SEVERE_CROSSWINDS', 'SLEET_HAIL', 'SNOW_Weather', 'UNK_Weather',
       'DAYLIGHT', 'DARK_LIGHTED', 'DARK_NOT_LIGHTED', 'DARK_UNKNOWN_LIGHTING',
       'DUSK', 'DAWN', 'UNK_LIGHT', 'OTHER_LIGHT', 'CITY_STREET',
       'COUNTY_ROAD', 'FARM_TO_MARKET', 'INTERSTATE', 'OTHER_ROADS',
       'TOLL_BRIDGES', 'TOLLWAY', 'US_STATE_HIGHWAY', 'DRY', 'ICE',
       'OTHER_SURF', 'SAND_MUD_DIRT', 'SLUSH', 'SNOW_SURF', 'STANDING_WATER',
       'UNKNOWN_SURF', 'WET', 'SPEEDING', 'INATTENTION', 'LANE_CHANGE',
       'TAILGATING', 'VIOLATION', 'UNSAFE_BACKING', 'IMPAIRMENT', 'TURNING',
       'TECH_PARK', 'NO_FAULT', 'KNOWN_HUMAN_FACTOR', 'UNKNOWN_HUMAN_FACTOR',
       'FATAL', 'MIN_INJURY', 'NO_INJURY', 'POSBL_INJURY', 'UNK_SEVERITY',
       'NO_INJ', 'YES_INJ', 'INJ_COUNT_SUM', 

In [63]:
okla.rename(columns={'OTHER_WEATHER':'Other_Weather'},inplace= True)

In [64]:
okla.rename(columns={'YES_SPD':'SPEEDING','YES_INATTENTION':'INATTENTION'},inplace= True)

In [65]:
okla.columns

Index(['GISJOIN', 'STATEFP', 'DAYLIGHT', 'DARK_LIGHTED', 'DARK_NOT_LIGHTED',
       'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN', 'UNK_LIGHT', 'OTHER_LIGHT',
       'POPN', 'CLEAR', 'CLOUDY', 'FOG', 'RAIN', 'SLEET_HAIL', 'Other_Weather',
       'UNK_Weather', 'SNOW_Weather', 'BLOWING_SAND_SNOW', 'SEVERE_CROSSWINDS',
       'INTERSTATE', 'US_STATE_HIGHWAY', 'FARM_TO_MARKET', 'COUNTY_ROAD',
       'CITY_STREET', 'TOLLWAY', 'OTHER_ROADS', 'TOLL_BRIDGES', 'ALCOHOL',
       'DRUG', 'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
       'NO_INATTENTION', 'INATTENTION', 'NO_SPD', 'SPEEDING', 'NO_INJ',
       'YES_INJ', 'INJ_COUNT_SUM', 'YEAR', 'STATE', 'NAME', 'Shape_Area',
       'STATE_CAT', 'YEAR_CAT'],
      dtype='object')

In [66]:
www = ['GISJOIN', 'STATEFP', 'DAYLIGHT', 'DARK_LIGHTED', 'DARK_NOT_LIGHTED',
       'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN', 'UNK_LIGHT', 'OTHER_LIGHT',
       'POPN', 'CLEAR', 'CLOUDY', 'FOG', 'RAIN', 'SLEET_HAIL', 'Other_Weather',
       'UNK_Weather', 'SNOW_Weather', 'BLOWING_SAND_SNOW', 'SEVERE_CROSSWINDS',
       'INTERSTATE', 'US_STATE_HIGHWAY', 'FARM_TO_MARKET', 'COUNTY_ROAD',
       'CITY_STREET', 'TOLLWAY', 'OTHER_ROADS', 'TOLL_BRIDGES', 'ALCOHOL',
       'DRUG', 'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
       'INATTENTION',  'SPEEDING', 'NO_INJ',
       'YES_INJ', 'INJ_COUNT_SUM', 'YEAR', 'STATE', 'NAME', 'Shape_Area',
       'STATE_CAT', 'YEAR_CAT']

In [67]:
tt = texas[www]

In [68]:
ok = okla[www]

In [69]:
to = pd.concat([tt,ok],axis=0)

In [70]:
to.isna().sum().sum()

0

In [71]:
txokla = to

In [72]:
txokla

GISJOIN  STATEFP   DAYLIGHT  DARK_LIGHTED  DARK_NOT_LIGHTED  \
0     G48000900201001       48  50.000000      0.000000         50.000000   
1     G48000900201002       48  59.259259      0.000000         40.740741   
2     G48000900202001       48  51.515152      6.060606         30.303030   
3     G48000900202002       48   0.000000      0.000000        100.000000   
4     G48000900202003       48  66.666667      0.000000         33.333333   
...               ...      ...        ...           ...               ...   
2191  G40014500307981       40   0.000000      0.000000          0.000000   
2192  G40014500307982       40   0.000000      0.000000          0.000000   
2193  G40014500307983       40   0.000000      0.000000          0.000000   
2194  G40014500308001       40   0.000000      0.000000          0.000000   
2195  G40014500308002       40   0.000000      0.000000          0.000000   

      DARK_UNKNOWN_LIGHTING  DUSK       DAWN  UNK_LIGHT  OTHER_LIGHT  ...  \
0                       0.0   0.0   0.000000        0.0          0.0  ...   
1                       0.0   0.0   0.000000        0.0          0.0  ...   
2                       0.0   0.0  12.121212        0.0          0.0  ...   
3                       0.0   0.0   0.000000        0.0          0.0  ...   
4                       0.0   0.0   0.000000        0.0          0.0  ...   
...                     ...   ...        ...        ...          ...  ...   
2191                    0.0   0.0   0.000000        0.0          0.0  ...   
2192                    0.0   0.0   0.000000        0.0          0.0  ...   
2193                    0.0   0.0   0.000000        0.0          0.0  ...   
2194                    0.0   0.0   0.000000        0.0          0.0  ...   
2195                    0.0   0.0   0.000000        0.0          0.0  ...   

       SPEEDING      NO_INJ    YES_INJ  INJ_COUNT_SUM  YEAR     STATE  \
0      0.000000  100.000000   0.000000              0  2019     Texas   
1      3.703704   55.555556  44.444444             13  2019     Texas   
2      3.030303   66.666667  33.333333             15  2019     Texas   
3     50.000000   50.000000  50.000000              2  2019     Texas   
4      0.000000   66.666667  33.333333              1  2019     Texas   
...         ...         ...        ...            ...   ...       ...   
2191   0.000000    0.000000   0.000000              0  2021  Oklahoma   
2192   0.000000    0.000000   0.000000              0  2021  Oklahoma   
2193   0.000000    0.000000   0.000000              0  2021  Oklahoma   
2194   0.000000    0.000000   0.000000              0  2021  Oklahoma   
2195   0.000000    0.000000   0.000000              0  2021  Oklahoma   

                   NAME    Shape_Area  STATE_CAT  YEAR_CAT  
0     Wichita Falls, TX  1.666707e+07          1         1  
1     Wichita Falls, TX  1.667774e+08          1         1  
2     Wichita Falls, TX  1.316214e+09          1         1  
3     Wichita Falls, TX  2.697749e+07          1         1  
4     Wichita Falls, TX  1.621930e+07          1         1  
...                 ...           ...        ...       ...  
2191          Tulsa, OK  1.704119e+08          2         3  
2192          Tulsa, OK  8.900419e+06          2         3  
2193          Tulsa, OK  1.398283e+08          2         3  
2194          Tulsa, OK  1.538469e+08          2         3  
2195          Tulsa, OK  6.596828e+07          2         3  

[54684 rows x 46 columns]

In [73]:
c2 = pd.read_csv('C:/Users/karan/Colorado_2020_LSAD.csv')
c3 = pd.read_csv('C:/Users/karan/Colorado_2021_LSAD.csv')

In [74]:
c1 = pd.read_csv('C:/Users/karan/colo_2019_LSAD (1).csv')

In [75]:
c1.isna().sum()

GISJOIN                          0
STATEFP                          0
POPN                             0
DATE                             0
INTOXICATION                     0
colorado_19_1_csv_COUNTY_FIPS    0
COUNTY                           0
YEAR                             0
INJURY_COUNT                     0
INJURY_OUTCOME                   0
BLOWING_SAND_SNOW_COUNT          0
CLEAR_COUNT                      0
CLOUDY_COUNT                     0
FOG_COUNT                        0
OTHER_WEATHER_COUNT              0
RAIN_COUNT                       0
SEVERE_CROSSWINDS                0
SLEET_HAIL                       0
SNOW_WEATHER                     0
DARK_LIGHTED                     0
DARK_NOT_LIGHTED                 0
DAWN                             0
DAYLIGHT                         0
DUSK                             0
UNKNOWN_LIGHT                    0
DARK_UNKNOWN_LIGHTING            0
OTHER_LIGHT                      0
CITY_STREET                      0
COUNTY_ROAD         

In [76]:
c2.isna().sum().sum()

0

In [77]:
c3.isna().sum().sum()

0

In [78]:
c1.shape, c2.shape, c3.shape

((3455, 49), (3455, 101), (3455, 48))

In [79]:
c1.columns

Index(['GISJOIN', 'STATEFP', 'POPN', 'DATE', 'INTOXICATION',
       'colorado_19_1_csv_COUNTY_FIPS', 'COUNTY', 'YEAR', 'INJURY_COUNT',
       'INJURY_OUTCOME', 'BLOWING_SAND_SNOW_COUNT', 'CLEAR_COUNT',
       'CLOUDY_COUNT', 'FOG_COUNT', 'OTHER_WEATHER_COUNT', 'RAIN_COUNT',
       'SEVERE_CROSSWINDS', 'SLEET_HAIL', 'SNOW_WEATHER', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DAWN', 'DAYLIGHT', 'DUSK', 'UNKNOWN_LIGHT',
       'DARK_UNKNOWN_LIGHTING', 'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD',
       'INTERSTATE', 'OTHER_ROADS', 'US_STATE_HIGHWAY', 'IMPAIRMENT',
       'INATTENTION', 'KNOWN_HUMAN_FACTOR', 'LANE_CHNG', 'NO_FAULT',
       'SPEEDING', 'TAILGATING', 'TECH_PARK', 'TURNING',
       'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION',
       'INJURY_COUNT_SUM', 'NO_INJURY_OUTCOME', 'YES_INJURY_OUTCOME', 'NAME',
       'Shape_Area'],
      dtype='object')

In [80]:
c2.drop(columns=['0.43', '0.44', '0.45', '0.46', '0.47', '0.48', '0.49', '0.50', '0.51',
       '0.52'],inplace= True)

In [81]:
c2.drop(columns=['0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7',
       '0.8', '0.9', '0.10', '0.11', '0.12', '0.13', '0.14', '0.15', '0.16',
       '0.17', '0.18', '0.19', '0.20', '0.21', '0.22', '0.23', '0.24', '0.25',
       '0.26', '0.27', '0.28', '0.29', '0.30', '0.31', '0.32', '0.33', '0.34',
       '0.35', '0.36', '0.37', '0.38', '0.39', '0.40', '0.41', '0.42'],inplace= True)

In [82]:
c2.columns

Index(['GISJOIN', 'STATEFP', 'POPN', 'INTOXICATION',
       'colorado_20_1_csv_COUNTY_FIPS', 'COUNTY', 'YEAR', 'INJURY_COUNT',
       'INJURY_OUTCOME', 'BLOWING_SAND_SNOW_COUNT', 'CLEAR_COUNT',
       'CLOUDY_COUNT', 'FOG_COUNT', 'OTHER_WEATHER_COUNT', 'RAIN_COUNT',
       'SEVERE_CROSSWINDS_COUNT', 'SLEET_HAIL_COUNT', 'SNOW_WEATHER_COUNT',
       'DARK_LIGHTED', 'DARK_NOT_LIGHTED', 'DAWN', 'DAYLIGHT', 'DUSK',
       'UNKNOWN_LIGHT', 'DARK_UNKNOWN_LIGHTING', 'OTHER_LIGHT', 'CITY_STREET',
       'COUNTY_ROAD', 'INTERSTATE', 'OTHER_ROADS', 'US_STATE_HIGHWAY',
       'IMPAIRMENT', 'INATTENTION', 'KNOWN_HUMAN_FACTOR', 'LANE_CHNG',
       'NO_FAULT', 'SPEEDING', 'TAILGATING', 'TECH_PARK', 'TURNING',
       'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION',
       'INJURY_COUNT_SUM', 'NO_INJURY_OUTCOME', 'YES_INJURY_OUTCOME', 'NAME',
       'Shape_Area'],
      dtype='object')

In [83]:
c1.columns

Index(['GISJOIN', 'STATEFP', 'POPN', 'DATE', 'INTOXICATION',
       'colorado_19_1_csv_COUNTY_FIPS', 'COUNTY', 'YEAR', 'INJURY_COUNT',
       'INJURY_OUTCOME', 'BLOWING_SAND_SNOW_COUNT', 'CLEAR_COUNT',
       'CLOUDY_COUNT', 'FOG_COUNT', 'OTHER_WEATHER_COUNT', 'RAIN_COUNT',
       'SEVERE_CROSSWINDS', 'SLEET_HAIL', 'SNOW_WEATHER', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DAWN', 'DAYLIGHT', 'DUSK', 'UNKNOWN_LIGHT',
       'DARK_UNKNOWN_LIGHTING', 'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD',
       'INTERSTATE', 'OTHER_ROADS', 'US_STATE_HIGHWAY', 'IMPAIRMENT',
       'INATTENTION', 'KNOWN_HUMAN_FACTOR', 'LANE_CHNG', 'NO_FAULT',
       'SPEEDING', 'TAILGATING', 'TECH_PARK', 'TURNING',
       'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION',
       'INJURY_COUNT_SUM', 'NO_INJURY_OUTCOME', 'YES_INJURY_OUTCOME', 'NAME',
       'Shape_Area'],
      dtype='object')

In [84]:
c1['INTOXICATION'] = c1['INTOXICATION'].fillna(4)

In [85]:
c1['INTOXICATION'] = c1['INTOXICATION'].astype(int)

In [86]:
c1['INTOXICATION'].unique()

array([4, 2, 1, 0, 5, 3])

In [87]:
c2['INTOXICATION'].unique()

array([4, 1, 5, 0, 3], dtype=int64)

In [88]:
c3['INTOXICATION'].unique()

array([4, 1, 0, 6], dtype=int64)

In [89]:
c1.rename(columns={'NO_INJURY_OUTCOME':'NO_INJURY','YES_INJURY_OUTCOME':'YES_INJURY'},inplace= True)

In [90]:
c2.rename(columns={'NO_INJURY_OUTCOME':'NO_INJURY','YES_INJURY_OUTCOME':'YES_INJURY'},inplace= True)

In [91]:
c3.columns

Index(['Colorado_CopyFeatures2_GISJOIN', 'STATEFP', 'POPN', 'INTOXICATION',
       'COUNTY_FIPS', 'COUNTY', 'YEAR', 'INJURY_COUNT', 'INJURY_OUTCOME',
       'BLOWING_SAND_SNOW_COUNT', 'CLEAR_COUNT', 'CLOUDY_COUNT', 'FOG_COUNT',
       'OTHER_WEATHER_COUNT', 'RAIN_COUNT', 'SEVERE_CROSSWINDS_COUNT',
       'SLEET_HAIL_COUNT', 'SNOW_WEATHER_COUNT', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DAWN', 'DAYLIGHT', 'DUSK', 'UNKNOWN_LIGHT',
       'DARK_UNKNOWN_LIGHTING', 'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD',
       'INTERSTATE', 'OTHER_ROADS', 'US_STATE_HIGHWAY', 'IMPAIRMENT',
       'INATTENTION', 'KNOWN_HUMAN_FACTOR', 'LANE_CHNG', 'NO_FAULT',
       'SPEEDING', 'TAILGATING', 'TECH_PARK_', 'TURNING',
       'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION',
       'INJURY_COUNT_SUM', 'NO_INJURY', 'YES_INJURY', 'NAME', 'Shape_Area'],
      dtype='object')

In [92]:
c3.columns = c3.columns.str.replace('Colorado_CopyFeatures2_','')

In [93]:
intoxication_mapping = {
    1: 'ALCOHOL',
    2: 'DRUG',
    3: 'ALCOHOL, DRUG',
    4: 'NO INTOXICATION',
    5: 'MEDICINAL',
    6: 'MARIJUANA'
}



def process_intoxication_data(df, mapping):
    # Map the intoxication codes to descriptive names
    df['INTOXICATION_DESC'] = df['INTOXICATION'].map(mapping).astype(str)
    
    all_categories = list(mapping.values())
    
    # Group by COUNTY and INTOXICATION_DESC, then count occurrences
    grouped = df.groupby(['GISJOIN', 'INTOXICATION_DESC']).size().unstack(fill_value=0)
    grouped = grouped.reindex(columns=all_categories, fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)
    
    # Calculate percentages
    intoxication_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    intoxication_percentages_df = intoxication_percentages_df.reset_index()
    
    return intoxication_percentages_df

# Process each year's data
intoxication_df_2019 = process_intoxication_data(c1, intoxication_mapping)
intoxication_df_2020 = process_intoxication_data(c2, intoxication_mapping)
intoxication_df_2021 = process_intoxication_data(c3, intoxication_mapping)



In [94]:
intoxication_df_2019.shape, intoxication_df_2020.shape, intoxication_df_2021.shape

((3455, 7), (3455, 7), (3455, 7))

In [95]:
c1 = pd.merge(c1,intoxication_df_2019,on=['GISJOIN'],how='left')
c2 = pd.merge(c2,intoxication_df_2020,on=['GISJOIN'],how='left')
c3 = pd.merge(c3,intoxication_df_2021,on=['GISJOIN'],how='left')

In [96]:
c1['YEAR'].unique()

array([2019,    0], dtype=int64)

In [97]:
c1['YEAR'] = np.where(c1['YEAR']==0,2019,c1['YEAR'])

In [98]:
c2['YEAR'] = np.where(c2['YEAR']==0,2020,c2['YEAR'])

In [99]:
c3['YEAR'] = np.where(c3['YEAR']==0,2021,c3['YEAR'])

In [100]:
c1.columns

Index(['GISJOIN', 'STATEFP', 'POPN', 'DATE', 'INTOXICATION',
       'colorado_19_1_csv_COUNTY_FIPS', 'COUNTY', 'YEAR', 'INJURY_COUNT',
       'INJURY_OUTCOME', 'BLOWING_SAND_SNOW_COUNT', 'CLEAR_COUNT',
       'CLOUDY_COUNT', 'FOG_COUNT', 'OTHER_WEATHER_COUNT', 'RAIN_COUNT',
       'SEVERE_CROSSWINDS', 'SLEET_HAIL', 'SNOW_WEATHER', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DAWN', 'DAYLIGHT', 'DUSK', 'UNKNOWN_LIGHT',
       'DARK_UNKNOWN_LIGHTING', 'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD',
       'INTERSTATE', 'OTHER_ROADS', 'US_STATE_HIGHWAY', 'IMPAIRMENT',
       'INATTENTION', 'KNOWN_HUMAN_FACTOR', 'LANE_CHNG', 'NO_FAULT',
       'SPEEDING', 'TAILGATING', 'TECH_PARK', 'TURNING',
       'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION',
       'INJURY_COUNT_SUM', 'NO_INJURY', 'YES_INJURY', 'NAME', 'Shape_Area',
       'INTOXICATION_DESC', 'ALCOHOL', 'DRUG', 'ALCOHOL, DRUG',
       'NO INTOXICATION', 'MEDICINAL', 'MARIJUANA'],
      dtype='object')

In [101]:
colo19 = pd.read_csv('C:/Users/karan/colo_2019.csv')
colo20 = pd.read_csv('C:/Users/karan/colo_2020.csv')
colo21 = pd.read_csv('C:/Users/karan/col_2021.csv')

In [102]:
colo19.isna().sum().sum()

0

In [103]:
colo20.isna().sum().sum()

0

In [104]:
colo21.isna().sum().sum()

0

In [105]:
for i in colo19.columns:
    print(i)

FID_Colorado_CopyFeatures_csv
Colorado_CopyFeatures_GISJOIN
Colorado_CopyFeatures_STATEFP
Colorado_CopyFeatures_COUNTYFP
Colorado_CopyFeatures_TRACTCE
Colorado_CopyFeatures_BLKGRPCE
Colorado_CopyFeatures_GEOID
Colorado_CopyFeatures_NAMELSAD
Colorado_CopyFeatures_MTFCC
Colorado_CopyFeatures_FUNCSTAT
Colorado_CopyFeatures_ALAND
Colorado_CopyFeatures_AWATER
Colorado_CopyFeatures_INTPTLAT
Colorado_CopyFeatures_INTPTLON
Colorado_CopyFeatures_Shape_Leng
colorado_19_1_csv_GISJOIN
colorado_19_1_csv_STATEFP
colorado_19_1_csv_TRACTCE
colorado_19_1_csv_Colorado_Population_csv_AMPVE001
colorado_19_1_csv_BUFFER
colorado_19_1_csv_ROAD_CLASS
colorado_19_1_csv_DATE
colorado_19_1_csv_INTERSECTION
colorado_19_1_csv_CONTOUR
colorado_19_1_csv_SURFACE
colorado_19_1_csv_LIGHTING
colorado_19_1_csv_WEATHER
colorado_19_1_csv_HUMAN_FACTOR
colorado_19_1_csv_INTOXICATION
colorado_19_1_csv_AGE
colorado_19_1_csv_GENDER
colorado_19_1_csv_COUNTY_FIPS
colorado_19_1_csv_COUNTY
colorado_19_1_csv_LATITUDE
colorado_19_1_c

In [106]:
del colo19['colorado_19_1_csv_GISJOIN']

In [107]:
del colo19['GISJOIN']

In [108]:
colo19.columns = colo19.columns.str.replace('colorado_19_1_csv_','')

In [109]:
colo19.columns = colo19.columns.str.replace('Colorado_CopyFeatures_','')

In [110]:
for i in colo20.columns:
    print(i)

FID_Colorado_CopyFeatures1_csv
Colorado_CopyFeatures1_GISJOIN
Colorado_CopyFeatures1_STATEFP
Colorado_CopyFeatures1_COUNTYFP
Colorado_CopyFeatures1_TRACTCE
Colorado_CopyFeatures1_BLKGRPCE
Colorado_CopyFeatures1_GEOID
Colorado_CopyFeatures1_NAMELSAD
Colorado_CopyFeatures1_MTFCC
Colorado_CopyFeatures1_FUNCSTAT
Colorado_CopyFeatures1_ALAND
Colorado_CopyFeatures1_AWATER
Colorado_CopyFeatures1_INTPTLAT
Colorado_CopyFeatures1_INTPTLON
Colorado_CopyFeatures1_Shape_Leng
colorado_20_1_csv_GISJOIN
colorado_20_1_csv_STATEFP
colorado_20_1_csv_TRACTCE
colorado_20_1_csv_Colorado_Population_csv_AMPVE001
colorado_20_1_csv_BUFFER
colorado_20_1_csv_ROAD_CLASS
colorado_20_1_csv_DATE
colorado_20_1_csv_INTERSECTION
colorado_20_1_csv_CONTOUR
colorado_20_1_csv_SURFACE
colorado_20_1_csv_LIGHTING
colorado_20_1_csv_WEATHER
colorado_20_1_csv_HUMAN_FACTOR
colorado_20_1_csv_INTOXICATION
colorado_20_1_csv_AGE
colorado_20_1_csv_GENDER
colorado_20_1_csv_COUNTY_FIPS
colorado_20_1_csv_COUNTY
colorado_20_1_csv_LATITUDE


In [111]:
del colo20['colorado_20_1_csv_GISJOIN']

In [112]:
del colo20['GISJOIN']

In [113]:
colo20.columns = colo20.columns.str.replace('Colorado_CopyFeatures1_','')

In [114]:
colo20.columns = colo20.columns.str.replace('_COUNT','')

In [115]:
colo20.columns= colo20.columns.str.replace('colorado_20_1_csv_','')

In [116]:
for i in colo21.columns:
    print(i)

FID_Colorado_CopyFeatures2_csv
Colorado_CopyFeatures2_GISJOIN
Colorado_CopyFeatures2_STATEFP
Colorado_CopyFeatures2_COUNTYFP
Colorado_CopyFeatures2_TRACTCE
Colorado_CopyFeatures2_BLKGRPCE
Colorado_CopyFeatures2_GEOID
Colorado_CopyFeatures2_NAMELSAD
Colorado_CopyFeatures2_MTFCC
Colorado_CopyFeatures2_FUNCSTAT
Colorado_CopyFeatures2_ALAND
Colorado_CopyFeatures2_AWATER
Colorado_CopyFeatures2_INTPTLAT
Colorado_CopyFeatures2_INTPTLON
Colorado_CopyFeatures2_Shape_Leng
colorado_21_1_csv_GISJOIN
colorado_21_1_csv_STATEFP
colorado_21_1_csv_TRACTCE
colorado_21_1_csv_Colorado_Population_csv_AMPVE001
colorado_21_1_csv_BUFFER
colorado_21_1_csv_ROAD_CLASS
colorado_21_1_csv_DATE
colorado_21_1_csv_INTERSECTION
colorado_21_1_csv_CONTOUR
colorado_21_1_csv_SURFACE
colorado_21_1_csv_LIGHTING
colorado_21_1_csv_WEATHER
colorado_21_1_csv_HUMAN_FACTOR
colorado_21_1_csv_INTOXICATION
colorado_21_1_csv_AGE
colorado_21_1_csv_GENDER
colorado_21_1_csv_COUNTY_FIPS
colorado_21_1_csv_COUNTY
colorado_21_1_csv_LATITUDE


In [117]:
del colo21['colorado_21_1_csv_GISJOIN']

In [118]:
del colo21['GISJOIN']

In [119]:
colo21.columns = colo21.columns.str.replace('Colorado_CopyFeatures2_','')

In [120]:
colo21.columns = colo21.columns.str.replace('colorado_21_1_csv_','')

In [121]:
colo21.columns = colo21.columns.str.replace('_COUNT','')

In [122]:
col19 = colo19[['GISJOIN','WEATHER']]
col19

GISJOIN  WEATHER
0     G08000100078011        8
1     G08000100078012        8
2     G08000100078021        8
3     G08000100078022        4
4     G08000100078023        8
...               ...      ...
3450  G08012300025021        4
3451  G08012300025022        8
3452  G08012300025023        8
3453  G08012300025024        8
3454  G08012300025025        7

[3455 rows x 2 columns]

In [123]:
for i in colo19.columns:
    print(i)

FID_csv
GISJOIN
STATEFP
COUNTYFP
TRACTCE
BLKGRPCE
GEOID
NAMELSAD
MTFCC
FUNCSTAT
ALAND
AWATER
INTPTLAT
INTPTLON
Shape_Leng
STATEFP
TRACTCE
Colorado_Population_csv_AMPVE001
BUFFER
ROAD_CLASS
DATE
INTERSECTION
CONTOUR
SURFACE
LIGHTING
WEATHER
HUMAN_FACTOR
INTOXICATION
AGE
GENDER
COUNTY_FIPS
COUNTY
LATITUDE
LONGITUDE
YEAR
INJURY_COUNT
INJURY_OUTCOME
Crash_ID
BUFF_DIST
ORIG_FID
Shape_Length
Shape_Area
WEATHER_DESC
BLOWING_SAND_SNOW_COUNT
CLEAR_COUNT
CLOUDY_COUNT
FOG_COUNT
OTHER_WEATHER_COUNT
RAIN_COUNT
SEVERE_CROSSWINDS_COUNT
SLEET_HAIL_COUNT
SNOW_WEATHER_COUNT
LIGHTING_DESC
DARK_LIGHTED_PERCENTAGE
DARK_NOT_LIGHTED_PERCENTAGE
DAWN_PERCENTAGE
DAYLIGHT_PERCENTAGE
DUSK_PERCENTAGE
UNKNOWN_LIGHT_PERCENTAGE
DARK_UNKNOWN_LIGHTING_PERCENTAGE
OTHER_LIGHT_PERCENTAGE
SURFACE_DESC
DIRT_PERCENTAGE
DRY_PERCENTAGE
ICE_PERCENTAGE
SLUSH_PERCENTAGE
SNOW_SURF_PERCENTAGE
UNKNOWN_SURF_PERCENTAGE
WET_PERCENTAGE
STANDING_WATER_PERCENTAGE
OTHER_SURF_PERCENTAGE
INTERSECTION_DESC
NO_INTERSECTION_PERCENTAGE
YES_INTER

In [124]:
col20 = colo20[['GISJOIN','WEATHER']]
col20

GISJOIN  WEATHER
0     G08000100078011        4
1     G08000100078012        8
2     G08000100078021        8
3     G08000100078022        8
4     G08000100078023        8
...               ...      ...
3450  G08012300025021        8
3451  G08012300025022        8
3452  G08012300025023        2
3453  G08012300025024        8
3454  G08012300025025        8

[3455 rows x 2 columns]

In [125]:
col21 = colo21[['GISJOIN','WEATHER']]
col21

GISJOIN  WEATHER
0     G08000100078011       11
1     G08000100078012       11
2     G08000100078021        0
3     G08000100078022        0
4     G08000100078023        0
...               ...      ...
3450  G08012300025021       11
3451  G08012300025022       11
3452  G08012300025023       11
3453  G08012300025024       11
3454  G08012300025025        3

[3455 rows x 2 columns]

In [126]:
c1.columns

Index(['GISJOIN', 'STATEFP', 'POPN', 'DATE', 'INTOXICATION',
       'colorado_19_1_csv_COUNTY_FIPS', 'COUNTY', 'YEAR', 'INJURY_COUNT',
       'INJURY_OUTCOME', 'BLOWING_SAND_SNOW_COUNT', 'CLEAR_COUNT',
       'CLOUDY_COUNT', 'FOG_COUNT', 'OTHER_WEATHER_COUNT', 'RAIN_COUNT',
       'SEVERE_CROSSWINDS', 'SLEET_HAIL', 'SNOW_WEATHER', 'DARK_LIGHTED',
       'DARK_NOT_LIGHTED', 'DAWN', 'DAYLIGHT', 'DUSK', 'UNKNOWN_LIGHT',
       'DARK_UNKNOWN_LIGHTING', 'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD',
       'INTERSTATE', 'OTHER_ROADS', 'US_STATE_HIGHWAY', 'IMPAIRMENT',
       'INATTENTION', 'KNOWN_HUMAN_FACTOR', 'LANE_CHNG', 'NO_FAULT',
       'SPEEDING', 'TAILGATING', 'TECH_PARK', 'TURNING',
       'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION',
       'INJURY_COUNT_SUM', 'NO_INJURY', 'YES_INJURY', 'NAME', 'Shape_Area',
       'INTOXICATION_DESC', 'ALCOHOL', 'DRUG', 'ALCOHOL, DRUG',
       'NO INTOXICATION', 'MEDICINAL', 'MARIJUANA'],
      dtype='object')

In [127]:
c1.drop(columns=['BLOWING_SAND_SNOW_COUNT', 'CLEAR_COUNT',
       'CLOUDY_COUNT', 'FOG_COUNT', 'OTHER_WEATHER_COUNT', 'RAIN_COUNT',
       'SEVERE_CROSSWINDS', 'SLEET_HAIL', 'SNOW_WEATHER'],inplace= True)

In [128]:
c2.columns

Index(['GISJOIN', 'STATEFP', 'POPN', 'INTOXICATION',
       'colorado_20_1_csv_COUNTY_FIPS', 'COUNTY', 'YEAR', 'INJURY_COUNT',
       'INJURY_OUTCOME', 'BLOWING_SAND_SNOW_COUNT', 'CLEAR_COUNT',
       'CLOUDY_COUNT', 'FOG_COUNT', 'OTHER_WEATHER_COUNT', 'RAIN_COUNT',
       'SEVERE_CROSSWINDS_COUNT', 'SLEET_HAIL_COUNT', 'SNOW_WEATHER_COUNT',
       'DARK_LIGHTED', 'DARK_NOT_LIGHTED', 'DAWN', 'DAYLIGHT', 'DUSK',
       'UNKNOWN_LIGHT', 'DARK_UNKNOWN_LIGHTING', 'OTHER_LIGHT', 'CITY_STREET',
       'COUNTY_ROAD', 'INTERSTATE', 'OTHER_ROADS', 'US_STATE_HIGHWAY',
       'IMPAIRMENT', 'INATTENTION', 'KNOWN_HUMAN_FACTOR', 'LANE_CHNG',
       'NO_FAULT', 'SPEEDING', 'TAILGATING', 'TECH_PARK', 'TURNING',
       'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION',
       'INJURY_COUNT_SUM', 'NO_INJURY', 'YES_INJURY', 'NAME', 'Shape_Area',
       'INTOXICATION_DESC', 'ALCOHOL', 'DRUG', 'ALCOHOL, DRUG',
       'NO INTOXICATION', 'MEDICINAL', 'MARIJUANA'],
      dtype='object')

In [129]:
c2.drop(columns=['BLOWING_SAND_SNOW_COUNT', 'CLEAR_COUNT',
       'CLOUDY_COUNT', 'FOG_COUNT', 'OTHER_WEATHER_COUNT', 'RAIN_COUNT',
       'SEVERE_CROSSWINDS_COUNT', 'SLEET_HAIL_COUNT', 'SNOW_WEATHER_COUNT'],inplace= True)

In [130]:
c3.columns

Index(['GISJOIN', 'STATEFP', 'POPN', 'INTOXICATION', 'COUNTY_FIPS', 'COUNTY',
       'YEAR', 'INJURY_COUNT', 'INJURY_OUTCOME', 'BLOWING_SAND_SNOW_COUNT',
       'CLEAR_COUNT', 'CLOUDY_COUNT', 'FOG_COUNT', 'OTHER_WEATHER_COUNT',
       'RAIN_COUNT', 'SEVERE_CROSSWINDS_COUNT', 'SLEET_HAIL_COUNT',
       'SNOW_WEATHER_COUNT', 'DARK_LIGHTED', 'DARK_NOT_LIGHTED', 'DAWN',
       'DAYLIGHT', 'DUSK', 'UNKNOWN_LIGHT', 'DARK_UNKNOWN_LIGHTING',
       'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD', 'INTERSTATE',
       'OTHER_ROADS', 'US_STATE_HIGHWAY', 'IMPAIRMENT', 'INATTENTION',
       'KNOWN_HUMAN_FACTOR', 'LANE_CHNG', 'NO_FAULT', 'SPEEDING', 'TAILGATING',
       'TECH_PARK_', 'TURNING', 'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING',
       'VIOLATION', 'INJURY_COUNT_SUM', 'NO_INJURY', 'YES_INJURY', 'NAME',
       'Shape_Area', 'INTOXICATION_DESC', 'ALCOHOL', 'DRUG', 'ALCOHOL, DRUG',
       'NO INTOXICATION', 'MEDICINAL', 'MARIJUANA'],
      dtype='object')

In [131]:
c3.drop(columns=['BLOWING_SAND_SNOW_COUNT',
       'CLEAR_COUNT', 'CLOUDY_COUNT', 'FOG_COUNT', 'OTHER_WEATHER_COUNT',
       'RAIN_COUNT', 'SEVERE_CROSSWINDS_COUNT', 'SLEET_HAIL_COUNT',
       'SNOW_WEATHER_COUNT'],inplace= True)

In [132]:
col21.columns

Index(['GISJOIN', 'WEATHER'], dtype='object')

In [133]:
c1= pd.merge(c1,col19,on=['GISJOIN'],how='left')
c2 = pd.merge(c2,col20,on=['GISJOIN'],how='left')
c3 = pd.merge(c3,col21,on=['GISJOIN'],how='left')

In [134]:
c1.isna().sum().sum()

0

In [135]:
c1['WEATHER'].unique()

array([8, 4, 2, 0, 5, 7], dtype=int64)

In [136]:
c2['WEATHER'].unique()

array([4, 8, 0, 5, 7, 2], dtype=int64)

In [137]:
c3['WEATHER'].unique()

array([11,  0,  2,  4,  3, 12,  7,  5,  6], dtype=int64)

In [138]:
weather_mapping = {
    11: 'CLEAR',
    12: 'CLOUDY',
    5: 'FOG',
    2: 'RAIN',
    3: 'SLEET/HAIL',
    8: 'OTHER_WEATHER',
    0: 'UNKNOWN_WEATHER',
    4: 'SNOW_WEATHER',
    6: 'BLOWING SAND/SNOW',
    7: 'SEVERE CROSSWINDS'
}


def process_intoxication_data(df, mapping):
    # Map the intoxication codes to descriptive names
    df['WEATHER_DESC'] = df['WEATHER'].map(weather_mapping).astype(str)

    # Create a list of all possible intoxication categories
    all_categories = list(mapping.values())

    # Group by COUNTY and INTOXICATION_DESC, then count occurrences
    grouped = df.groupby(['GISJOIN', 'WEATHER_DESC']).size().unstack(fill_value=0)

    # Reindex the DataFrame to include all possible intoxication categories
    grouped = grouped.reindex(columns=all_categories, fill_value=0)

    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)

    # Calculate percentages
    w_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    w_df = w_df.reset_index(drop=False)

    return w_df


w19 = process_intoxication_data(c1,weather_mapping)
w20 = process_intoxication_data(c2,weather_mapping)
w21 = process_intoxication_data(c3,weather_mapping)

In [139]:
c1 = pd.merge(c1,w19,on=['GISJOIN'],how='left')
c2 = pd.merge(c2,w20,on=['GISJOIN'],how='left')
c3 = pd.merge(c3,w21,on=['GISJOIN'],how='left')

In [140]:
c1['STATE'] = 'Colorado'
c2['STATE'] = 'Colorado'
c3['STATE'] = 'Colorado'

In [141]:
c1['YEAR_CAT'] = 1
c2['YEAR_CAT'] = 2
c3['YEAR_CAT'] = 3

In [142]:
c1.shape, c2.shape, c3.shape

((3455, 61), (3455, 60), (3455, 60))

In [143]:
del c1['DATE']

In [144]:
c1.isna().sum().sum()

0

In [145]:
cold = pd.concat([c1,c2,c3],axis=0)

In [146]:
c1.shape,c2.shape,c3.shape


((3455, 60), (3455, 60), (3455, 60))

In [147]:
cold.shape

(10365, 63)

In [148]:
cold['STATE_CAT'] = 3

In [149]:
cold.columns

Index(['GISJOIN', 'STATEFP', 'POPN', 'INTOXICATION',
       'colorado_19_1_csv_COUNTY_FIPS', 'COUNTY', 'YEAR', 'INJURY_COUNT',
       'INJURY_OUTCOME', 'DARK_LIGHTED', 'DARK_NOT_LIGHTED', 'DAWN',
       'DAYLIGHT', 'DUSK', 'UNKNOWN_LIGHT', 'DARK_UNKNOWN_LIGHTING',
       'OTHER_LIGHT', 'CITY_STREET', 'COUNTY_ROAD', 'INTERSTATE',
       'OTHER_ROADS', 'US_STATE_HIGHWAY', 'IMPAIRMENT', 'INATTENTION',
       'KNOWN_HUMAN_FACTOR', 'LANE_CHNG', 'NO_FAULT', 'SPEEDING', 'TAILGATING',
       'TECH_PARK', 'TURNING', 'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING',
       'VIOLATION', 'INJURY_COUNT_SUM', 'NO_INJURY', 'YES_INJURY', 'NAME',
       'Shape_Area', 'INTOXICATION_DESC', 'ALCOHOL', 'DRUG', 'ALCOHOL, DRUG',
       'NO INTOXICATION', 'MEDICINAL', 'MARIJUANA', 'WEATHER', 'WEATHER_DESC',
       'CLEAR', 'CLOUDY', 'FOG', 'RAIN', 'SLEET/HAIL', 'OTHER_WEATHER',
       'UNKNOWN_WEATHER', 'SNOW_WEATHER', 'BLOWING SAND/SNOW',
       'SEVERE CROSSWINDS', 'STATE', 'YEAR_CAT',
       'colorado_20_1_csv_COU

In [150]:
txokla.isna().sum().sum()

0

In [151]:
for i,n in enumerate(cold.isna().sum()):
    print(i,n)

0 0
1 0
2 0
3 0
4 6910
5 0
6 0
7 0
8 0
9 0
10 0
11 0
12 0
13 0
14 0
15 0
16 0
17 0
18 0
19 0
20 0
21 0
22 0
23 0
24 0
25 0
26 0
27 0
28 0
29 3455
30 0
31 0
32 0
33 0
34 0
35 0
36 0
37 0
38 0
39 0
40 0
41 0
42 0
43 0
44 0
45 0
46 0
47 0
48 0
49 0
50 0
51 0
52 0
53 0
54 0
55 0
56 0
57 0
58 0
59 0
60 6910
61 6910
62 6910
63 0


In [152]:
txokla.columns

Index(['GISJOIN', 'STATEFP', 'DAYLIGHT', 'DARK_LIGHTED', 'DARK_NOT_LIGHTED',
       'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN', 'UNK_LIGHT', 'OTHER_LIGHT',
       'POPN', 'CLEAR', 'CLOUDY', 'FOG', 'RAIN', 'SLEET_HAIL', 'Other_Weather',
       'UNK_Weather', 'SNOW_Weather', 'BLOWING_SAND_SNOW', 'SEVERE_CROSSWINDS',
       'INTERSTATE', 'US_STATE_HIGHWAY', 'FARM_TO_MARKET', 'COUNTY_ROAD',
       'CITY_STREET', 'TOLLWAY', 'OTHER_ROADS', 'TOLL_BRIDGES', 'ALCOHOL',
       'DRUG', 'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
       'INATTENTION', 'SPEEDING', 'NO_INJ', 'YES_INJ', 'INJ_COUNT_SUM', 'YEAR',
       'STATE', 'NAME', 'Shape_Area', 'STATE_CAT', 'YEAR_CAT'],
      dtype='object')

In [153]:
cold.isna().sum().sum()

31095

In [154]:
txokla.isna().sum().sum()

0

In [155]:
cold.rename(columns={'UNKNOWN_LIGHT':'UNK_LIGHT','SLEET/HAIL':'SLEET_HAIL',
                     'OTHER_WEATHER':'Other_Weather',
                    'UNKNOWN_WEATHER':'UNK_Weather',
                    'BLOWING SAND/SNOW':'BLOWING_SAND_SNOW',
                    'SEVERE CROSSWINDS':'SEVERE_CROSSWINDS',
                    'ALCOHOL, DRUG':'ALCOHOL__DRUG',
                    'NO INTOXICATION':'NO_INTOXICATION',
                    'NO_INJURY':'NO_INJ','YES_INJURY':'YES_INJ','INJURY_COUNT':'INJ_COUNT_SUM'},inplace= True)

In [156]:
cold.rename(columns={'SNOW_WEATHER':'SNOW_Weather'},inplace= True)

In [157]:
cold['TOLL_BRIDGES'] = 0
cold['TOLLWAY'] = 0
cold['FARM_TO_MARKET'] = 0

In [158]:
cold.columns

Index(['GISJOIN', 'STATEFP', 'POPN', 'INTOXICATION',
       'colorado_19_1_csv_COUNTY_FIPS', 'COUNTY', 'YEAR', 'INJ_COUNT_SUM',
       'INJURY_OUTCOME', 'DARK_LIGHTED', 'DARK_NOT_LIGHTED', 'DAWN',
       'DAYLIGHT', 'DUSK', 'UNK_LIGHT', 'DARK_UNKNOWN_LIGHTING', 'OTHER_LIGHT',
       'CITY_STREET', 'COUNTY_ROAD', 'INTERSTATE', 'OTHER_ROADS',
       'US_STATE_HIGHWAY', 'IMPAIRMENT', 'INATTENTION', 'KNOWN_HUMAN_FACTOR',
       'LANE_CHNG', 'NO_FAULT', 'SPEEDING', 'TAILGATING', 'TECH_PARK',
       'TURNING', 'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION',
       'INJURY_COUNT_SUM', 'NO_INJ', 'YES_INJ', 'NAME', 'Shape_Area',
       'INTOXICATION_DESC', 'ALCOHOL', 'DRUG', 'ALCOHOL__DRUG',
       'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA', 'WEATHER', 'WEATHER_DESC',
       'CLEAR', 'CLOUDY', 'FOG', 'RAIN', 'SLEET_HAIL', 'Other_Weather',
       'UNK_Weather', 'SNOW_Weather', 'BLOWING_SAND_SNOW', 'SEVERE_CROSSWINDS',
       'STATE', 'YEAR_CAT', 'colorado_20_1_csv_COUNTY_FIPS', 'COUNTY_F

In [159]:
cold1 = cold[txokla.columns]

In [160]:
cold1.shape

(10365, 46)

In [161]:
txokla.shape

(54684, 46)

In [162]:
cold['STATE'].unique()

array(['Colorado'], dtype=object)

In [163]:
tco = pd.concat([txokla,cold1],axis=0)

In [164]:
tco.columns

Index(['GISJOIN', 'STATEFP', 'DAYLIGHT', 'DARK_LIGHTED', 'DARK_NOT_LIGHTED',
       'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN', 'UNK_LIGHT', 'OTHER_LIGHT',
       'POPN', 'CLEAR', 'CLOUDY', 'FOG', 'RAIN', 'SLEET_HAIL', 'Other_Weather',
       'UNK_Weather', 'SNOW_Weather', 'BLOWING_SAND_SNOW', 'SEVERE_CROSSWINDS',
       'INTERSTATE', 'US_STATE_HIGHWAY', 'FARM_TO_MARKET', 'COUNTY_ROAD',
       'CITY_STREET', 'TOLLWAY', 'OTHER_ROADS', 'TOLL_BRIDGES', 'ALCOHOL',
       'DRUG', 'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
       'INATTENTION', 'SPEEDING', 'NO_INJ', 'YES_INJ', 'INJ_COUNT_SUM', 'YEAR',
       'STATE', 'NAME', 'Shape_Area', 'STATE_CAT', 'YEAR_CAT'],
      dtype='object')

In [165]:
state_dummies = pd.get_dummies(tco['STATE_CAT'], prefix='STATE')

# Concatenate the original tco DataFrame with the state_dummies DataFrame
tco = pd.concat([tco, state_dummies], axis=1)

In [166]:
year_dummies = pd.get_dummies(tco['YEAR_CAT'], prefix='YEAR')

# Concatenate the original tco DataFrame with the state_dummies DataFrame
tco = pd.concat([tco, year_dummies], axis=1)

In [167]:
tco.columns

Index(['GISJOIN', 'STATEFP', 'DAYLIGHT', 'DARK_LIGHTED', 'DARK_NOT_LIGHTED',
       'DARK_UNKNOWN_LIGHTING', 'DUSK', 'DAWN', 'UNK_LIGHT', 'OTHER_LIGHT',
       'POPN', 'CLEAR', 'CLOUDY', 'FOG', 'RAIN', 'SLEET_HAIL', 'Other_Weather',
       'UNK_Weather', 'SNOW_Weather', 'BLOWING_SAND_SNOW', 'SEVERE_CROSSWINDS',
       'INTERSTATE', 'US_STATE_HIGHWAY', 'FARM_TO_MARKET', 'COUNTY_ROAD',
       'CITY_STREET', 'TOLLWAY', 'OTHER_ROADS', 'TOLL_BRIDGES', 'ALCOHOL',
       'DRUG', 'ALCOHOL__DRUG', 'NO_INTOXICATION', 'MEDICINAL', 'MARIJUANA',
       'INATTENTION', 'SPEEDING', 'NO_INJ', 'YES_INJ', 'INJ_COUNT_SUM', 'YEAR',
       'STATE', 'NAME', 'Shape_Area', 'STATE_CAT', 'YEAR_CAT', 'STATE_1',
       'STATE_2', 'STATE_3', 'YEAR_1', 'YEAR_2', 'YEAR_3'],
      dtype='object')

In [168]:
tco['INJURY_RATE'] = (tco['INJ_COUNT_SUM']/tco['POPN'])*100000

In [169]:
tco['INJURY_RATE'] = tco['INJURY_RATE'].fillna(0)


In [170]:
tco['INJURY_RATE'].isna().sum().sum()

0

In [171]:
tco.isna().sum().sum()

0

In [172]:
tco['LOG_INJ_RATE'] = np.log(tco['INJURY_RATE']+1)

In [173]:
cold.to_csv('colorado_metro.csv',index= False)

In [174]:
tco.shape

(65049, 54)

In [175]:
tco.to_csv('tco_metro.csv',index= False)

In [176]:
tco.shape

(65049, 54)

In [177]:
tco['YEAR'].unique()

array([2019, 2020, 2021], dtype=int64)

In [178]:
tco['STATE'].unique()

array(['Texas', 'Oklahoma', 'Colorado'], dtype=object)