In [1]:
import numpy as np
import pandas as pd

In [2]:
texas = pd.read_csv('C:/Users/karan/Texas_Crash_buffer.csv')

In [3]:
texas['ROAD_CLASS'].unique()

array([5, 2, 1, 3, 4, 6, 7, 8], dtype=int64)

In [4]:
texas['YEAR'].unique()

array([2019, 2020, 2021], dtype=int64)

In [5]:
texas_2019 = texas[texas['YEAR']== 2019]
texas_2020 = texas[texas['YEAR']==2020]
texas_2021 = texas[texas['YEAR']==2021]

In [6]:
age_bands = ['AGE 1-21', 'AGE 22-30', 'AGE 31-65', 'AGE 66 and above', 'Unknown Age']

# Use pd.cut() to bin the ages into the age bands
texas_2019['AGE_BAND'] = pd.cut(texas_2019['AGE'], bins=[0, 21, 30, 65, 100, np.inf], labels=age_bands, right=False)

C:\Users\karan\AppData\Local\Temp\ipykernel_6304\3021618074.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  texas_2019['AGE_BAND'] = pd.cut(texas_2019['AGE'], bins=[0, 21, 30, 65, 100, np.inf], labels=age_bands, right=False)


In [7]:
age_bands = ['AGE 1-21', 'AGE 22-30', 'AGE 31-65', 'AGE 66 and above', 'Unknown Age']

# Use pd.cut() to bin the ages into the age bands
texas_2020['AGE_BAND'] = pd.cut(texas_2020['AGE'], bins=[0, 21, 30, 65, 100, np.inf], labels=age_bands, right=False)

C:\Users\karan\AppData\Local\Temp\ipykernel_6304\3327702539.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  texas_2020['AGE_BAND'] = pd.cut(texas_2020['AGE'], bins=[0, 21, 30, 65, 100, np.inf], labels=age_bands, right=False)


In [8]:
age_bands = ['AGE 1-21', 'AGE 22-30', 'AGE 31-65', 'AGE 66 and above', 'Unknown Age']

# Use pd.cut() to bin the ages into the age bands
texas_2021['AGE_BAND'] = pd.cut(texas_2021['AGE'], bins=[0, 21, 30, 65, 100, np.inf], labels=age_bands, right=False)

C:\Users\karan\AppData\Local\Temp\ipykernel_6304\2660556298.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  texas_2021['AGE_BAND'] = pd.cut(texas_2021['AGE'], bins=[0, 21, 30, 65, 100, np.inf], labels=age_bands, right=False)


In [9]:
def age(df):
    
    # Group by COUNTY and ROAD_TYPE_DESC, then count occurrences
    grouped_road_type = df.groupby(['COUNTY', 'AGE_BAND']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_road_type = grouped_road_type.sum(axis=1)
    
    # Calculate percentages
    age_percentages_df = (grouped_road_type.div(total_counts_by_county_road_type, axis=0) * 100).fillna(0)
    age_percentages_df = age_percentages_df.reset_index()
    
    return age_percentages_df

# Apply the function to each yearly DataFrame
age_percentages_df_2019 = age(texas_2019)
age_percentages_df_2020 = age(texas_2020)
age_percentages_df_2021 = age(texas_2021)

In [10]:
age_percentages_df_2019.shape, age_percentages_df_2020.shape,age_percentages_df_2021.shape

((254, 6), (254, 6), (254, 6))

In [11]:
def merger(f1,f2):
    f1 = pd.merge(f1,f2,on=['COUNTY'],how='left')
    return f1

In [12]:
texas_2019 = merger(texas_2019,age_percentages_df_2019)
texas_2020 = merger(texas_2020,age_percentages_df_2020)
texas_2021 = merger(texas_2021,age_percentages_df_2021)

In [13]:
texas_2019.shape, texas_2020.shape, texas_2021.shape

((241003, 33), (242151, 33), (243069, 33))

In [14]:
texas_2019['GENDER'].unique(), texas_2020['GENDER'].unique(), texas_2021['GENDER'].unique()

(array([2, 1, 0], dtype=int64),
 array([2, 0, 1], dtype=int64),
 array([1, 2, 0], dtype=int64))

In [15]:
gender_mapping = {
    0: 'MALE',
    1: 'FEMALE',
    2: 'UNKNOWN_GENDER'
}



def process_gender_data(df, mapping):
    # Map the gender codes to descriptive names
    df['GENDER_DESC'] = df['GENDER'].map(mapping).astype(str)
    
    # Group by COUNTY and GENDER_DESC, then count occurrences
    grouped = df.groupby(['COUNTY', 'GENDER_DESC']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)
    
    # Calculate percentages
    gender_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    gender_percentages_df = gender_percentages_df.reset_index()
    
    return gender_percentages_df

# Process each year's data
gender_df_2019 = process_gender_data(texas_2019, gender_mapping)
gender_df_2020 = process_gender_data(texas_2020, gender_mapping)
gender_df_2021 = process_gender_data(texas_2021, gender_mapping)


In [16]:
def merger(f1,f2):
    f1 = pd.merge(f1,f2,on=['COUNTY'],how='left')
    return f1

In [17]:
texas_2019 = merger(texas_2019,gender_df_2019)
texas_2020 = merger(texas_2020,gender_df_2020)
texas_2021 = merger(texas_2021,gender_df_2021)

In [18]:
texas_2019.shape, texas_2020.shape, texas_2021.shape

((241003, 37), (242151, 37), (243069, 37))

In [19]:
texas_2019['INTERSECTION'].unique(), texas_2020['INTERSECTION'].unique(), texas_2021['INTERSECTION'].unique()

(array([1, 0], dtype=int64),
 array([1, 0], dtype=int64),
 array([0, 1], dtype=int64))

In [20]:
intersection_mapping ={
    0:'NO_INTERSECTION',
    1:'YES_INTERSECTION'
}


def intersect(df, mapping):
    df['INTERSECTION_DESC'] = df['INTERSECTION'].map(mapping)
    grouped_lighting = df.groupby(['COUNTY', 'INTERSECTION_DESC']).size().unstack(fill_value=0)
    grouped_lighting = df.groupby(['COUNTY', 'INTERSECTION_DESC']).size().unstack(fill_value=0)
    total_counts_by_county_lighting = grouped_lighting.sum(axis=1)
    intersection_percentages_df = (grouped_lighting.div(total_counts_by_county_lighting, axis=0) * 100).fillna(0)
    intersection_percentages_df = intersection_percentages_df.reset_index()
    
    return intersection_percentages_df

intersection_percentages_df_2019 = intersect(texas_2019, intersection_mapping)
intersection_percentages_df_2020 = intersect(texas_2020, intersection_mapping)
intersection_percentages_df_2021 = intersect(texas_2021, intersection_mapping)

In [21]:
texas_2019.shape

(241003, 38)

In [22]:
texas_2019 = merger(texas_2019,intersection_percentages_df_2019)
texas_2020 = merger(texas_2020,intersection_percentages_df_2020)
texas_2021 = merger(texas_2021,intersection_percentages_df_2021)

In [23]:
texas_2019.shape, texas_2020.shape,  texas_2021.shape

((241003, 40), (242151, 40), (243069, 40))

In [24]:
weather_mapping = {
    11: 'CLEAR',
    12: 'CLOUDY',
    5: 'FOG',
    2: 'RAIN',
    3: 'SLEET/HAIL',
    8: 'OTHER_WEATHER',
    0: 'UNKNOWN_WEATHER',
    4: 'SNOW_WEATHER',
    6: 'BLOWING SAND/SNOW',
    7: 'SEVERE CROSSWINDS'
}


texas_2019['WEATHER_DESC'] = texas_2019['WEATHER'].map(weather_mapping)
texas_2020['WEATHER_DESC'] = texas_2020['WEATHER'].map(weather_mapping)
texas_2021['WEATHER_DESC'] = texas_2021['WEATHER'].map(weather_mapping)

def analyze_weather(df):
    grouped_weather = df.groupby(['COUNTY', 'WEATHER_DESC']).size().unstack(fill_value=0)
    total_counts_by_county_weather = grouped_weather.sum(axis=1)
    weather_percentages_df = (grouped_weather.div(total_counts_by_county_weather, axis=0) * 100).fillna(0)
    weather_percentages_df = weather_percentages_df.reset_index()
    return weather_percentages_df

weather_percentages_df_2019 = analyze_weather(texas_2019)
weather_percentages_df_2020 = analyze_weather(texas_2020)
weather_percentages_df_2021 = analyze_weather(texas_2021)

In [25]:
weather_percentages_df_2019.shape

(254, 11)

In [26]:
weather_percentages_df_2020.shape

(254, 11)

In [27]:
weather_percentages_df_2021.shape

(254, 11)

In [28]:
texas_2019.shape

(241003, 41)

In [29]:
texas_2019 = merger(texas_2019,weather_percentages_df_2019)
texas_2020 = merger(texas_2020,weather_percentages_df_2020)
texas_2021 = merger(texas_2021,weather_percentages_df_2021)

In [30]:
texas_2019.shape, texas_2020.shape, texas_2021.shape

((241003, 51), (242151, 51), (243069, 51))

In [31]:
map = {
    0:'UNKNOWN_LIGHT',
    1:'DAYLIGHT',
    2:'DAWN',
    3:'DARK-NOT LIGHTED',
    4:'DARK-LIGHTED',
    5:'DUSK',
    6:'DARK-UNKNOWN LIGHTING',
    8:'OTHER_LIGHT'
}

def process_lighting_data(df, mapping):
    df['LIGHTING_DESC'] = df['LIGHTING'].map(mapping)
    grouped_lighting = df.groupby(['COUNTY', 'LIGHTING_DESC']).size().unstack(fill_value=0)
    grouped_lighting = df.groupby(['COUNTY', 'LIGHTING_DESC']).size().unstack(fill_value=0)
    total_counts_by_county_lighting = grouped_lighting.sum(axis=1)
    lighting_percentages_df = (grouped_lighting.div(total_counts_by_county_lighting, axis=0) * 100).fillna(0)
    lighting_percentages_df = lighting_percentages_df.reset_index()
    
    return lighting_percentages_df

lighting_percentages_df_2019 = process_lighting_data(texas_2019, map)
lighting_percentages_df_2020 = process_lighting_data(texas_2020, map)
lighting_percentages_df_2021 = process_lighting_data(texas_2021, map)

In [32]:
lighting_percentages_df_2019.shape

(254, 9)

In [33]:
lighting_percentages_df_2020.shape

(254, 9)

In [34]:
lighting_percentages_df_2021.shape

(254, 9)

In [35]:
texas_2019 = merger(texas_2019,lighting_percentages_df_2019)
texas_2020 = merger(texas_2020,lighting_percentages_df_2020)
texas_2021 = merger(texas_2021,lighting_percentages_df_2021)

In [36]:
texas_2019.shape, texas_2020.shape, texas_2021.shape

((241003, 60), (242151, 60), (243069, 60))

In [37]:
surface_mapping={
    0:'UNKNOWN_SURF',
    1:'DRY',
    2:'WET',
    3:'STANDING_WATER',
    5:'SLUSH',
    6:'ICE',
    8:'OTHER_SURF',
    9:'SNOW_SURF',
    10:'DIRT'
    
}

def surface(df, mapping):
    df['SURF_DESC'] = df['SURFACE'].map(mapping)
    grouped_lighting = df.groupby(['COUNTY', 'SURF_DESC']).size().unstack(fill_value=0)
    grouped_lighting = df.groupby(['COUNTY', 'SURF_DESC']).size().unstack(fill_value=0)
    total_counts_by_county_lighting = grouped_lighting.sum(axis=1)
    surf_percentages_df = (grouped_lighting.div(total_counts_by_county_lighting, axis=0) * 100).fillna(0)
    surf_percentages_df = surf_percentages_df.reset_index()
    
    return surf_percentages_df

surf_percentages_df_2019 = surface(texas_2019, surface_mapping)
surf_percentages_df_2020 = surface(texas_2020, surface_mapping)
surf_percentages_df_2021 = surface(texas_2021, surface_mapping)


In [38]:
surf_percentages_df_2019.shape

(254, 10)

In [39]:
surf_percentages_df_2020.shape

(254, 10)

In [40]:
surf_percentages_df_2021.shape

(254, 10)

In [41]:
texas_2019 = merger(texas_2019,surf_percentages_df_2019)
texas_2020 = merger(texas_2020,surf_percentages_df_2020)
texas_2021 = merger(texas_2021,surf_percentages_df_2021)

In [42]:
texas_2019.shape, texas_2020.shape, texas_2021.shape

((241003, 70), (242151, 70), (243069, 70))

In [43]:
human_encoding = {
    1:'SPEEDING',
    2:'INATTENTION',
    3:'LANE_CHNG',
    4:'TAILGATING',
    5:'VIOLATION',
    6:'UNSAFE_BACKING',
    7:'IMPAIRMENT',
    8:'TURNING',
    9:'TECH_PARK',
    10:'NO_FAULT',
    11:'KNOWN_HUMAN_FACTOR',
    12:'UNKNOWN_HUMAN_FACTOR'
}


def human(df, mapping):
    # Map the road type codes to descriptive names
    df['HUMAN_FACTOR_DESC'] = df['HUMAN_FACTOR'].map(mapping).astype(str)
    
    # Group by COUNTY and ROAD_TYPE_DESC, then count occurrences
    grouped_road_type = df.groupby(['COUNTY', 'HUMAN_FACTOR_DESC']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_road_type = grouped_road_type.sum(axis=1)
    
    # Calculate percentages
    human_percentages_df = (grouped_road_type.div(total_counts_by_county_road_type, axis=0) * 100).fillna(0)
    human_percentages_df = human_percentages_df.reset_index()
    
    return human_percentages_df

# Apply the function to each yearly DataFrame
human_percentages_df_2019 = human(texas_2019, human_encoding)
human_percentages_df_2020 = human(texas_2020, human_encoding)
human_percentages_df_2021 = human(texas_2021, human_encoding)

In [44]:
human_percentages_df_2019.shape, human_percentages_df_2020.shape, human_percentages_df_2021.shape

((254, 12), (254, 13), (254, 13))

In [45]:
human_percentages_df_2019.columns

Index(['COUNTY', 'IMPAIRMENT', 'INATTENTION', 'KNOWN_HUMAN_FACTOR',
       'LANE_CHNG', 'NO_FAULT', 'SPEEDING', 'TECH_PARK', 'TURNING',
       'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION'],
      dtype='object', name='HUMAN_FACTOR_DESC')

In [46]:
human_percentages_df_2020.columns

Index(['COUNTY', 'IMPAIRMENT', 'INATTENTION', 'KNOWN_HUMAN_FACTOR',
       'LANE_CHNG', 'NO_FAULT', 'SPEEDING', 'TAILGATING', 'TECH_PARK',
       'TURNING', 'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION'],
      dtype='object', name='HUMAN_FACTOR_DESC')

In [47]:
human_percentages_df_2021.columns


Index(['COUNTY', 'IMPAIRMENT', 'INATTENTION', 'KNOWN_HUMAN_FACTOR',
       'LANE_CHNG', 'NO_FAULT', 'SPEEDING', 'TAILGATING', 'TECH_PARK',
       'TURNING', 'UNKNOWN_HUMAN_FACTOR', 'UNSAFE_BACKING', 'VIOLATION'],
      dtype='object', name='HUMAN_FACTOR_DESC')

In [48]:
human_percentages_df_2019.insert(7,'TAILGATING',0)

In [49]:
texas_2019 = merger(texas_2019,human_percentages_df_2019)
texas_2020 = merger(texas_2020,human_percentages_df_2020)
texas_2021 = merger(texas_2021,human_percentages_df_2021)

In [50]:
texas['ROAD_CLASS'].unique()

array([5, 2, 1, 3, 4, 6, 7, 8], dtype=int64)

In [51]:
texas_2019.shape, texas_2020.shape, texas_2021.shape

((241003, 83), (242151, 83), (243069, 83))

In [52]:
roadway_types = {
    1: 'INTERSTATE',
    2: 'US & STATE HIGHWAY',
    3: 'FARM TO MARKET',
    4: 'COUNTY ROAD',
    5: 'CITY STREET',
    6: 'TOLLWAY',
    7: 'OTHER ROADS',
    8: 'TOLL BRIDGES'
}


def process_road_type_data(df, mapping):
    # Map the road type codes to descriptive names
    df['ROAD_TYPE_DESC'] = df['ROAD_CLASS'].map(mapping).astype(str)
    
    # Group by COUNTY and ROAD_TYPE_DESC, then count occurrences
    grouped_road_type = df.groupby(['COUNTY', 'ROAD_TYPE_DESC']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_road_type = grouped_road_type.sum(axis=1)
    
    # Calculate percentages
    road_type_percentages_df = (grouped_road_type.div(total_counts_by_county_road_type, axis=0) * 100).fillna(0)
    road_type_percentages_df = road_type_percentages_df.reset_index()
    
    return road_type_percentages_df

# Apply the function to each yearly DataFrame
road_type_percentages_df_2019 = process_road_type_data(texas_2019, roadway_types)
road_type_percentages_df_2020 = process_road_type_data(texas_2020, roadway_types)
road_type_percentages_df_2021 = process_road_type_data(texas_2021, roadway_types)

In [53]:
road_type_percentages_df_2019.shape, road_type_percentages_df_2020.shape, road_type_percentages_df_2021.shape

((254, 9), (254, 9), (254, 9))

In [54]:
texas_2019 = merger(texas_2019,road_type_percentages_df_2019)
texas_2020 = merger(texas_2020,road_type_percentages_df_2020)
texas_2021 = merger(texas_2021,road_type_percentages_df_2021)

In [55]:
texas_2019.shape, texas_2020.shape, texas_2021.shape


((241003, 92), (242151, 92), (243069, 92))

In [56]:
texas['INJURY_OUTCOME'].unique()

array([0, 1], dtype=int64)

In [57]:
map = {
    0:'NO_INJURY',
    1:'YES_INJURY'
}

def injury(df,map):
    df['INJURY_DESC'] = df['INJURY_OUTCOME'].map(map).astype('str')
    grouped = df.groupby(['COUNTY','INJURY_DESC']).size().unstack(fill_value=0)
    total_counts_by_county = grouped.sum(axis=1)
    injury_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    injury_percentages_df = injury_percentages_df.reset_index()
    return injury_percentages_df

injury_percentages_df_2019 = injury(texas_2019, map)
injury_percentages_df_2020 = injury(texas_2020, map)
injury_percentages_df_2021 = injury(texas_2021, map)

In [58]:
texas_2019 = merger(texas_2019,injury_percentages_df_2019)
texas_2020 = merger(texas_2020,injury_percentages_df_2020)
texas_2021 = merger(texas_2021,injury_percentages_df_2021)

In [59]:
texas_2019.shape, texas_2020.shape, texas_2021.shape

((241003, 95), (242151, 95), (243069, 95))

In [60]:
texas_2019.columns

Index(['Crash_ID', 'AGE', 'GENDER', 'DATE', 'TIME', 'COUNTY_FIPS', 'COUNTY',
       'INTERSECTION', 'WEATHER', 'LIGHTING', 'SURFACE', 'HUMAN_FACTOR',
       'ROAD_CLASS', 'LATITUDE', 'LONGITUDE', 'MEDIANWIDTH', 'LANES',
       'ROADWIDTH', 'AADT', 'INJURY_OUTCOME', 'INJURY_COUNT', 'YEAR',
       'INTOXICATION', 'BUFF_DIST', 'ORIG_FID', 'Shape_Length', 'Shape_Area',
       'AGE_BAND', 'AGE 1-21', 'AGE 22-30', 'AGE 31-65', 'AGE 66 and above',
       'Unknown Age', 'GENDER_DESC', 'FEMALE', 'MALE', 'UNKNOWN_GENDER',
       'INTERSECTION_DESC', 'NO_INTERSECTION', 'YES_INTERSECTION',
       'WEATHER_DESC', 'BLOWING SAND/SNOW', 'CLEAR', 'CLOUDY', 'FOG',
       'OTHER_WEATHER', 'RAIN', 'SEVERE CROSSWINDS', 'SLEET/HAIL',
       'SNOW_WEATHER', 'UNKNOWN_WEATHER', 'LIGHTING_DESC', 'DARK-LIGHTED',
       'DARK-NOT LIGHTED', 'DARK-UNKNOWN LIGHTING', 'DAWN', 'DAYLIGHT', 'DUSK',
       'OTHER_LIGHT', 'UNKNOWN_LIGHT', 'SURF_DESC', 'DIRT', 'DRY', 'ICE',
       'OTHER_SURF', 'SLUSH', 'SNOW_SURF', 'STAND

In [61]:
intoxication_mapping = {
    1: 'ALCOHOL',
    2: 'DRUG',
    3: 'ALCOHOL, DRUG',
    4: 'NO INTOXICATION',
    5: 'MEDICINAL',
    6: 'MARIJUANA'
}

In [62]:
def process_intoxication_data(df, mapping):
    # Map the intoxication codes to descriptive names
    df['INTOXICATION_DESC'] = df['INTOXICATION'].map(mapping).astype(str)
    
    # Group by COUNTY and INTOXICATION_DESC, then count occurrences
    grouped = df.groupby(['COUNTY', 'INTOXICATION_DESC']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)
    
    # Calculate percentages
    intoxication_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    intoxication_percentages_df = intoxication_percentages_df.reset_index()
    
    return intoxication_percentages_df

# Process each year's data
intoxication_df_2019 = process_intoxication_data(texas_2019, intoxication_mapping)
intoxication_df_2020 = process_intoxication_data(texas_2020, intoxication_mapping)
intoxication_df_2021 = process_intoxication_data(texas_2021, intoxication_mapping)



In [63]:
intoxication_df_2019

INTOXICATION_DESC    COUNTY   ALCOHOL  ALCOHOL, DRUG      DRUG  MARIJUANA  \
0                  Anderson  0.000000            0.0  0.390625   0.585938   
1                   Andrews  0.000000            0.0  0.444444   0.000000   
2                  Angelina  0.095238            0.0  0.000000   0.000000   
3                   Aransas  0.000000            0.0  0.500000   0.000000   
4                    Archer  0.000000            0.0  1.063830   0.000000   
..                      ...       ...            ...       ...        ...   
249                    Wood  0.272480            0.0  0.272480   0.000000   
250                  Yoakum  0.000000            0.0  0.000000   0.000000   
251                   Young  0.000000            0.0  0.000000   0.000000   
252                  Zapata  0.000000            0.0  0.000000   0.000000   
253                  Zavala  0.000000            0.0  0.000000   0.000000   

INTOXICATION_DESC  MEDICINAL  NO INTOXICATION  
0                   0.000000        99.023438  
1                   0.000000        99.555556  
2                   0.000000        99.904762  
3                   0.500000        99.000000  
4                   0.000000        98.936170  
..                       ...              ...  
249                 1.089918        98.365123  
250                 0.000000       100.000000  
251                 0.000000       100.000000  
252                 0.000000       100.000000  
253                 0.000000       100.000000  

[254 rows x 7 columns]

In [64]:
intoxication_df_2020

INTOXICATION_DESC    COUNTY  ALCOHOL  ALCOHOL, DRUG      DRUG  MARIJUANA  \
0                  Anderson      0.0            0.0  0.563910   0.000000   
1                   Andrews      0.0            0.0  0.518135   0.000000   
2                  Angelina      0.0            0.0  0.078003   0.000000   
3                   Aransas      0.0            0.0  0.000000   0.000000   
4                    Archer      0.0            0.0  0.000000   0.787402   
..                      ...      ...            ...       ...        ...   
249                    Wood      0.0            0.0  0.476190   0.000000   
250                  Yoakum      0.0            0.0  0.000000   0.000000   
251                   Young      0.0            0.0  0.666667   0.000000   
252                  Zapata      0.0            0.0  0.000000   0.000000   
253                  Zavala      0.0            0.0  0.000000   0.000000   

INTOXICATION_DESC  MEDICINAL  NO INTOXICATION  
0                   0.000000        99.436090  
1                   0.000000        99.481865  
2                   0.156006        99.765991  
3                   0.000000       100.000000  
4                   1.574803        97.637795  
..                       ...              ...  
249                 0.952381        98.571429  
250                 0.000000       100.000000  
251                 0.666667        98.666667  
252                 0.000000       100.000000  
253                 0.000000       100.000000  

[254 rows x 7 columns]

In [65]:
intoxication_df_2021

INTOXICATION_DESC    COUNTY   ALCOHOL  ALCOHOL, DRUG      DRUG  MARIJUANA  \
0                  Anderson  0.000000            0.0  0.000000   0.000000   
1                   Andrews  0.000000            0.0  0.000000   0.000000   
2                  Angelina  0.082237            0.0  0.164474   0.000000   
3                   Aransas  0.000000            0.0  0.000000   0.000000   
4                    Archer  0.000000            0.0  1.041667   1.041667   
..                      ...       ...            ...       ...        ...   
249                    Wood  0.000000            0.0  0.000000   0.542005   
250                  Yoakum  0.000000            0.0  0.000000   0.000000   
251                   Young  0.000000            0.0  0.000000   0.000000   
252                  Zapata  0.000000            0.0  0.000000   0.000000   
253                  Zavala  0.000000            0.0  0.000000   0.000000   

INTOXICATION_DESC  MEDICINAL  NO INTOXICATION  
0                    0.39604        99.603960  
1                    0.00000       100.000000  
2                    0.00000        99.753289  
3                    0.00000       100.000000  
4                    0.00000        97.916667  
..                       ...              ...  
249                  0.00000        99.457995  
250                  0.00000       100.000000  
251                  0.00000       100.000000  
252                  0.00000       100.000000  
253                  0.00000       100.000000  

[254 rows x 7 columns]

In [66]:
texas_2019 = merger(texas_2019,intoxication_df_2019)
texas_2020 = merger(texas_2020,intoxication_df_2020)
texas_2021 = merger(texas_2021,intoxication_df_2021)

In [67]:
texas_2019.shape, texas_2020.shape, texas_2021.shape

((241003, 102), (242151, 102), (243069, 102))

In [68]:
texas_2019.columns

Index(['Crash_ID', 'AGE', 'GENDER', 'DATE', 'TIME', 'COUNTY_FIPS', 'COUNTY',
       'INTERSECTION', 'WEATHER', 'LIGHTING',
       ...
       'INJURY_DESC', 'NO_INJURY', 'YES_INJURY', 'INTOXICATION_DESC',
       'ALCOHOL', 'ALCOHOL, DRUG', 'DRUG', 'MARIJUANA', 'MEDICINAL',
       'NO INTOXICATION'],
      dtype='object', length=102)

In [69]:
texas_2019['INJURY_COUNT_SUM'] = texas_2019.groupby(['COUNTY'])['INJURY_COUNT'].transform('sum')
texas_2020['INJURY_COUNT_SUM'] = texas_2020.groupby(['COUNTY'])['INJURY_COUNT'].transform('sum')
texas_2021['INJURY_COUNT_SUM'] = texas_2021.groupby(['COUNTY'])['INJURY_COUNT'].transform('sum')

In [70]:
texas_2019.columns

Index(['Crash_ID', 'AGE', 'GENDER', 'DATE', 'TIME', 'COUNTY_FIPS', 'COUNTY',
       'INTERSECTION', 'WEATHER', 'LIGHTING',
       ...
       'NO_INJURY', 'YES_INJURY', 'INTOXICATION_DESC', 'ALCOHOL',
       'ALCOHOL, DRUG', 'DRUG', 'MARIJUANA', 'MEDICINAL', 'NO INTOXICATION',
       'INJURY_COUNT_SUM'],
      dtype='object', length=103)

In [71]:
texas_comb = pd.concat([texas_2019,texas_2020,texas_2021],axis=0)

In [72]:
texas_comb.shape

(726223, 103)

In [73]:
texas_comb['YEAR_CAT'] = np.where(texas_comb['YEAR']==2019,1,np.where(texas_comb['YEAR']==2020,2,np.where(texas_comb['YEAR']==2021,3,np.nan)))

In [74]:
texas_comb = pd.get_dummies(texas_comb,columns=['YEAR'])

In [75]:
texas_comb

Crash_ID  AGE  GENDER       DATE      TIME  COUNTY_FIPS      COUNTY  \
0       15585669   27       2  2/10/2019   4:50 PM        48141     El Paso   
1       16473665   48       1  6/15/2019  11:00 AM        48241      Jasper   
2       16585839   44       1  1/26/2019  12:40 PM        48113      Dallas   
3       16824697   37       1   1/1/2019   4:53 AM        48113      Dallas   
4       16824710   53       1   1/1/2019   2:57 AM        48303     Lubbock   
...          ...  ...     ...        ...       ...          ...         ...   
243064  19834478   38       1  1/29/2021   3:57 PM        48019     Bandera   
243065  19850863   52       1  2/21/2021  12:22 PM        48019     Bandera   
243066  19906451   66       1  8/25/2021   7:32 PM        48479        Webb   
243067  20073914   18       1  2/23/2021   3:50 AM        48201      Harris   
243068  20087367   35       1  3/14/2021   5:30 PM        48339  Montgomery   

        INTERSECTION  WEATHER  LIGHTING  ...  ALCOHOL, DRUG      DRUG  \
0                  1       11         1  ...       0.000000  0.025940   
1                  1       11         1  ...       0.000000  0.295858   
2                  0       11         1  ...       0.010487  0.115358   
3                  0       11         4  ...       0.010487  0.115358   
4                  1       12         4  ...       0.000000  0.075273   
...              ...      ...       ...  ...            ...       ...   
243064             0       11         1  ...       0.000000  0.000000   
243065             0       11         1  ...       0.000000  0.000000   
243066             0       11         1  ...       0.000000  0.045872   
243067             0       11         4  ...       0.009031  0.069235   
243068             0       11         1  ...       0.000000  0.165593   

        MARIJUANA  MEDICINAL  NO INTOXICATION  INJURY_COUNT_SUM  YEAR_CAT  \
0        0.038911   0.012970        99.753567              2850       1.0   
1        0.295858   0.295858        99.112426               128       1.0   
2        0.094384   0.068166        98.615699              9934       1.0   
3        0.094384   0.068166        98.615699              9934       1.0   
4        0.112909   0.150546        99.623636              1596       1.0   
...           ...        ...              ...               ...       ...   
243064   0.000000   0.000000       100.000000                59       3.0   
243065   0.000000   0.000000       100.000000                59       3.0   
243066   0.000000   0.000000        99.816514               811       3.0   
243067   0.015051   0.051174        99.358820             13385       3.0   
243068   0.018399   0.055198        99.687213              2144       3.0   

        YEAR_2019  YEAR_2020  YEAR_2021  
0               1          0          0  
1               1          0          0  
2               1          0          0  
3               1          0          0  
4               1          0          0  
...           ...        ...        ...  
243064          0          0          1  
243065          0          0          1  
243066          0          0          1  
243067          0          0          1  
243068          0          0          1  

[726223 rows x 106 columns]

In [76]:
texas_comb.to_csv('texas_comb.csv',index= False)