In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('C:/Users/karan/TEXAS 1.csv')

In [3]:
data.columns

Index(['GISJOIN', 'COUNTYFP', 'TRACTCE', 'Shape_Leng', 'nhgis0014_GISJOIN',
       'STATE', 'COUNTY', 'AMPVE001_POPN', 'FID_Texas_XYTable_Buffer',
       'Intoxication', 'Crash_ID', 'Age', 'Ethnicity', 'Gender', 'Crash_Date',
       'Crash_Time', 'FIPS_Code', 'County_Name', 'Damage_1000', 'Speed',
       'Intersection', 'Weather', 'Lighting', 'EntrRoad', 'RoadType',
       'RoadAlign', 'Surface', 'Evnt_1', 'HmnFac_1', 'RoadPart', 'RoadClass',
       'Latitude', 'Longitude', 'Severity', 'Days', 'MedianWidth', 'NmbrLanes',
       'Roadbed_Width', 'AADT', 'Injury', 'Tot_Injry_Cnt', 'Death_Cnt', 'YEAR',
       'Test', 'Shape_Length', 'Shape_Area'],
      dtype='object')

In [4]:
data.rename(columns={'AMPVE001_POPN':'POPN'},inplace= True)

In [5]:
map_1 = {2:5,3:5,4:5}
data['Intoxication'].replace(map_1,inplace= True)

In [6]:
map_2 = {6:2,7:2}
data['Intoxication'].replace(map_2,inplace= True)

In [7]:
map_3 = {8:6,10:2,11:2,12:2}
data['Intoxication'].replace(map_3,inplace= True)

In [8]:
map_4 = {97:4,99:4}
data['Intoxication'].replace(map_4,inplace= True)

In [9]:
data['Intoxication'].unique()

array([4, 6, 2, 5], dtype=int64)

In [10]:
t_19 = data[data['YEAR']==2019]
t_20 = data[data['YEAR']==2020]
t_21 = data[data['YEAR']==2021]

In [11]:
t_19['Intoxication'].value_counts()

4    327082
2       324
5       236
6       174
Name: Intoxication, dtype: int64

In [12]:
test_mapping = {
    1: 'ALCOHOL',
    2: 'DRUG',
    3: 'ALCOHOL, DRUG',
    4: 'NO INTOXICATION',
    5: 'MEDICINAL',
    6: 'MARIJUANA'
}


In [13]:
def process_intoxication_data(df, mapping):
    # Map the intoxication codes to descriptive names
    df['TEST_DESC'] = df['Test'].map(mapping).astype(str)

    # Create a list of all possible intoxication categories
    all_categories = list(mapping.values())

    # Group by COUNTY and INTOXICATION_DESC, then count occurrences
    grouped = df.groupby(['GISJOIN', 'TEST_DESC']).size().unstack(fill_value=0)

    # Reindex the DataFrame to include all possible intoxication categories
    grouped = grouped.reindex(columns=all_categories, fill_value=0)

    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)

    # Calculate percentages
    test_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    test_percentages_df = test_percentages_df.reset_index(drop=False)

    return test_percentages_df

# Process each year's data
test_df_2019 = process_intoxication_data(t_19, test_mapping)
test_df_2020 = process_intoxication_data(t_20, test_mapping)
test_df_2021 = process_intoxication_data(t_21, test_mapping)



C:\Users\karan\AppData\Local\Temp\ipykernel_19036\3178468100.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TEST_DESC'] = df['Test'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\3178468100.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['TEST_DESC'] = df['Test'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\3178468100.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_

In [14]:
test_df_2019

TEST_DESC          GISJOIN  ALCOHOL  DRUG  ALCOHOL, DRUG  NO INTOXICATION  \
0          G48000109501001      0.0   0.0            0.0            100.0   
1          G48000109501002      0.0   0.0            0.0            100.0   
2          G48000109501003      0.0   0.0            0.0            100.0   
3          G48000109505001      0.0   0.0            0.0            100.0   
4          G48000109505002      0.0   0.0            0.0            100.0   
...                    ...      ...   ...            ...              ...   
10047      G48050709503021      0.0   0.0            0.0            100.0   
10048      G48050709503022      0.0   0.0            0.0            100.0   
10049      G48050709503023      0.0   0.0            0.0            100.0   
10050      G48050709503024      0.0   0.0            0.0            100.0   
10051      G48050709503025      0.0   0.0            0.0            100.0   

TEST_DESC  MEDICINAL  MARIJUANA  
0                0.0        0.0  
1                0.0        0.0  
2                0.0        0.0  
3                0.0        0.0  
4                0.0        0.0  
...              ...        ...  
10047            0.0        0.0  
10048            0.0        0.0  
10049            0.0        0.0  
10050            0.0        0.0  
10051            0.0        0.0  

[10052 rows x 7 columns]

In [15]:
t19 = t_19.groupby(['GISJOIN'])

In [16]:
group19 = t19.size()

In [17]:
group19 = group19.reset_index()

In [18]:
group19.columns

Index(['GISJOIN', 0], dtype='object')

In [19]:
group19.rename(columns={0:'COUNT'},inplace = True)

In [20]:
group19

GISJOIN  COUNT
0      G48000109501001      5
1      G48000109501002     26
2      G48000109501003     27
3      G48000109505001     27
4      G48000109505002      4
...                ...    ...
10047  G48050709503021      5
10048  G48050709503022      1
10049  G48050709503023      1
10050  G48050709503024      1
10051  G48050709503025      1

[10052 rows x 2 columns]

In [21]:
group20 = t_20.groupby(['GISJOIN'])

In [22]:
group20 = group20.size()

In [23]:
group20 = group20.reset_index()

In [24]:
group20 = group20.rename(columns={0:'COUNT'})

In [25]:
group20

GISJOIN  COUNT
0      G48000109501001     12
1      G48000109501002     19
2      G48000109501003     17
3      G48000109505001     34
4      G48000109505002      1
...                ...    ...
10026  G48050709503011     16
10027  G48050709503021      8
10028  G48050709503022      2
10029  G48050709503024      7
10030  G48050709503025      2

[10031 rows x 2 columns]

In [26]:
group21 = t_21.groupby(['GISJOIN'])
group21 = group21.size()
group21= group21.reset_index()

In [27]:
group21 = group21.rename(columns={0:'COUNT'})

In [28]:
t1 = pd.merge(group19,test_df_2019,on=['GISJOIN'],how='left')

In [29]:
t2 = pd.merge(group20,test_df_2020,on=['GISJOIN'],how='left')

In [30]:
t3 = pd.merge(group21,test_df_2021,on=['GISJOIN'],how='left')

In [31]:
t1.shape, t2.shape, t3.shape

((10052, 8), (10031, 8), (10007, 8))

In [32]:
data.columns

Index(['GISJOIN', 'COUNTYFP', 'TRACTCE', 'Shape_Leng', 'nhgis0014_GISJOIN',
       'STATE', 'COUNTY', 'POPN', 'FID_Texas_XYTable_Buffer', 'Intoxication',
       'Crash_ID', 'Age', 'Ethnicity', 'Gender', 'Crash_Date', 'Crash_Time',
       'FIPS_Code', 'County_Name', 'Damage_1000', 'Speed', 'Intersection',
       'Weather', 'Lighting', 'EntrRoad', 'RoadType', 'RoadAlign', 'Surface',
       'Evnt_1', 'HmnFac_1', 'RoadPart', 'RoadClass', 'Latitude', 'Longitude',
       'Severity', 'Days', 'MedianWidth', 'NmbrLanes', 'Roadbed_Width', 'AADT',
       'Injury', 'Tot_Injry_Cnt', 'Death_Cnt', 'YEAR', 'Test', 'Shape_Length',
       'Shape_Area'],
      dtype='object')

In [33]:
data['Ethnicity'].unique()

array([2, 1, 0, 5, 4, 3, 6], dtype=int64)

In [34]:
eth_mapping= {
    0:'UNK',
    1:'White',
    2:'Hispanic',
    3:'Black',
    4:'Asian',
    5:'Other',
    6:'American Native'
}

In [35]:
def process_intoxication_data(df, mapping):
    # Map the intoxication codes to descriptive names
    df['eth_desc'] = df['Ethnicity'].map(mapping).astype(str)

    # Create a list of all possible intoxication categories
    all_categories = list(mapping.values())

    # Group by COUNTY and INTOXICATION_DESC, then count occurrences
    grouped = df.groupby(['GISJOIN', 'eth_desc']).size().unstack(fill_value=0)

    # Reindex the DataFrame to include all possible intoxication categories
    grouped = grouped.reindex(columns=all_categories, fill_value=0)

    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)

    # Calculate percentages
    intoxication_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    intoxication_percentages_df = intoxication_percentages_df.reset_index(drop=False)

    return intoxication_percentages_df

# Process each year's data
eth_df_2019 = process_intoxication_data(t_19, eth_mapping)
eth_df_2020 = process_intoxication_data(t_20, eth_mapping)
eth_df_2021 = process_intoxication_data(t_21, eth_mapping)



C:\Users\karan\AppData\Local\Temp\ipykernel_19036\3190312613.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['eth_desc'] = df['Ethnicity'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\3190312613.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['eth_desc'] = df['Ethnicity'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\3190312613.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .

In [36]:
t1 = pd.merge(t1,eth_df_2019,on=['GISJOIN'],how= 'left')
t2 = pd.merge(t2,eth_df_2020,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,eth_df_2021,on=['GISJOIN'],how='left')

In [37]:
t1.shape, t2.shape, t3.shape

((10052, 15), (10031, 15), (10007, 15))

In [38]:
data['Damage_1000'].unique()

array(['Y', 'N'], dtype=object)

In [39]:
data['Damage_1000'].unique()

array(['Y', 'N'], dtype=object)

In [40]:
grouped_intersection_2019 = t_19.groupby(['GISJOIN', 'Damage_1000']).size().unstack(fill_value=0)

In [41]:
grouped_intersection_2019

Damage_1000      N   Y
GISJOIN               
G48000109501001  0   5
G48000109501002  0  26
G48000109501003  0  27
G48000109505001  1  26
G48000109505002  0   4
...             ..  ..
G48050709503021  0   5
G48050709503022  0   1
G48050709503023  0   1
G48050709503024  1   0
G48050709503025  0   1

[10052 rows x 2 columns]

In [42]:
# Grouping, counting, and formatting for df_2020
grouped_intersection_20219 = t_19.groupby(['GISJOIN', 'Damage_1000']).size().unstack(fill_value=0)
grouped_intersection_2019.columns = ['NO_Damage', 'YES_Damage']
total_counts_by_county_2019 = grouped_intersection_2019.sum(axis=1)
no_intersection_percentage_2019 = (grouped_intersection_2019['NO_Damage'] / total_counts_by_county_2019) * 100
yes_intersection_percentage_2019 = (grouped_intersection_2019['YES_Damage'] / total_counts_by_county_2019) * 100

intersection_percentages_df_2019 = pd.concat([
    no_intersection_percentage_2019, 
    yes_intersection_percentage_2019
], axis=1)
intersection_percentages_df_2019.columns = ['NO_Damage', 'YES_Damage']
intersection_percentages_df_2019 = intersection_percentages_df_2019.reset_index().rename(columns={'index': 'GISJOIN'})
intersection_percentages_df_2019.fillna(0, inplace=True)
intersection_percentages_df_2019

GISJOIN   NO_Damage  YES_Damage
0      G48000109501001    0.000000  100.000000
1      G48000109501002    0.000000  100.000000
2      G48000109501003    0.000000  100.000000
3      G48000109505001    3.703704   96.296296
4      G48000109505002    0.000000  100.000000
...                ...         ...         ...
10047  G48050709503021    0.000000  100.000000
10048  G48050709503022    0.000000  100.000000
10049  G48050709503023    0.000000  100.000000
10050  G48050709503024  100.000000    0.000000
10051  G48050709503025    0.000000  100.000000

[10052 rows x 3 columns]

In [43]:
grouped_intersection_2020 = t_20.groupby(['GISJOIN', 'Damage_1000']).size().unstack(fill_value=0)
grouped_intersection_2020.columns = ['NO_Damage', 'YES_Damage']
total_counts_by_county_2020 = grouped_intersection_2020.sum(axis=1)
no_intersection_percentage_2020 = (grouped_intersection_2020['NO_Damage'] / total_counts_by_county_2020) * 100
yes_intersection_percentage_2020 = (grouped_intersection_2020['YES_Damage'] / total_counts_by_county_2020) * 100

intersection_percentages_df_2020 = pd.concat([
    no_intersection_percentage_2020,
    yes_intersection_percentage_2020
], axis=1)
intersection_percentages_df_2020.columns = ['NO_Damage', 'YES_Damage']
intersection_percentages_df_2020 = intersection_percentages_df_2020.reset_index().rename(columns={'index': 'GISJOIN'})
intersection_percentages_df_2020.fillna(0, inplace=True)
intersection_percentages_df_2020

GISJOIN  NO_Damage  YES_Damage
0      G48000109501001   8.333333   91.666667
1      G48000109501002   0.000000  100.000000
2      G48000109501003   0.000000  100.000000
3      G48000109505001   5.882353   94.117647
4      G48000109505002   0.000000  100.000000
...                ...        ...         ...
10026  G48050709503011   6.250000   93.750000
10027  G48050709503021  12.500000   87.500000
10028  G48050709503022   0.000000  100.000000
10029  G48050709503024   0.000000  100.000000
10030  G48050709503025  50.000000   50.000000

[10031 rows x 3 columns]

In [44]:
grouped_intersection_2021 = t_21.groupby(['GISJOIN', 'Damage_1000']).size().unstack(fill_value=0)
grouped_intersection_2021.columns = ['NO_Damage', 'YES_Damage']
total_counts_by_county_2021 = grouped_intersection_2021.sum(axis=1)
no_intersection_percentage_2021 = (grouped_intersection_2021['NO_Damage'] / total_counts_by_county_2021) * 100
yes_intersection_percentage_2021 = (grouped_intersection_2021['YES_Damage'] / total_counts_by_county_2021) * 100

intersection_percentages_df_2021 = pd.concat([
    no_intersection_percentage_2021,
    yes_intersection_percentage_2021
], axis=1)
intersection_percentages_df_2021.columns = ['NO_Damage', 'YES_Damage']
intersection_percentages_df_2021 = intersection_percentages_df_2021.reset_index().rename(columns={'index': 'GISJOIN'})
intersection_percentages_df_2021.fillna(0, inplace=True)
intersection_percentages_df_2021

GISJOIN  NO_Damage  YES_Damage
0      G48000109501001   0.000000  100.000000
1      G48000109501002   0.000000  100.000000
2      G48000109501003   5.555556   94.444444
3      G48000109504021   0.000000  100.000000
4      G48000109505001   0.000000  100.000000
...                ...        ...         ...
10002  G48050709503011   0.000000  100.000000
10003  G48050709503021   0.000000  100.000000
10004  G48050709503023   0.000000  100.000000
10005  G48050709503024  66.666667   33.333333
10006  G48050709503025   0.000000  100.000000

[10007 rows x 3 columns]

In [45]:
t1 = pd.merge(t1,intersection_percentages_df_2019,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,intersection_percentages_df_2020,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,intersection_percentages_df_2021,on=['GISJOIN'],how='left')

In [46]:
t1.shape, t2.shape, t3.shape

((10052, 17), (10031, 17), (10007, 17))

In [47]:
t1.isna().sum()

GISJOIN            0
COUNT              0
ALCOHOL            0
DRUG               0
ALCOHOL, DRUG      0
NO INTOXICATION    0
MEDICINAL          0
MARIJUANA          0
UNK                0
White              0
Hispanic           0
Black              0
Asian              0
Other              0
American Native    0
NO_Damage          0
YES_Damage         0
dtype: int64

In [48]:
t2.isna().sum()

GISJOIN            0
COUNT              0
ALCOHOL            0
DRUG               0
ALCOHOL, DRUG      0
NO INTOXICATION    0
MEDICINAL          0
MARIJUANA          0
UNK                0
White              0
Hispanic           0
Black              0
Asian              0
Other              0
American Native    0
NO_Damage          0
YES_Damage         0
dtype: int64

In [49]:
t3.isna().sum()

GISJOIN            0
COUNT              0
ALCOHOL            0
DRUG               0
ALCOHOL, DRUG      0
NO INTOXICATION    0
MEDICINAL          0
MARIJUANA          0
UNK                0
White              0
Hispanic           0
Black              0
Asian              0
Other              0
American Native    0
NO_Damage          0
YES_Damage         0
dtype: int64

In [50]:
data['Intersection']

0         Y
1         Y
2         N
3         N
4         Y
         ..
986360    Y
986361    Y
986362    Y
986363    Y
986364    Y
Name: Intersection, Length: 986365, dtype: object

In [51]:
grouped_intersection = t_19.groupby(['GISJOIN', 'Intersection']).size().unstack(fill_value=0)
grouped_intersection

Intersection      N   Y
GISJOIN                
G48000109501001   2   3
G48000109501002  24   2
G48000109501003  21   6
G48000109505001  15  12
G48000109505002   3   1
...              ..  ..
G48050709503021   1   4
G48050709503022   0   1
G48050709503023   1   0
G48050709503024   0   1
G48050709503025   1   0

[10052 rows x 2 columns]

In [52]:
def calculate_intersection_percentages(df):
    grouped_intersection = df.groupby(['GISJOIN', 'Intersection']).size().unstack(fill_value=0)
    grouped_intersection.columns = ['NO_Intersection', 'YES_Intersection']
    total_counts_by_county = grouped_intersection.sum(axis=1)
    no_intersection_percentage = (grouped_intersection['NO_Intersection'] / total_counts_by_county) * 100
    yes_intersection_percentage = (grouped_intersection['YES_Intersection'] / total_counts_by_county) * 100

    intersection_percentages_df = pd.concat([
        no_intersection_percentage,
        yes_intersection_percentage
    ], axis=1)
    intersection_percentages_df.columns = ['NO_Intersection', 'YES_Intersection']
    intersection_percentages_df = intersection_percentages_df.reset_index().rename(columns={'index': 'GISJOIN'})
    intersection_percentages_df.fillna(0, inplace=True)

    return intersection_percentages_df

In [53]:
t11 = calculate_intersection_percentages(t_19)
t22 = calculate_intersection_percentages(t_20)
t33 = calculate_intersection_percentages(t_21)

In [54]:
t1 = pd.merge(t1,t11,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,t22,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,t33,on=['GISJOIN'],how='left')

In [55]:
t1.shape, t2.shape, t3.shape

((10052, 19), (10031, 19), (10007, 19))

In [56]:
data['Weather'].unique()

array([11,  0,  2,  5, 12,  3,  8,  7,  4,  6], dtype=int64)

In [57]:
# Define the mapping of weather codes to descriptions
weather_mapping = {
    11: 'CLEAR',
    12: 'CLOUDY',
    5: 'FOG',
    2: 'RAIN',
    3: 'SLEET/HAIL',
    8: 'OTHER',
    0: 'UNK_Weather',
    4: 'SNOW_Weather',
    6: 'BLOWING SAND/SNOW',
    7: 'SEVERE CROSSWINDS'
}

# Apply this mapping across the relevant DataFrames
t_19['WEATHER_DESC'] = t_19['Weather'].map(weather_mapping)
t_20['WEATHER_DESC'] = t_20['Weather'].map(weather_mapping)
t_21['WEATHER_DESC'] = t_21['Weather'].map(weather_mapping)

# Function to perform the analysis for a given DataFrame
def analyze_weather(df):
    grouped_weather = df.groupby(['GISJOIN', 'WEATHER_DESC']).size().unstack(fill_value=0)
    total_counts_by_county_weather = grouped_weather.sum(axis=1)
    weather_percentages_df = (grouped_weather.div(total_counts_by_county_weather, axis=0) * 100).fillna(0)
    weather_percentages_df = weather_percentages_df.reset_index()
    return weather_percentages_df

# Perform the analysis for each year
weather_percentages_df_2019 = analyze_weather(t_19)
weather_percentages_df_2020 = analyze_weather(t_20)
weather_percentages_df_2021 = analyze_weather(t_21)

C:\Users\karan\AppData\Local\Temp\ipykernel_19036\4268051982.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_19['WEATHER_DESC'] = t_19['Weather'].map(weather_mapping)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\4268051982.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t_20['WEATHER_DESC'] = t_20['Weather'].map(weather_mapping)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\4268051982.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try 

In [58]:
weather_percentages_df_2019

WEATHER_DESC          GISJOIN  BLOWING SAND/SNOW       CLEAR     CLOUDY  \
0             G48000109501001                0.0  100.000000   0.000000   
1             G48000109501002                0.0   61.538462  30.769231   
2             G48000109501003                0.0   59.259259  29.629630   
3             G48000109505001                0.0   77.777778  22.222222   
4             G48000109505002                0.0   75.000000  25.000000   
...                       ...                ...         ...        ...   
10047         G48050709503021                0.0  100.000000   0.000000   
10048         G48050709503022                0.0  100.000000   0.000000   
10049         G48050709503023                0.0  100.000000   0.000000   
10050         G48050709503024                0.0  100.000000   0.000000   
10051         G48050709503025                0.0  100.000000   0.000000   

WEATHER_DESC       FOG  OTHER      RAIN  SEVERE CROSSWINDS  SLEET/HAIL  \
0             0.000000    0.0  0.000000                0.0    0.000000   
1             3.846154    0.0  3.846154                0.0    0.000000   
2             0.000000    0.0  7.407407                0.0    3.703704   
3             0.000000    0.0  0.000000                0.0    0.000000   
4             0.000000    0.0  0.000000                0.0    0.000000   
...                ...    ...       ...                ...         ...   
10047         0.000000    0.0  0.000000                0.0    0.000000   
10048         0.000000    0.0  0.000000                0.0    0.000000   
10049         0.000000    0.0  0.000000                0.0    0.000000   
10050         0.000000    0.0  0.000000                0.0    0.000000   
10051         0.000000    0.0  0.000000                0.0    0.000000   

WEATHER_DESC  SNOW_Weather  UNK_Weather  
0                      0.0          0.0  
1                      0.0          0.0  
2                      0.0          0.0  
3                      0.0          0.0  
4                      0.0          0.0  
...                    ...          ...  
10047                  0.0          0.0  
10048                  0.0          0.0  
10049                  0.0          0.0  
10050                  0.0          0.0  
10051                  0.0          0.0  

[10052 rows x 11 columns]

In [59]:
t1 = pd.merge(t1,weather_percentages_df_2019,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,weather_percentages_df_2020,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,weather_percentages_df_2021,on=['GISJOIN'],how='left')

In [60]:
t1.shape, t2.shape, t3.shape

((10052, 29), (10031, 29), (10007, 29))

In [61]:
data['Lighting'].unique()

array([6, 1, 4, 3, 5, 0, 2, 8], dtype=int64)

In [62]:
lighting_conditions = {
    1: 'DAYLIGHT',
    4: 'DARK-LIGHTED',
    3: 'DARK-NOT LIGHTED',
    6: 'DARK-UNKNOWN LIGHTING',
    5: 'DUSK',
    2: 'DAWN',
    0: 'UNK_LIGHT',
    8: 'OTHER_LIGHT'
}


In [63]:
def process_intoxication_data(df, mapping):
    # Map the intoxication codes to descriptive names
    df['light_desc'] = df['Lighting'].map(mapping).astype(str)

    # Create a list of all possible intoxication categories
    all_categories = list(mapping.values())

    # Group by COUNTY and INTOXICATION_DESC, then count occurrences
    grouped = df.groupby(['GISJOIN', 'light_desc']).size().unstack(fill_value=0)

    # Reindex the DataFrame to include all possible intoxication categories
    grouped = grouped.reindex(columns=all_categories, fill_value=0)

    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)

    # Calculate percentages
    light_percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    light_percentages_df = light_percentages_df.reset_index(drop=False)

    return light_percentages_df

# Process each year's data
l_df_2019 = process_intoxication_data(t_19, lighting_conditions)
l_df_2020 = process_intoxication_data(t_20, lighting_conditions)
l_df_2021 = process_intoxication_data(t_21, lighting_conditions)



C:\Users\karan\AppData\Local\Temp\ipykernel_19036\392848977.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['light_desc'] = df['Lighting'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\392848977.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['light_desc'] = df['Lighting'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\392848977.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .l

In [64]:
l_df_2019

light_desc          GISJOIN   DAYLIGHT  DARK-LIGHTED  DARK-NOT LIGHTED  \
0           G48000109501001   80.00000      0.000000         20.000000   
1           G48000109501002   50.00000      0.000000         50.000000   
2           G48000109501003   70.37037      0.000000         25.925926   
3           G48000109505001   70.37037     14.814815          7.407407   
4           G48000109505002   25.00000     50.000000         25.000000   
...                     ...        ...           ...               ...   
10047       G48050709503021   20.00000     60.000000         20.000000   
10048       G48050709503022    0.00000    100.000000          0.000000   
10049       G48050709503023  100.00000      0.000000          0.000000   
10050       G48050709503024  100.00000      0.000000          0.000000   
10051       G48050709503025  100.00000      0.000000          0.000000   

light_desc  DARK-UNKNOWN LIGHTING      DUSK      DAWN  UNK_LIGHT  OTHER_LIGHT  
0                             0.0  0.000000  0.000000        0.0          0.0  
1                             0.0  0.000000  0.000000        0.0          0.0  
2                             0.0  0.000000  3.703704        0.0          0.0  
3                             0.0  3.703704  3.703704        0.0          0.0  
4                             0.0  0.000000  0.000000        0.0          0.0  
...                           ...       ...       ...        ...          ...  
10047                         0.0  0.000000  0.000000        0.0          0.0  
10048                         0.0  0.000000  0.000000        0.0          0.0  
10049                         0.0  0.000000  0.000000        0.0          0.0  
10050                         0.0  0.000000  0.000000        0.0          0.0  
10051                         0.0  0.000000  0.000000        0.0          0.0  

[10052 rows x 9 columns]

In [65]:
l_df_2020

light_desc          GISJOIN   DAYLIGHT  DARK-LIGHTED  DARK-NOT LIGHTED  \
0           G48000109501001  66.666667      8.333333         16.666667   
1           G48000109501002  36.842105      0.000000         57.894737   
2           G48000109501003  35.294118      0.000000         64.705882   
3           G48000109505001  61.764706     35.294118          0.000000   
4           G48000109505002   0.000000    100.000000          0.000000   
...                     ...        ...           ...               ...   
10026       G48050709503011  62.500000      0.000000         25.000000   
10027       G48050709503021  75.000000     12.500000         12.500000   
10028       G48050709503022  50.000000     50.000000          0.000000   
10029       G48050709503024  71.428571      0.000000         14.285714   
10030       G48050709503025   0.000000      0.000000        100.000000   

light_desc  DARK-UNKNOWN LIGHTING      DUSK       DAWN  UNK_LIGHT  OTHER_LIGHT  
0                        0.000000  8.333333   0.000000        0.0          0.0  
1                        0.000000  0.000000   5.263158        0.0          0.0  
2                        0.000000  0.000000   0.000000        0.0          0.0  
3                        2.941176  0.000000   0.000000        0.0          0.0  
4                        0.000000  0.000000   0.000000        0.0          0.0  
...                           ...       ...        ...        ...          ...  
10026                    6.250000  6.250000   0.000000        0.0          0.0  
10027                    0.000000  0.000000   0.000000        0.0          0.0  
10028                    0.000000  0.000000   0.000000        0.0          0.0  
10029                    0.000000  0.000000  14.285714        0.0          0.0  
10030                    0.000000  0.000000   0.000000        0.0          0.0  

[10031 rows x 9 columns]

In [66]:
t1 = pd.merge(t1,l_df_2019,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,l_df_2020,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,l_df_2021,on=['GISJOIN'],how='left')

In [67]:
t1.shape, t2.shape, t3.shape

((10052, 37), (10031, 37), (10007, 37))

In [68]:
data['EntrRoad'].unique()

array([ 2, 98,  0,  4,  3,  5,  6,  8,  7], dtype=int64)

In [69]:
data['RoadType'].unique()

array([ 1,  2,  4, 98,  3], dtype=int64)

In [70]:
data['RoadClass'].unique()

array([2, 5, 1, 3, 4, 7, 6, 8], dtype=int64)

In [71]:
roadway_types = {
    1: 'INTERSTATE',
    2: 'US & STATE HIGHWAY',
    3: 'FARM TO MARKET',
    4: 'COUNTY ROAD',
    5: 'CITY STREET',
    6: 'TOLLWAY',
    7: 'OTHER ROADS',
    8: 'TOLL BRIDGES'
}

In [72]:
def process_road_type_data(df, mapping):
    # Map the road type codes to descriptive names
    df['ROAD_TYPE_DESC'] = df['RoadClass'].map(mapping).astype(str)
    
    # Group by COUNTY and ROAD_TYPE_DESC, then count occurrences
    grouped_road_type = df.groupby(['GISJOIN', 'ROAD_TYPE_DESC']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_road_type = grouped_road_type.sum(axis=1)
    
    # Calculate percentages
    road_type_percentages_df = (grouped_road_type.div(total_counts_by_county_road_type, axis=0) * 100).fillna(0)
    road_type_percentages_df = road_type_percentages_df.reset_index()
    
    return road_type_percentages_df

# Apply the function to each yearly DataFrame
road_type_percentages_df_2019 = process_road_type_data(t_19, roadway_types)
road_type_percentages_df_2020 = process_road_type_data(t_20, roadway_types)
road_type_percentages_df_2021 = process_road_type_data(t_21, roadway_types)


C:\Users\karan\AppData\Local\Temp\ipykernel_19036\2737281286.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ROAD_TYPE_DESC'] = df['RoadClass'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\2737281286.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ROAD_TYPE_DESC'] = df['RoadClass'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\2737281286.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.

In [73]:
road_type_percentages_df_2019

ROAD_TYPE_DESC          GISJOIN  CITY STREET  COUNTY ROAD  FARM TO MARKET  \
0               G48000109501001          0.0          0.0        0.000000   
1               G48000109501002          0.0          0.0       15.384615   
2               G48000109501003          0.0          0.0       37.037037   
3               G48000109505001          0.0          0.0        0.000000   
4               G48000109505002         25.0          0.0        0.000000   
...                         ...          ...          ...             ...   
10047           G48050709503021         20.0          0.0       80.000000   
10048           G48050709503022          0.0          0.0        0.000000   
10049           G48050709503023          0.0          0.0        0.000000   
10050           G48050709503024        100.0          0.0        0.000000   
10051           G48050709503025        100.0          0.0        0.000000   

ROAD_TYPE_DESC  INTERSTATE  OTHER ROADS  TOLL BRIDGES  TOLLWAY  \
0                      0.0          0.0           0.0      0.0   
1                      0.0          0.0           0.0      0.0   
2                      0.0          0.0           0.0      0.0   
3                      0.0          0.0           0.0      0.0   
4                      0.0          0.0           0.0      0.0   
...                    ...          ...           ...      ...   
10047                  0.0          0.0           0.0      0.0   
10048                  0.0          0.0           0.0      0.0   
10049                  0.0          0.0           0.0      0.0   
10050                  0.0          0.0           0.0      0.0   
10051                  0.0          0.0           0.0      0.0   

ROAD_TYPE_DESC  US & STATE HIGHWAY  
0                       100.000000  
1                        84.615385  
2                        62.962963  
3                       100.000000  
4                        75.000000  
...                            ...  
10047                     0.000000  
10048                   100.000000  
10049                   100.000000  
10050                     0.000000  
10051                     0.000000  

[10052 rows x 9 columns]

In [74]:
t1 = pd.merge(t1,road_type_percentages_df_2019,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,road_type_percentages_df_2020,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,road_type_percentages_df_2021,on=['GISJOIN'],how='left')

In [75]:
t1.shape, t2.shape, t3.shape

((10052, 45), (10031, 45), (10007, 45))

In [76]:
data.columns

Index(['GISJOIN', 'COUNTYFP', 'TRACTCE', 'Shape_Leng', 'nhgis0014_GISJOIN',
       'STATE', 'COUNTY', 'POPN', 'FID_Texas_XYTable_Buffer', 'Intoxication',
       'Crash_ID', 'Age', 'Ethnicity', 'Gender', 'Crash_Date', 'Crash_Time',
       'FIPS_Code', 'County_Name', 'Damage_1000', 'Speed', 'Intersection',
       'Weather', 'Lighting', 'EntrRoad', 'RoadType', 'RoadAlign', 'Surface',
       'Evnt_1', 'HmnFac_1', 'RoadPart', 'RoadClass', 'Latitude', 'Longitude',
       'Severity', 'Days', 'MedianWidth', 'NmbrLanes', 'Roadbed_Width', 'AADT',
       'Injury', 'Tot_Injry_Cnt', 'Death_Cnt', 'YEAR', 'Test', 'Shape_Length',
       'Shape_Area'],
      dtype='object')

In [77]:
data['Surface'].unique()

array([ 1,  0,  2,  6,  3,  5, 10,  8,  9], dtype=int64)

In [78]:
surface_conditions = {
    1: 'DRY',
    2: 'WET',
    3: 'STANDING WATER',
    6: 'ICE',
    9: 'SNOW_SURF',
    8: 'OTHER_SURF',
    0: 'UNKNOWN_SURF',
    5: 'SLUSH',
    10: 'SAND,MUD,DIRT'
}


In [79]:
# Function to process surface data for a given DataFrame
def process_surface_data(df, mapping):
    # Map the surface codes to descriptions
    df['SURFACE_DESC'] = df['Surface'].map(mapping).astype(str)
    
    # Group by COUNTY and SURFACE_DESC, then count occurrences
    grouped_surface = df.groupby(['GISJOIN', 'SURFACE_DESC']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_surface = grouped_surface.sum(axis=1)
    
    # Calculate percentages
    surface_percentages_df = (grouped_surface.div(total_counts_by_county_surface, axis=0) * 100).fillna(0)
    surface_percentages_df = surface_percentages_df.reset_index()
    
    return surface_percentages_df

# Apply the function to each yearly DataFrame
surface_percentages_df_2019 = process_surface_data(t_19, surface_conditions)
surface_percentages_df_2020 = process_surface_data(t_20, surface_conditions)
surface_percentages_df_2021 = process_surface_data(t_21, surface_conditions)


C:\Users\karan\AppData\Local\Temp\ipykernel_19036\1039526438.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SURFACE_DESC'] = df['Surface'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\1039526438.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SURFACE_DESC'] = df['Surface'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\1039526438.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try usi

In [80]:
surface_percentages_df_2019

SURFACE_DESC          GISJOIN         DRY  ICE  OTHER_SURF  SAND,MUD,DIRT  \
0             G48000109501001  100.000000  0.0         0.0            0.0   
1             G48000109501002   96.153846  0.0         0.0            0.0   
2             G48000109501003   88.888889  0.0         0.0            0.0   
3             G48000109505001   96.296296  0.0         0.0            0.0   
4             G48000109505002   75.000000  0.0         0.0            0.0   
...                       ...         ...  ...         ...            ...   
10047         G48050709503021  100.000000  0.0         0.0            0.0   
10048         G48050709503022  100.000000  0.0         0.0            0.0   
10049         G48050709503023  100.000000  0.0         0.0            0.0   
10050         G48050709503024  100.000000  0.0         0.0            0.0   
10051         G48050709503025  100.000000  0.0         0.0            0.0   

SURFACE_DESC     SLUSH  SNOW_SURF  STANDING WATER  UNKNOWN_SURF        WET  
0             0.000000        0.0             0.0           0.0   0.000000  
1             0.000000        0.0             0.0           0.0   3.846154  
2             3.703704        0.0             0.0           0.0   7.407407  
3             0.000000        0.0             0.0           0.0   3.703704  
4             0.000000        0.0             0.0           0.0  25.000000  
...                ...        ...             ...           ...        ...  
10047         0.000000        0.0             0.0           0.0   0.000000  
10048         0.000000        0.0             0.0           0.0   0.000000  
10049         0.000000        0.0             0.0           0.0   0.000000  
10050         0.000000        0.0             0.0           0.0   0.000000  
10051         0.000000        0.0             0.0           0.0   0.000000  

[10052 rows x 10 columns]

In [81]:
t1 = pd.merge(t1,surface_percentages_df_2019,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,surface_percentages_df_2020,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,surface_percentages_df_2021,on=['GISJOIN'],how='left')

In [82]:
t1.shape, t2.shape, t3.shape

((10052, 54), (10031, 54), (10007, 54))

In [83]:
data['HmnFac_1'].unique()

array([ 2,  8,  5, 10,  9, 11,  7,  1,  6, 12,  3,  4], dtype=int64)

In [84]:
data.columns

Index(['GISJOIN', 'COUNTYFP', 'TRACTCE', 'Shape_Leng', 'nhgis0014_GISJOIN',
       'STATE', 'COUNTY', 'POPN', 'FID_Texas_XYTable_Buffer', 'Intoxication',
       'Crash_ID', 'Age', 'Ethnicity', 'Gender', 'Crash_Date', 'Crash_Time',
       'FIPS_Code', 'County_Name', 'Damage_1000', 'Speed', 'Intersection',
       'Weather', 'Lighting', 'EntrRoad', 'RoadType', 'RoadAlign', 'Surface',
       'Evnt_1', 'HmnFac_1', 'RoadPart', 'RoadClass', 'Latitude', 'Longitude',
       'Severity', 'Days', 'MedianWidth', 'NmbrLanes', 'Roadbed_Width', 'AADT',
       'Injury', 'Tot_Injry_Cnt', 'Death_Cnt', 'YEAR', 'Test', 'Shape_Length',
       'Shape_Area'],
      dtype='object')

In [85]:
human_factor_mapping = {
    1: 'SPEEDING',
    2: 'INATTENTION',
    3: 'LANE_CHANGE',
    4: 'TAILGATING',
    5: 'VIOLATION',
    6: 'UNSAFE_BACKING',
    7: 'IMPAIRMENT',
    8: 'TURNING',
    9: 'TECH_PARK',
    10: 'NO_FAULT',
    11: 'KNOWN_HUMAN_FACTOR',
    12: 'UNKNOWN_HUMAN_FACTOR'
}


In [86]:
def process_human_factors_data(df, mapping):
    # Map the human factor codes to descriptive names
    df['HUMAN_FACTOR_DESC'] = df['HmnFac_1'].map(mapping).astype(str)
    all_categories = list(mapping.values())
    
    # Group by COUNTY and HUMAN_FACTOR_DESC, then count occurrences
    grouped = df.groupby(['GISJOIN', 'HUMAN_FACTOR_DESC']).size().unstack(fill_value=0)
    grouped = grouped.reindex(columns=all_categories, fill_value=0)
    
   
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county = grouped.sum(axis=1)
    
    # Calculate percentages
    percentages_df = (grouped.div(total_counts_by_county, axis=0) * 100).fillna(0)
    percentages_df = percentages_df.reset_index()
    
    return percentages_df

# Process each year's data
human_factors_df_2019 = process_human_factors_data(t_19, human_factor_mapping)
human_factors_df_2020 = process_human_factors_data(t_20, human_factor_mapping)
human_factors_df_2021 = process_human_factors_data(t_21, human_factor_mapping)


C:\Users\karan\AppData\Local\Temp\ipykernel_19036\4184676110.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['HUMAN_FACTOR_DESC'] = df['HmnFac_1'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\4184676110.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['HUMAN_FACTOR_DESC'] = df['HmnFac_1'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\4184676110.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFr

In [87]:
human_factors_df_2019.shape

(10052, 13)

In [88]:
human_factors_df_2020.shape

(10031, 13)

In [89]:
t1 = pd.merge(t1,human_factors_df_2019,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,human_factors_df_2020,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,human_factors_df_2021,on=['GISJOIN'],how='left')

In [90]:
data['MedianWidth'].unique()

array([  0,  50,   4, 160,  90, 100,  10,  95,  40,   2,  36,  25,  86,
        64,  60,  20, 140,  61, 300,  65,  35, 118,  38,   1,  16,  43,
        98, 136,  15,  85, 162,  14,  79,   3,  11,  12,   5, 360, 175,
       250, 120,  32,  21,  28,  72,   9,  56,  18,  68,   8,  26,  76,
        80,  44,  45, 134, 135, 137, 115, 177,  39,  29,  82,  41,  24,
        23,  17,  31,  58,  42, 150,  55, 116, 164,  63,  30,  46,  67,
        57,  49,  47,  52,  94,  92,  48,  51,  70,  22,   6, 163,  62,
        84, 267, 322, 255,  19,  78,  74,  83,  54, 152,  75,  27,  77,
        88,   7, 200, 110, 262, 101, 325,  66,  69, 123, 128,  73, 377,
       500, 450, 180, 240, 400,  59, 105, 260,  13, 124, 130, 198, 125,
       280, 376, 192,  53, 132, 174,  99,  34,  96, 158, 190,  33, 172,
       119, 167, 129, 133, 108, 350, 114, 186,  37, 375, 230, 460, 600,
        91, 248, 770, 455, 185,  71, 188, 203,  97, 214, 170, 206, 312,
       104, 225, 385,  87, 340, 165], dtype=int64)

In [91]:
t1.shape, t2.shape, t3.shape

((10052, 66), (10031, 66), (10007, 66))

In [92]:
def process_median_width_data(df):
    # Group by COUNTY and MEDIANWIDTH, then aggregate to calculate the sum and median
    aggregated_data = df.groupby('GISJOIN')['MedianWidth'].agg(['sum', 'median']).reset_index()
 
    # Rename columns for clarity
    aggregated_data.columns = ['GISJOIN', 'SUM_MEDIANWIDTH', 'MEDIAN_MEDIANWIDTH']
 
   
 
    return aggregated_data
 
# Assuming df_2019, df_2020, df_2021 are your dataframes for each respective year
median_width_summary_df_2019 = process_median_width_data(t_19)
median_width_summary_df_2020 = process_median_width_data(t_20)
median_width_summary_df_2021 = process_median_width_data(t_21)
 


In [93]:
data['MedianWidth']

0          0
1          0
2          0
3          0
4          0
          ..
986360    30
986361    30
986362    30
986363    30
986364    30
Name: MedianWidth, Length: 986365, dtype: int64

In [94]:
median_width_summary_df_2019

GISJOIN  SUM_MEDIANWIDTH  MEDIAN_MEDIANWIDTH
0      G48000109501001                0                 0.0
1      G48000109501002             1444                88.0
2      G48000109501003              845                37.0
3      G48000109505001                0                 0.0
4      G48000109505002                0                 0.0
...                ...              ...                 ...
10047  G48050709503021                0                 0.0
10048  G48050709503022                0                 0.0
10049  G48050709503023                0                 0.0
10050  G48050709503024                0                 0.0
10051  G48050709503025                0                 0.0

[10052 rows x 3 columns]

In [95]:
t1 = pd.merge(t1,median_width_summary_df_2019,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,median_width_summary_df_2020,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,median_width_summary_df_2021,on=['GISJOIN'],how='left')

In [96]:
t1

GISJOIN  COUNT  ALCOHOL  DRUG  ALCOHOL, DRUG  NO INTOXICATION  \
0      G48000109501001      5      0.0   0.0            0.0            100.0   
1      G48000109501002     26      0.0   0.0            0.0            100.0   
2      G48000109501003     27      0.0   0.0            0.0            100.0   
3      G48000109505001     27      0.0   0.0            0.0            100.0   
4      G48000109505002      4      0.0   0.0            0.0            100.0   
...                ...    ...      ...   ...            ...              ...   
10047  G48050709503021      5      0.0   0.0            0.0            100.0   
10048  G48050709503022      1      0.0   0.0            0.0            100.0   
10049  G48050709503023      1      0.0   0.0            0.0            100.0   
10050  G48050709503024      1      0.0   0.0            0.0            100.0   
10051  G48050709503025      1      0.0   0.0            0.0            100.0   

       MEDICINAL  MARIJUANA        UNK       White  ...  VIOLATION  \
0            0.0        0.0   0.000000   60.000000  ...  20.000000   
1            0.0        0.0   0.000000   57.692308  ...  23.076923   
2            0.0        0.0   0.000000   74.074074  ...  22.222222   
3            0.0        0.0   3.703704   66.666667  ...  11.111111   
4            0.0        0.0   0.000000   50.000000  ...   0.000000   
...          ...        ...        ...         ...  ...        ...   
10047        0.0        0.0  40.000000   20.000000  ...  40.000000   
10048        0.0        0.0   0.000000    0.000000  ...   0.000000   
10049        0.0        0.0   0.000000  100.000000  ...   0.000000   
10050        0.0        0.0   0.000000  100.000000  ...   0.000000   
10051        0.0        0.0   0.000000    0.000000  ...   0.000000   

       UNSAFE_BACKING  IMPAIRMENT     TURNING  TECH_PARK   NO_FAULT  \
0                 0.0         0.0   80.000000        0.0   0.000000   
1                 0.0         0.0   30.769231        0.0  30.769231   
2                 0.0         0.0   37.037037        0.0  22.222222   
3                 0.0         0.0   88.888889        0.0   0.000000   
4                 0.0         0.0  100.000000        0.0   0.000000   
...               ...         ...         ...        ...        ...   
10047             0.0         0.0   40.000000        0.0   0.000000   
10048             0.0         0.0  100.000000        0.0   0.000000   
10049             0.0         0.0  100.000000        0.0   0.000000   
10050             0.0         0.0  100.000000        0.0   0.000000   
10051             0.0         0.0  100.000000        0.0   0.000000   

       KNOWN_HUMAN_FACTOR  UNKNOWN_HUMAN_FACTOR  SUM_MEDIANWIDTH  \
0                     0.0                   0.0                0   
1                     0.0                   0.0             1444   
2                     0.0                   0.0              845   
3                     0.0                   0.0                0   
4                     0.0                   0.0                0   
...                   ...                   ...              ...   
10047                 0.0                   0.0                0   
10048                 0.0                   0.0                0   
10049                 0.0                   0.0                0   
10050                 0.0                   0.0                0   
10051                 0.0                   0.0                0   

       MEDIAN_MEDIANWIDTH  
0                     0.0  
1                    88.0  
2                    37.0  
3                     0.0  
4                     0.0  
...                   ...  
10047                 0.0  
10048                 0.0  
10049                 0.0  
10050                 0.0  
10051                 0.0  

[10052 rows x 68 columns]

In [97]:
data['RoadType'].unique()

array([ 1,  2,  4, 98,  3], dtype=int64)

In [98]:
road_typ_map ={
    0:'OTHR_RD_TYP',
    1:'2L2W',
    2:'4LND',
    3:'4LUND'
}

In [99]:
# Function to process surface data for a given DataFrame
def process_surface_data(df, mapping):
    # Map the surface codes to descriptions
    df['road_desc'] = df['RoadType'].map(mapping).astype(str)
    
    # Group by COUNTY and SURFACE_DESC, then count occurrences
    grouped_surface = df.groupby(['GISJOIN', 'road_desc']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_surface = grouped_surface.sum(axis=1)
    
    # Calculate percentages
    rt_percentages_df = (grouped_surface.div(total_counts_by_county_surface, axis=0) * 100).fillna(0)
    rt_percentages_df = rt_percentages_df.reset_index()
    
    return rt_percentages_df

# Apply the function to each yearly DataFrame
rt_percentages_df_2019 = process_surface_data(t_19, road_typ_map)
rt_percentages_df_2020 = process_surface_data(t_20, road_typ_map)
rt_percentages_df_2021 = process_surface_data(t_21, road_typ_map)

C:\Users\karan\AppData\Local\Temp\ipykernel_19036\188161795.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['road_desc'] = df['RoadType'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\188161795.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['road_desc'] = df['RoadType'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\188161795.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc

In [100]:
rt_percentages_df_2019

road_desc          GISJOIN        2L2W       4LND      4LUND    nan
0          G48000109501001   60.000000  20.000000  20.000000    0.0
1          G48000109501002   30.769231  69.230769   0.000000    0.0
2          G48000109501003   51.851852  40.740741   7.407407    0.0
3          G48000109505001   51.851852  48.148148   0.000000    0.0
4          G48000109505002   75.000000  25.000000   0.000000    0.0
...                    ...         ...        ...        ...    ...
10047      G48050709503021   20.000000  60.000000  20.000000    0.0
10048      G48050709503022  100.000000   0.000000   0.000000    0.0
10049      G48050709503023  100.000000   0.000000   0.000000    0.0
10050      G48050709503024  100.000000   0.000000   0.000000    0.0
10051      G48050709503025    0.000000   0.000000   0.000000  100.0

[10052 rows x 5 columns]

In [101]:
data['Severity'].unique()

array([5, 0, 2, 3, 4, 1], dtype=int64)

In [102]:
sev_map = {
    0:'UNK_SEVERITY',
    1:'SSI',
    2:'MIN_INJURY',
    3:'POSBL_INJURY',
    4:'FATAL',
    5:'NO_INJURY'
    
}

In [103]:
def process_road_type_data(df, mapping):
    # Map the road type codes to descriptive names
    df['Sev_DESC'] = df['Severity'].map(mapping).astype(str)
    
    # Group by COUNTY and ROAD_TYPE_DESC, then count occurrences
    grouped_road_type = df.groupby(['GISJOIN', 'Sev_DESC']).size().unstack(fill_value=0)
    
    # Calculate total counts by county to normalize the data
    total_counts_by_county_road_type = grouped_road_type.sum(axis=1)
    
    # Calculate percentages
    road_type_percentages_df = (grouped_road_type.div(total_counts_by_county_road_type, axis=0) * 100).fillna(0)
    road_type_percentages_df = road_type_percentages_df.reset_index()
    
    return road_type_percentages_df

# Apply the function to each yearly DataFrame
road_type_percentages_df_2019 = process_road_type_data(t_19, sev_map)
road_type_percentages_df_2020 = process_road_type_data(t_20, sev_map)
road_type_percentages_df_2021 = process_road_type_data(t_21, sev_map)


C:\Users\karan\AppData\Local\Temp\ipykernel_19036\3024294412.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sev_DESC'] = df['Severity'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\3024294412.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sev_DESC'] = df['Severity'].map(mapping).astype(str)
C:\Users\karan\AppData\Local\Temp\ipykernel_19036\3024294412.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .lo

In [104]:
road_type_percentages_df_2019

Sev_DESC          GISJOIN     FATAL  MIN_INJURY   NO_INJURY  POSBL_INJURY  \
0         G48000109501001  0.000000   40.000000   60.000000      0.000000   
1         G48000109501002  3.846154   11.538462   53.846154     19.230769   
2         G48000109501003  3.703704   25.925926   51.851852     18.518519   
3         G48000109505001  0.000000    3.703704   62.962963     29.629630   
4         G48000109505002  0.000000    0.000000   75.000000     25.000000   
...                   ...       ...         ...         ...           ...   
10047     G48050709503021  0.000000   20.000000   40.000000      0.000000   
10048     G48050709503022  0.000000    0.000000    0.000000    100.000000   
10049     G48050709503023  0.000000  100.000000    0.000000      0.000000   
10050     G48050709503024  0.000000    0.000000  100.000000      0.000000   
10051     G48050709503025  0.000000    0.000000  100.000000      0.000000   

Sev_DESC       SSI  UNK_SEVERITY  
0         0.000000      0.000000  
1         7.692308      3.846154  
2         0.000000      0.000000  
3         3.703704      0.000000  
4         0.000000      0.000000  
...            ...           ...  
10047     0.000000     40.000000  
10048     0.000000      0.000000  
10049     0.000000      0.000000  
10050     0.000000      0.000000  
10051     0.000000      0.000000  

[10052 rows x 7 columns]

In [105]:
t1 = pd.merge(t1,road_type_percentages_df_2019,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,road_type_percentages_df_2020,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,road_type_percentages_df_2021,on=['GISJOIN'],how='left')

In [106]:
t1

GISJOIN  COUNT  ALCOHOL  DRUG  ALCOHOL, DRUG  NO INTOXICATION  \
0      G48000109501001      5      0.0   0.0            0.0            100.0   
1      G48000109501002     26      0.0   0.0            0.0            100.0   
2      G48000109501003     27      0.0   0.0            0.0            100.0   
3      G48000109505001     27      0.0   0.0            0.0            100.0   
4      G48000109505002      4      0.0   0.0            0.0            100.0   
...                ...    ...      ...   ...            ...              ...   
10047  G48050709503021      5      0.0   0.0            0.0            100.0   
10048  G48050709503022      1      0.0   0.0            0.0            100.0   
10049  G48050709503023      1      0.0   0.0            0.0            100.0   
10050  G48050709503024      1      0.0   0.0            0.0            100.0   
10051  G48050709503025      1      0.0   0.0            0.0            100.0   

       MEDICINAL  MARIJUANA        UNK       White  ...  KNOWN_HUMAN_FACTOR  \
0            0.0        0.0   0.000000   60.000000  ...                 0.0   
1            0.0        0.0   0.000000   57.692308  ...                 0.0   
2            0.0        0.0   0.000000   74.074074  ...                 0.0   
3            0.0        0.0   3.703704   66.666667  ...                 0.0   
4            0.0        0.0   0.000000   50.000000  ...                 0.0   
...          ...        ...        ...         ...  ...                 ...   
10047        0.0        0.0  40.000000   20.000000  ...                 0.0   
10048        0.0        0.0   0.000000    0.000000  ...                 0.0   
10049        0.0        0.0   0.000000  100.000000  ...                 0.0   
10050        0.0        0.0   0.000000  100.000000  ...                 0.0   
10051        0.0        0.0   0.000000    0.000000  ...                 0.0   

       UNKNOWN_HUMAN_FACTOR  SUM_MEDIANWIDTH  MEDIAN_MEDIANWIDTH     FATAL  \
0                       0.0                0                 0.0  0.000000   
1                       0.0             1444                88.0  3.846154   
2                       0.0              845                37.0  3.703704   
3                       0.0                0                 0.0  0.000000   
4                       0.0                0                 0.0  0.000000   
...                     ...              ...                 ...       ...   
10047                   0.0                0                 0.0  0.000000   
10048                   0.0                0                 0.0  0.000000   
10049                   0.0                0                 0.0  0.000000   
10050                   0.0                0                 0.0  0.000000   
10051                   0.0                0                 0.0  0.000000   

       MIN_INJURY   NO_INJURY  POSBL_INJURY       SSI  UNK_SEVERITY  
0       40.000000   60.000000      0.000000  0.000000      0.000000  
1       11.538462   53.846154     19.230769  7.692308      3.846154  
2       25.925926   51.851852     18.518519  0.000000      0.000000  
3        3.703704   62.962963     29.629630  3.703704      0.000000  
4        0.000000   75.000000     25.000000  0.000000      0.000000  
...           ...         ...           ...       ...           ...  
10047   20.000000   40.000000      0.000000  0.000000     40.000000  
10048    0.000000    0.000000    100.000000  0.000000      0.000000  
10049  100.000000    0.000000      0.000000  0.000000      0.000000  
10050    0.000000  100.000000      0.000000  0.000000      0.000000  
10051    0.000000  100.000000      0.000000  0.000000      0.000000  

[10052 rows x 74 columns]

In [107]:
data.columns

Index(['GISJOIN', 'COUNTYFP', 'TRACTCE', 'Shape_Leng', 'nhgis0014_GISJOIN',
       'STATE', 'COUNTY', 'POPN', 'FID_Texas_XYTable_Buffer', 'Intoxication',
       'Crash_ID', 'Age', 'Ethnicity', 'Gender', 'Crash_Date', 'Crash_Time',
       'FIPS_Code', 'County_Name', 'Damage_1000', 'Speed', 'Intersection',
       'Weather', 'Lighting', 'EntrRoad', 'RoadType', 'RoadAlign', 'Surface',
       'Evnt_1', 'HmnFac_1', 'RoadPart', 'RoadClass', 'Latitude', 'Longitude',
       'Severity', 'Days', 'MedianWidth', 'NmbrLanes', 'Roadbed_Width', 'AADT',
       'Injury', 'Tot_Injry_Cnt', 'Death_Cnt', 'YEAR', 'Test', 'Shape_Length',
       'Shape_Area'],
      dtype='object')

In [108]:
data['NmbrLanes'].unique()

array([ 4,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 14,  1, 13],
      dtype=int64)

In [109]:
data['Intoxication'].unique()

array([4, 6, 2, 5], dtype=int64)

In [110]:
data['Test'].unique()

array([4, 6, 2, 1, 5, 3], dtype=int64)

In [111]:
data.columns

Index(['GISJOIN', 'COUNTYFP', 'TRACTCE', 'Shape_Leng', 'nhgis0014_GISJOIN',
       'STATE', 'COUNTY', 'POPN', 'FID_Texas_XYTable_Buffer', 'Intoxication',
       'Crash_ID', 'Age', 'Ethnicity', 'Gender', 'Crash_Date', 'Crash_Time',
       'FIPS_Code', 'County_Name', 'Damage_1000', 'Speed', 'Intersection',
       'Weather', 'Lighting', 'EntrRoad', 'RoadType', 'RoadAlign', 'Surface',
       'Evnt_1', 'HmnFac_1', 'RoadPart', 'RoadClass', 'Latitude', 'Longitude',
       'Severity', 'Days', 'MedianWidth', 'NmbrLanes', 'Roadbed_Width', 'AADT',
       'Injury', 'Tot_Injry_Cnt', 'Death_Cnt', 'YEAR', 'Test', 'Shape_Length',
       'Shape_Area'],
      dtype='object')

In [112]:
data['Injury']

0         0
1         0
2         0
3         0
4         0
         ..
986360    1
986361    0
986362    0
986363    1
986364    0
Name: Injury, Length: 986365, dtype: int64

In [113]:
grouped_intersection = t_19.groupby(['GISJOIN', 'Injury']).size().unstack(fill_value=0 )
grouped_intersection

Injury            0   1
GISJOIN                
G48000109501001   3   2
G48000109501002  15  11
G48000109501003  14  13
G48000109505001  17  10
G48000109505002   3   1
...              ..  ..
G48050709503021   4   1
G48050709503022   0   1
G48050709503023   0   1
G48050709503024   1   0
G48050709503025   1   0

[10052 rows x 2 columns]

In [114]:
def calculate_intersection_percentages(df):
    grouped_intersection = df.groupby(['GISJOIN', 'Injury']).size().unstack(fill_value=0)
    grouped_intersection.columns = ['NO_INJ', 'YES_INJ']
    total_counts_by_county = grouped_intersection.sum(axis=1)
    no_intersection_percentage = (grouped_intersection['NO_INJ'] / total_counts_by_county) * 100
    yes_intersection_percentage = (grouped_intersection['YES_INJ'] / total_counts_by_county) * 100

    intersection_percentages_df = pd.concat([
        no_intersection_percentage,
        yes_intersection_percentage
    ], axis=1)
    intersection_percentages_df.columns = ['NO_INJ', 'YES_INJ']
    intersection_percentages_df = intersection_percentages_df.reset_index().rename(columns={'index': 'GISJOIN'})
    intersection_percentages_df.fillna(0, inplace=True)

    return intersection_percentages_df

In [115]:
t11 = calculate_intersection_percentages(t_19)

In [116]:
t22 = calculate_intersection_percentages(t_20)
t33 = calculate_intersection_percentages(t_21)

In [117]:
t1 = pd.merge(t1,t11,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,t22,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,t33,on=['GISJOIN'],how='left')

In [118]:
t1.isna().sum().sum()

0

In [119]:
t1.columns

Index(['GISJOIN', 'COUNT', 'ALCOHOL', 'DRUG', 'ALCOHOL, DRUG',
       'NO INTOXICATION', 'MEDICINAL', 'MARIJUANA', 'UNK', 'White', 'Hispanic',
       'Black', 'Asian', 'Other', 'American Native', 'NO_Damage', 'YES_Damage',
       'NO_Intersection', 'YES_Intersection', 'BLOWING SAND/SNOW', 'CLEAR',
       'CLOUDY', 'FOG', 'OTHER', 'RAIN', 'SEVERE CROSSWINDS', 'SLEET/HAIL',
       'SNOW_Weather', 'UNK_Weather', 'DAYLIGHT', 'DARK-LIGHTED',
       'DARK-NOT LIGHTED', 'DARK-UNKNOWN LIGHTING', 'DUSK', 'DAWN',
       'UNK_LIGHT', 'OTHER_LIGHT', 'CITY STREET', 'COUNTY ROAD',
       'FARM TO MARKET', 'INTERSTATE', 'OTHER ROADS', 'TOLL BRIDGES',
       'TOLLWAY', 'US & STATE HIGHWAY', 'DRY', 'ICE', 'OTHER_SURF',
       'SAND,MUD,DIRT', 'SLUSH', 'SNOW_SURF', 'STANDING WATER', 'UNKNOWN_SURF',
       'WET', 'SPEEDING', 'INATTENTION', 'LANE_CHANGE', 'TAILGATING',
       'VIOLATION', 'UNSAFE_BACKING', 'IMPAIRMENT', 'TURNING', 'TECH_PARK',
       'NO_FAULT', 'KNOWN_HUMAN_FACTOR', 'UNKNOWN_HUMAN_FACTOR

In [120]:
t1[['NO_INJ', 'YES_INJ']]

NO_INJ     YES_INJ
0       60.000000   40.000000
1       57.692308   42.307692
2       51.851852   48.148148
3       62.962963   37.037037
4       75.000000   25.000000
...           ...         ...
10047   80.000000   20.000000
10048    0.000000  100.000000
10049    0.000000  100.000000
10050  100.000000    0.000000
10051  100.000000    0.000000

[10052 rows x 2 columns]

In [121]:
def process_median_width_data(df):
    # Group by COUNTY and MEDIANWIDTH, then aggregate to calculate the sum and median
    aggregated_data = df.groupby('GISJOIN')['Tot_Injry_Cnt'].agg(['sum']).reset_index()
 
    # Rename columns for clarity
    aggregated_data.columns = ['GISJOIN', 'INJ_COUNT_SUM']
 
   
 
    return aggregated_data
 
# Assuming df_2019, df_2020, df_2021 are your dataframes for each respective year
median_width_summary_df_2019 = process_median_width_data(t_19)
median_width_summary_df_2020 = process_median_width_data(t_20)
median_width_summary_df_2021 = process_median_width_data(t_21)
 


In [122]:
t1 = pd.merge(t1,median_width_summary_df_2019,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,median_width_summary_df_2020,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,median_width_summary_df_2021,on=['GISJOIN'],how='left')

In [123]:
t1.shape, t2.shape, t3.shape

((10052, 77), (10031, 77), (10007, 77))

In [124]:
texas = pd.concat([t1,t2,t3],axis=0)

In [125]:
texas.isna().sum().sum()

0

In [126]:
#texas.to_csv('texas.csv',index= False)

In [127]:
t10 = t_19.groupby(['GISJOIN','POPN'])

In [128]:
t10 = t10.size()

In [129]:
t10 = t10.reset_index()

In [130]:
t10.drop(columns={0},inplace= True)

In [131]:
t10

GISJOIN  POPN
0      G48000109501001  1640
1      G48000109501002  1901
2      G48000109501003  1417
3      G48000109505001  1093
4      G48000109505002   444
...                ...   ...
10047  G48050709503021  1827
10048  G48050709503022   198
10049  G48050709503023  1659
10050  G48050709503024   588
10051  G48050709503025  2197

[10052 rows x 2 columns]

In [132]:
t20 = t_20.groupby(['GISJOIN','POPN'])
t20 = t20.size()
t20 = t20.reset_index()

In [133]:
t20.drop(columns={0},inplace= True)

In [134]:
t20

GISJOIN  POPN
0      G48000109501001  1640
1      G48000109501002  1901
2      G48000109501003  1417
3      G48000109505001  1093
4      G48000109505002   444
...                ...   ...
10026  G48050709503011   631
10027  G48050709503021  1827
10028  G48050709503022   198
10029  G48050709503024   588
10030  G48050709503025  2197

[10031 rows x 2 columns]

In [135]:
t30 = t_21.groupby(['GISJOIN','POPN'])
t30 = t30.size()
t30 = t30.reset_index()
t30.drop(columns={0},inplace= True)

In [136]:
t30

GISJOIN  POPN
0      G48000109501001  1640
1      G48000109501002  1901
2      G48000109501003  1417
3      G48000109504021  7335
4      G48000109505001  1093
...                ...   ...
10002  G48050709503011   631
10003  G48050709503021  1827
10004  G48050709503023  1659
10005  G48050709503024   588
10006  G48050709503025  2197

[10007 rows x 2 columns]

In [137]:
t1 = pd.merge(t1,t10,on=['GISJOIN'],how='left')
t2 = pd.merge(t2,t20,on=['GISJOIN'],how='left')
t3 = pd.merge(t3,t30,on=['GISJOIN'],how='left')

In [138]:
t1['YEAR'] = 2019
t2['YEAR'] = 2020
t3['YEAR'] = 2021

In [139]:
t1.to_csv('texas_2019.csv',index=False)

In [140]:
t2.to_csv('texas_2020.csv',index= False)

In [141]:
t3.to_csv('texas_2021.csv',index= False)

In [143]:
t1.shape, t2.shape, t3.shape

((10052, 79), (10031, 79), (10007, 79))

In [144]:
v = t1.columns.intersection(t2.columns)
len(v)

79

In [ ]:
texas['STATE'] = 'Texas'

In [ ]:
texas = pd.concat([t1,t2,t3],axis=0)

In [ ]:
texas['STATE'] = 'Texas'

In [ ]:
texas.columns

In [ ]:
texas.to_csv('texas.csv',index= False)